-- ── LISTA DE REFERENCIA ──
INSERT INTO `dev-izipay-data-storage.master_party.lista_referencia_nomcom`
(id, nombre_comercial, razon_social, origen, activo, fecha_actualizacion)
VALUES
(1,  'SMART FIT',                  'SMART FIT PERU S.A.C.',                'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(2,  'PLAZA VEA',                  'SUPERMERCADOS PERUANOS S.A.',          'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(3,  'INKAFARMA',                  'INKAFARMA S.A.C.',                     'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(4,  'BEMBOS',                     'BEMBOS S.A.C.',                        'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(5,  'CINEPLANET',                 'CINEPLEX S.A.',                        'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(6,  'INTERBANK',                  'BANCO INTERNACIONAL DEL PERU S.A.A.',  'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(7,  'REAL PLAZA',                 'REAL PLAZA S.R.L.',                    'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(8,  'OECHSLE',                    'TIENDAS PERUANAS S.A.',                'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(9,  'PROMART',                    'HOMECENTERS PERUANOS S.A.',            'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(10, 'CASA ANDINA',                'NESSUS HOTELES PERU S.A.',             'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(11, 'PAPA JOHNS',                 'CORPORACION PERUANA DE RESTAURANTES S.A.', 'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(12, 'DUNKIN DONUTS',              'EP DE FRANQUICIAS S.A.C.',             'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(13, 'MAKRO',                      'MAKRO SUPERMAYORISTA S.A.',            'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(14, 'MIFARMA',                    'MIFARMA S.A.C.',                       'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(15, 'FINANCIERA OH',              'FINANCIERA OH S.A.',                   'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(16, 'ONLYFANS',                   NULL,                                   'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(17, 'SHOPSTAR',                   'SHOPSTAR S.A.C.',                      'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(18, 'INNOVA SCHOOLS',             'COLEGIOS PERUANOS S.A.',               'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(19, 'LA TINKA',                   'LA TINKA S.A.',                        'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(20, 'DON BELISARIO',              'SERVICIOS COMPARTIDOS DE RESTAURANTES S.A.C.', 'ADHOC', TRUE, CURRENT_TIMESTAMP()),
(101, 'DISTRIBUIDORA LA GRANJE',   'DISTRIBUIDORA LA GRANJE S.A.C.',      'RUC20_PARQUE', TRUE, CURRENT_TIMESTAMP()),
(102, 'PEPITO DISTRIBUCIONES',     'PEPITO DISTRIBUCIONES E.I.R.L.',      'RUC20_PARQUE', TRUE, CURRENT_TIMESTAMP()),
(103, 'BOTICA UNIVERSAL',          'BOTICA UNIVERSAL S.R.L.',             'RUC20_PARQUE', TRUE, CURRENT_TIMESTAMP()),
(104, 'RESTAURANT EL PACIFICO',    'RESTAURANT EL PACIFICO S.A.C.',       'RUC20_PARQUE', TRUE, CURRENT_TIMESTAMP()),
(105, 'FERRETERIA MENDOZA',        'FERRETERIA MENDOZA E.I.R.L.',         'RUC20_PARQUE', TRUE, CURRENT_TIMESTAMP()),
(106, 'MARKET EXPRESS PERU',       'MARKET EXPRESS PERU S.A.C.',          'RUC20_PARQUE', TRUE, CURRENT_TIMESTAMP()),
(107, 'ELECTRONICA GLOBAL',        'ELECTRONICA GLOBAL S.A.',             'RUC20_PARQUE', TRUE, CURRENT_TIMESTAMP()),
(108, 'SUPERMERCADO CENTRAL',      'SUPERMERCADO CENTRAL S.A.C.',         'RUC20_PARQUE', TRUE, CURRENT_TIMESTAMP()),
(201, 'TIENDA RAPIDA PERU',        'TIENDA RAPIDA PERU S.A.C.',           'ROYC', TRUE, CURRENT_TIMESTAMP()),
(202, 'FARMACIA SOLIDARIA',        'FARMACIA SOLIDARIA E.I.R.L.',         'ROYC', TRUE, CURRENT_TIMESTAMP()),
(203, 'SANTA CLARA COMPRAS',       NULL,                                  'ROYC', TRUE, CURRENT_TIMESTAMP()),
(204, 'GRUPO TUCASA',              NULL,                                  'ROYC', TRUE, CURRENT_TIMESTAMP()),
(205, 'CLICK COMPRAS PERU',        NULL,                                  'ROYC', TRUE, CURRENT_TIMESTAMP()),
(206, 'POSITIVA EMPRESARIAL',      NULL,                                  'ROYC', TRUE, CURRENT_TIMESTAMP())
