-- ── AFILIACIONES DE PRUEBA ──
INSERT INTO `dev-izipay-data-storage.master_party.lista_afiliaciones_analizar`
(cod_comercio, nom_comercio, razon_social, representante_legal, tipo_documento, fecha_apertura_comercio, fecha_carga)
VALUES
('TEST001', 'IZI*ZMARTF1T',      'JUAN PEREZ GARCIA',      'JUAN PEREZ GARCIA',      'DNI',    '2025-03-10', CURRENT_TIMESTAMP()),
('TEST002', 'IZI*PLAZ4 VEA',     'MARIA LOPEZ RIOS',       'MARIA LOPEZ RIOS',       'RUC 10', '2025-03-10', CURRENT_TIMESTAMP()),
('TEST003', 'IZI*INKAF4RMA',     'PEDRO DIAZ SOTO',        'PEDRO DIAZ SOTO',        'CE',     '2025-03-10', CURRENT_TIMESTAMP()),
('TEST004', 'IZI*B3MBOS',        'ANA TORRES LUNA',        'ANA TORRES LUNA',        'DNI',    '2025-03-10', CURRENT_TIMESTAMP()),
('TEST005', 'IZI*SMART FITT',    'CARLOS RUIZ MEJIA',      'CARLOS RUIZ MEJIA',      'RUC 15', '2025-03-09', CURRENT_TIMESTAMP()),
('TEST006', 'IZI*PLZA VEA EXPRESS', 'ROSA FLORES DIAZ',    'ROSA FLORES DIAZ',       'RUC 17', '2025-03-09', CURRENT_TIMESTAMP()),
('TEST007', 'IZI*SMART HOUSE',   'LUIS GARCIA RAMOS',      'LUIS GARCIA RAMOS',       'DNI',    '2025-03-09', CURRENT_TIMESTAMP()),
('TEST008', 'IZI*JUAN PEREZ',    'JUAN PEREZ',             'JUAN PEREZ',              'DNI',    '2025-03-08', CURRENT_TIMESTAMP()),
('TEST009', 'IZI*P3P1T0 D1STR1BUC10N3S', 'FAKE PERSONA', 'FAKE PERSONA',            'DNI',    '2025-03-10', CURRENT_TIMESTAMP()),
('TEST010', 'IZI*L4 GR4NJ3',     'OTRO PERSONA',           'OTRO PERSONA',            'RUC 10', '2025-03-10', CURRENT_TIMESTAMP()),
('TEST011', 'IZI*SINEPLENET',    'TEST PERSONA',           'TEST PERSONA',            'DNI',    '2025-03-10', CURRENT_TIMESTAMP()),
('TEST012', 'IZI*BODEGA DON MIGUEL', 'MIGUEL SANTOS',      'MIGUEL SANTOS',           'DNI',    '2025-03-10', CURRENT_TIMESTAMP())
