CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.master_risk.m_consolidacion_fraudes (
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
fecha_trx DATE  OPTIONS(description='Fecha en la que se realizó la transacción asociada al caso de fraude'),
tarjeta_encriptada STRING  OPTIONS(description='Identificador encriptado o enmascarado de la tarjeta involucrada en la transacción'),
cod_comercio STRING  OPTIONS(description='Código que identifica al comercio donde se efectuó la transacción'),
cod_respuesta STRING  OPTIONS(description='Código de respuesta asignada a la ransacción'),
cod_autorizacion STRING  OPTIONS(description='Código de autorización asignado a la transacción'),
mto_fraude_soles FLOAT64  OPTIONS(description='Monto del fraude expresado en moneda nacional (soles)'),
nom_comercio STRING  OPTIONS(description='Nombre comercial del establecimiento donde ocurrió la transacción'),
accion_tomada STRING  OPTIONS(description='Acción ejecutada como resultado del análisis o gestión del caso'),
tipo_fraude_marcado STRING  OPTIONS(description='Tipo o categoría de fraude asignada a la transacción'),
fecha_carga DATE  OPTIONS(description='Fecha en la que el registro fue cargado al repositorio o sistema'),
estado_fraude STRING  OPTIONS(description='Estado actual del caso de fraude dentro del flujo de gestión (Filtro: Marcado Alerta, Enviado, Filtro: Cruce Transaccional, Segundo_Reproceso_Enviado, Segundo_Reproceso_Filtro: Cruce Transaccional)'),
fecha_envio DATE  OPTIONS(description='Fecha en la que la información del caso fue enviada a otra entidad o sistema'),
nom_entidad STRING  OPTIONS(description='Entidad que procesa el fraude: ADQ (Adquirente) o EMISOR'),
proceso STRING  OPTIONS(description='Hace referencia al tipo de carga que se está realizando, para diferenciarlo de cargas masivas'),
tarjeta_sha256_trx STRING  OPTIONS(description='Hash SHA256 de la tarjeta obtenido del sistema transaccional. Se popula únicamente en estados Enviado y Segundo_Reproceso_Enviado'),
hora_trx STRING  OPTIONS(description='Hora exacta de la transacción obtenida del sistema transaccional'),
mto_trx STRING  OPTIONS(description='Monto real de la transacción confirmado desde el sistema transaccional'),
codigo_cio_trx STRING  OPTIONS(description='Código completo del comercio (CIO) tal como aparece en el sistema transaccional'),
nom_cio_trx STRING  OPTIONS(description='Nombre del comercio obtenido del sistema transaccional'),
cod_giro_comercio_trx STRING  OPTIONS(description='Código MCC (Merchant Category Code) del comercio — rubro o giro del negocio'),
bin_trx STRING  OPTIONS(description='BIN (Bank Identification Number) de la tarjeta registrado en el sistema transaccional'),
id_cliente_trx STRING  OPTIONS(description='Identificador único del cliente titular de la tarjeta, proveniente del sistema transaccional'),
entry_mode_trx STRING  OPTIONS(description='Modo de ingreso de la tarjeta en la transacción (chip, banda magnética, contactless, manual, etc.)'),
ucaf_trx STRING  OPTIONS(description='Universal Cardholder Authentication Field — dato de autenticación del portador de la tarjeta'),
canal_trx STRING  OPTIONS(description='Canal por el cual se realizó la transacción (presencial, web, app, MOTO, etc.)'),
id_comercio_trx STRING  OPTIONS(description='Identificador interno del comercio en el sistema transaccional'),
tarjetaregistro750_trx STRING  OPTIONS(description='Tarjeta enmascarada en formato 750 (PAN enmascarado) proveniente del sistema transaccional'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date DATETIME NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD')
)
PARTITION BY process_date
CLUSTER BY fecha_trx, accion_tomada, estado_fraude, nom_entidad
OPTIONS (description='Tabla que contiene el status de los fraudes que están involucrados en el proceso');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.master_risk.m_consolidacion_fraudes_h (
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
fecha_trx DATE  OPTIONS(description='Fecha en la que se realizó la transacción asociada al caso de fraude'),
tarjeta_encriptada STRING  OPTIONS(description='Identificador encriptado o enmascarado de la tarjeta involucrada en la transacción'),
cod_comercio STRING  OPTIONS(description='Código que identifica al comercio donde se efectuó la transacción'),
cod_respuesta STRING  OPTIONS(description='Código de respuesta asignada a la ransacción'),
cod_autorizacion STRING  OPTIONS(description='Código de autorización asignado a la transacción'),
mto_fraude_soles FLOAT64  OPTIONS(description='Monto del fraude expresado en moneda nacional (soles)'),
nom_comercio STRING  OPTIONS(description='Nombre comercial del establecimiento donde ocurrió la transacción'),
accion_tomada STRING  OPTIONS(description='Acción ejecutada como resultado del análisis o gestión del caso'),
tipo_fraude_marcado STRING  OPTIONS(description='Tipo o categoría de fraude asignada a la transacción'),
fecha_carga DATE  OPTIONS(description='Fecha en la que el registro fue cargado al repositorio o sistema'),
estado_fraude STRING  OPTIONS(description='Estado actual del caso de fraude dentro del flujo de gestión (Filtro: Marcado Alerta, Enviado, Filtro: Cruce Transaccional, Segundo_Reproceso_Enviado, Segundo_Reproceso_Filtro: Cruce Transaccional)'),
fecha_envio DATE  OPTIONS(description='Fecha en la que la información del caso fue enviada a otra entidad o sistema'),
nom_entidad STRING  OPTIONS(description='Entidad que procesa el fraude: ADQ (Adquirente) o EMISOR'),
proceso STRING  OPTIONS(description='Hace referencia al tipo de carga que se está realizando, para diferenciarlo de cargas masivas'),
tarjeta_sha256_trx STRING  OPTIONS(description='Hash SHA256 de la tarjeta obtenido del sistema transaccional. Se popula únicamente en estados Enviado y Segundo_Reproceso_Enviado'),
hora_trx STRING  OPTIONS(description='Hora exacta de la transacción obtenida del sistema transaccional'),
mto_trx STRING  OPTIONS(description='Monto real de la transacción confirmado desde el sistema transaccional'),
codigo_cio_trx STRING  OPTIONS(description='Código completo del comercio (CIO) tal como aparece en el sistema transaccional'),
nom_cio_trx STRING  OPTIONS(description='Nombre del comercio obtenido del sistema transaccional'),
cod_giro_comercio_trx STRING  OPTIONS(description='Código MCC (Merchant Category Code) del comercio — rubro o giro del negocio'),
bin_trx STRING  OPTIONS(description='BIN (Bank Identification Number) de la tarjeta registrado en el sistema transaccional'),
id_cliente_trx STRING  OPTIONS(description='Identificador único del cliente titular de la tarjeta, proveniente del sistema transaccional'),
entry_mode_trx STRING  OPTIONS(description='Modo de ingreso de la tarjeta en la transacción (chip, banda magnética, contactless, manual, etc.)'),
ucaf_trx STRING  OPTIONS(description='Universal Cardholder Authentication Field — dato de autenticación del portador de la tarjeta'),
canal_trx STRING  OPTIONS(description='Canal por el cual se realizó la transacción (presencial, web, app, MOTO, etc.)'),
id_comercio_trx STRING  OPTIONS(description='Identificador interno del comercio en el sistema transaccional'),
tarjetaregistro750_trx STRING  OPTIONS(description='Tarjeta enmascarada en formato 750 (PAN enmascarado) proveniente del sistema transaccional'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date DATETIME NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD')
)
PARTITION BY process_date
CLUSTER BY fecha_trx, accion_tomada, estado_fraude, nom_entidad
OPTIONS (description='Tabla histórica que contiene el status de los fraudes que están involucrados en el proceso');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.master_risk.m_fraudes_externos (
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
cod_reclamo STRING  OPTIONS(description='Código de Reclamo'),
correlativo STRING  OPTIONS(description='Correlativo único del registro. Formato YYMMDD + secuencia de 4 dígitos'),
usuario_reclamo STRING  OPTIONS(description='Usuario que tomó el Reclamo'),
sucursal_reclamo STRING  OPTIONS(description='Sucursal de Reclamo'),
fecha_reclamo DATE  OPTIONS(description='Fecha del Reclamo'),
hora_reclamo STRING  OPTIONS(description='Hora del Reclamo'),
detalle_reclamo STRING  OPTIONS(description='Detalle del Reclamo — fuente del fraude (TC40, Safe, Asbanc, Contracargos)'),
medio_canal_reclamo STRING  OPTIONS(description='Medio o Canal del Reclamo'),
fuente_reclamo STRING  OPTIONS(description='Fuente del Reclamo'),
departamento_division STRING  OPTIONS(description='Departamento / División / Área'),
cod_evento STRING  OPTIONS(description='Código de Evento — identifica el rol: 8751 ADQ, 8750 EMISOR'),
id_cliente STRING  OPTIONS(description='ID del Cliente titular de la tarjeta'),
tarjeta_sha256 STRING  OPTIONS(description='Número de Tarjeta en encripción SHA256'),
fecha_trx DATE  OPTIONS(description='Fecha de la Transacción'),
hora_trx STRING  OPTIONS(description='Hora de la Transacción'),
mto_trx FLOAT64  OPTIONS(description='Monto de la Transacción'),
cod_autorizacion STRING  OPTIONS(description='Identificación de Transacción / Número de Autorización'),
cod_respuesta STRING  OPTIONS(description='Código de Respuesta'),
resultado_reclamo STRING  OPTIONS(description='Resultado del Reclamo'),
cod_comercio STRING  OPTIONS(description='Código de Comercio (ACF)'),
tarjeta_registro750 STRING  OPTIONS(description='Tarjeta Registro 750 — PAN enmascarado'),
nom_comercio STRING  OPTIONS(description='Nombre del Comercio'),
cod_giro_comercio STRING  OPTIONS(description='MCC — Merchant Category Code (rubro del comercio)'),
bin_6 STRING  OPTIONS(description='BIN de la tarjeta (primeros 6 dígitos)'),
modo_ingreso STRING  OPTIONS(description='Entry Mode — modo de ingreso de la tarjeta'),
ucaf STRING  OPTIONS(description='UCAF — Universal Cardholder Authentication Field'),
canal_trx STRING  OPTIONS(description='Canal de la transacción'),
id_comercio STRING  OPTIONS(description='ID del Comercio en el sistema transaccional'),
disponible1 STRING  OPTIONS(description='Campo disponible para uso futuro 1'),
disponible2 STRING  OPTIONS(description='Campo disponible para uso futuro 2'),
disponible3 STRING  OPTIONS(description='Campo disponible para uso futuro 3'),
disponible4 STRING  OPTIONS(description='Campo disponible para uso futuro 4'),
disponible5 STRING  OPTIONS(description='Campo disponible para uso futuro 5'),
disponible6 STRING  OPTIONS(description='Campo disponible para uso futuro 6'),
cod_resultado STRING  OPTIONS(description='Código del Resultado de la investigación'),
detalle_investigacion STRING  OPTIONS(description='Detalle de la Investigación del Reclamo — tipo de fraude marcado'),
usuario_investigador STRING  OPTIONS(description='Usuario que investigó el Reclamo'),
cod_institucion STRING  OPTIONS(description='Código de la Institución'),
fecha_investigacion DATE  OPTIONS(description='Fecha de Investigación del Reclamo'),
hora_investigacion STRING  OPTIONS(description='Hora de Investigación del Reclamo'),
detectado_monitoreo STRING  OPTIONS(description='Detectado por Sistema de Monitoreo (0=No, 1=Sí)'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date DATETIME NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD')
)
PARTITION BY process_date
CLUSTER BY fecha_reclamo, fecha_trx, cod_comercio, bin_6
OPTIONS (description='Tabla final con los fraudes que se cargan al servidor de produccion de Monitor');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.master_risk.m_fraudes_externos_h (
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
cod_reclamo STRING  OPTIONS(description='Código de Reclamo'),
correlativo STRING  OPTIONS(description='Correlativo único del registro. Formato YYMMDD + secuencia de 4 dígitos'),
usuario_reclamo STRING  OPTIONS(description='Usuario que tomó el Reclamo'),
sucursal_reclamo STRING  OPTIONS(description='Sucursal de Reclamo'),
fecha_reclamo DATE  OPTIONS(description='Fecha del Reclamo'),
hora_reclamo STRING  OPTIONS(description='Hora del Reclamo'),
detalle_reclamo STRING  OPTIONS(description='Detalle del Reclamo — fuente del fraude (TC40, Safe, Asbanc, Contracargos)'),
medio_canal_reclamo STRING  OPTIONS(description='Medio o Canal del Reclamo'),
fuente_reclamo STRING  OPTIONS(description='Fuente del Reclamo'),
departamento_division STRING  OPTIONS(description='Departamento / División / Área'),
cod_evento STRING  OPTIONS(description='Código de Evento — identifica el rol: 8751 ADQ, 8750 EMISOR'),
id_cliente STRING  OPTIONS(description='ID del Cliente titular de la tarjeta'),
tarjeta_sha256 STRING  OPTIONS(description='Número de Tarjeta en encripción SHA256'),
fecha_trx DATE  OPTIONS(description='Fecha de la Transacción'),
hora_trx STRING  OPTIONS(description='Hora de la Transacción'),
mto_trx FLOAT64  OPTIONS(description='Monto de la Transacción'),
cod_autorizacion STRING  OPTIONS(description='Identificación de Transacción / Número de Autorización'),
cod_respuesta STRING  OPTIONS(description='Código de Respuesta'),
resultado_reclamo STRING  OPTIONS(description='Resultado del Reclamo'),
cod_comercio STRING  OPTIONS(description='Código de Comercio (ACF)'),
tarjeta_registro750 STRING  OPTIONS(description='Tarjeta Registro 750 — PAN enmascarado'),
nom_comercio STRING  OPTIONS(description='Nombre del Comercio'),
cod_giro_comercio STRING  OPTIONS(description='MCC — Merchant Category Code (rubro del comercio)'),
bin_6 STRING  OPTIONS(description='BIN de la tarjeta (primeros 6 dígitos)'),
modo_ingreso STRING  OPTIONS(description='Entry Mode — modo de ingreso de la tarjeta'),
ucaf STRING  OPTIONS(description='UCAF — Universal Cardholder Authentication Field'),
canal_trx STRING  OPTIONS(description='Canal de la transacción'),
id_comercio STRING  OPTIONS(description='ID del Comercio en el sistema transaccional'),
disponible1 STRING  OPTIONS(description='Campo disponible para uso futuro 1'),
disponible2 STRING  OPTIONS(description='Campo disponible para uso futuro 2'),
disponible3 STRING  OPTIONS(description='Campo disponible para uso futuro 3'),
disponible4 STRING  OPTIONS(description='Campo disponible para uso futuro 4'),
disponible5 STRING  OPTIONS(description='Campo disponible para uso futuro 5'),
disponible6 STRING  OPTIONS(description='Campo disponible para uso futuro 6'),
cod_resultado STRING  OPTIONS(description='Código del Resultado de la investigación'),
detalle_investigacion STRING  OPTIONS(description='Detalle de la Investigación del Reclamo — tipo de fraude marcado'),
usuario_investigador STRING  OPTIONS(description='Usuario que investigó el Reclamo'),
cod_institucion STRING  OPTIONS(description='Código de la Institución'),
fecha_investigacion DATE  OPTIONS(description='Fecha de Investigación del Reclamo'),
hora_investigacion STRING  OPTIONS(description='Hora de Investigación del Reclamo'),
detectado_monitoreo STRING  OPTIONS(description='Detectado por Sistema de Monitoreo (0=No, 1=Sí)'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date DATETIME NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD')
)
PARTITION BY process_date
CLUSTER BY fecha_reclamo, fecha_trx, cod_comercio, bin_6
OPTIONS (description='Tabla histórica final con los fraudes que se cargan al servidor de produccion de Monitor');


