CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.master_risk.m_contracargo_mastercard (
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
tipo_intercambio STRING  OPTIONS(description='Indica si es intercambio es Local (L) o Internacional (I)'),
bin STRING  OPTIONS(description='Bin de la tarjeta (primeros 9 dígitos)'),
fecha_ingreso DATE  OPTIONS(description='Fecha de ingreso del contracargo'),
cod_ica_emisor STRING  OPTIONS(description='Codigo ICA del emisor'),
cod_ica_adq STRING  OPTIONS(description='Codigo ICA del adquirente (Izipay = 007963)'),
cod_mti STRING  OPTIONS(description='MTI codigo interno'),
cod_funcion STRING  OPTIONS(description='Codigo Fun indica la etapa del contracargo'),
tarjeta_enmascarada STRING  OPTIONS(description='Tarjeta enmascarada, compuesta por los 6 primeros dígitos + 6 asteriscos + 4 últimos dígitos'),
cod_tipo_contracargo STRING  OPTIONS(description='Tipo contracargo'),
cod_moneda STRING  OPTIONS(description='Moneda del contracargo'),
mto_contracargo FLOAT64  OPTIONS(description='Importe del contracargo'),
cod_autorizacion_trx STRING  OPTIONS(description='Codigo de autorizacion de la transaccion'),
nro_referencia_acq STRING  OPTIONS(description='ARD de la transaccion'),
cod_comercio STRING  OPTIONS(description='Codigo del comercio'),
nom_comercio STRING  OPTIONS(description='Nombre del comercio'),
nro_control STRING  OPTIONS(description='Número de control del contracargo'),
cod_razon STRING  OPTIONS(description='Codigo de razon, indica el motivo del contracargo'),
cod_terminal STRING  OPTIONS(description='Codigo de terminal'),
pais_adq STRING  OPTIONS(description='País del adquirente'),
pais_emisor STRING  OPTIONS(description='País del emisor'),
mensaje STRING  OPTIONS(description='Mensaje del contracargo'),
cod_usuario_reporte STRING  OPTIONS(description='Codigo del reporte de usuario'),
situacion STRING  OPTIONS(description='Situación del contracargo'),
fecha_aceptacion DATE  OPTIONS(description='Fecha de aceptación, caso contrario 0'),
cod_gestor STRING  OPTIONS(description='Codigo MC del usuario gestor'),
obs_regularizacion STRING  OPTIONS(description='Observacion en caso de regularizaciones'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date DATETIME NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD')
)
CLUSTER BY bin, fecha_ingreso, cod_comercio, pais_emisor
OPTIONS (description='Tabla que contiene la informacion historica de contracargos provenientes de la plataforma Visa');
