CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_mccenter_caco.tmmerchant( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
cmrmerchantid STRING  OPTIONS(description= ''), 
cmrstatus STRING  OPTIONS(description= ''), 
dmrcontactname BYTES  OPTIONS(description= ''), 
dmrmerchantname STRING  OPTIONS(description= ''), 
dmraddress BYTES  OPTIONS(description= ''), 
dmrphone BYTES  OPTIONS(description= ''), 
cmrdepartcode STRING  OPTIONS(description= ''), 
cmrprovincecode STRING  OPTIONS(description= ''), 
cmrdistrictcode STRING  OPTIONS(description= ''), 
fmrcontrsigndate STRING  OPTIONS(description= ''), 
cmrtranssale STRING  OPTIONS(description= ''), 
cmrtranscash STRING  OPTIONS(description= ''), 
cmrtransgas STRING  OPTIONS(description= ''), 
cmrtransservice STRING  OPTIONS(description= ''), 
nmrfreqsettle STRING  OPTIONS(description= ''), 
cmrmcc STRING  OPTIONS(description= ''), 
cmrreqcashback STRING  OPTIONS(description= ''), 
cmrtranspreautorization STRING  OPTIONS(description= ''), 
cmrtransconfirmacion STRING  OPTIONS(description= ''), 
cmrtranssalepoints STRING  OPTIONS(description= ''), 
cmrtranspoints STRING  OPTIONS(description= ''), 
cmrtranspropina STRING  OPTIONS(description= ''), 
cmrtranspagoservice STRING  OPTIONS(description= ''), 
cmrtransanular STRING  OPTIONS(description= ''), 
cmrtransanularps STRING  OPTIONS(description= ''), 
cmrtransanularsp STRING  OPTIONS(description= ''), 
cmrtranscierre STRING  OPTIONS(description= ''), 
party_id_izi STRING  OPTIONS(description= ''), 
cmradministratorkey STRING  OPTIONS(description= ''), 
cmraccesstype STRING  OPTIONS(description= ''), 
cmrclosetype STRING  OPTIONS(description= ''), 
cmrclosetime STRING  OPTIONS(description= ''), 
cmraccesstrx STRING  OPTIONS(description= ''), 
cmrcardwriter STRING  OPTIONS(description= ''), 
cmrpropina STRING  OPTIONS(description= ''), 
cmrmoneymult STRING  OPTIONS(description= ''), 
cmrlastnumber STRING  OPTIONS(description= ''), 
cmrreqdni STRING  OPTIONS(description= ''), 
cmrprofileid STRING  OPTIONS(description= ''), 
cmrlimitamount STRING  OPTIONS(description= ''), 
cmrsaldoamount STRING  OPTIONS(description= ''), 
cmrvoidkey STRING  OPTIONS(description= ''), 
cmrsettlekey STRING  OPTIONS(description= ''), 
cmrpaymentkey STRING  OPTIONS(description= ''), 
cmrdigitkey STRING  OPTIONS(description= ''), 
cmrnetbin STRING  OPTIONS(description= ''), 
cmroperatorreq STRING  OPTIONS(description= ''), 
cmrvaloperator STRING  OPTIONS(description= ''), 
cmrlimitamountdollar STRING  OPTIONS(description= ''), 
cmrsaldoamountdollar STRING  OPTIONS(description= ''), 
cmrmodifyuser STRING  OPTIONS(description= ''), 
fmrmodifydate STRING  OPTIONS(description= ''), 
hmrmodifytime STRING  OPTIONS(description= ''), 
cmrmerchantchain STRING  OPTIONS(description= ''), 
cmrdownloadprofile STRING  OPTIONS(description= ''), 
cmrforceupdate STRING  OPTIONS(description= ''), 
cmrlogicalstatus STRING  OPTIONS(description= ''), 
cmrconfigkey STRING  OPTIONS(description= ''), 
cmrterminals STRING  OPTIONS(description= ''), 
hmrbatchclosehour STRING  OPTIONS(description= ''), 
cmrflagbatchclose STRING  OPTIONS(description= ''), 
fmrlastorderdate STRING  OPTIONS(description= ''), 
cmrtransactionkey STRING  OPTIONS(description= ''), 
dmremailaddress BYTES  OPTIONS(description= ''), 
cmrsilentalarm STRING  OPTIONS(description= ''), 
cmrtypemerchantid STRING  OPTIONS(description= ''), 
cmridfacilitador STRING  OPTIONS(description= ''), 
cmrtipoconversor STRING  OPTIONS(description= ''), 
cmrmerchantidamex STRING  OPTIONS(description= ''), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_mccenter_caco.tmterminal( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
ctrmerchantid STRING  OPTIONS(description= ''), 
ctrterminalnum STRING  OPTIONS(description= ''), 
ctrstatus STRING  OPTIONS(description= ''), 
ctrtype STRING  OPTIONS(description= ''), 
dtrterminalsn STRING  OPTIONS(description= ''), 
ntrswversion STRING  OPTIONS(description= ''), 
ctrworkingkey STRING  OPTIONS(description= ''), 
ftrgenwkdate STRING  OPTIONS(description= ''), 
dtraddress STRING  OPTIONS(description= ''), 
dtrdescription STRING  OPTIONS(description= ''), 
ctrseqnumber STRING  OPTIONS(description= ''), 
ctrtypework STRING  OPTIONS(description= ''), 
ctrmodel STRING  OPTIONS(description= ''), 
ctrconnect STRING  OPTIONS(description= ''), 
ctrmultmerchant STRING  OPTIONS(description= ''), 
ctrstatuslogin STRING  OPTIONS(description= ''), 
ctrtracenumber STRING  OPTIONS(description= ''), 
ctrlotenumber STRING  OPTIONS(description= ''), 
ctraplicacion STRING  OPTIONS(description= ''), 
ctrhfr1 STRING  OPTIONS(description= ''), 
ctrhfr2 STRING  OPTIONS(description= ''), 
ctrhfr3 STRING  OPTIONS(description= ''), 
ctrtrl1 STRING  OPTIONS(description= ''), 
ctrtrl2 STRING  OPTIONS(description= ''), 
ctrftr1 STRING  OPTIONS(description= ''), 
ctrftr2 STRING  OPTIONS(description= ''), 
ctrftr3 STRING  OPTIONS(description= ''), 
ctrcodbar STRING  OPTIONS(description= ''), 
ctrcodver STRING  OPTIONS(description= ''), 
ctrcodtarj STRING  OPTIONS(description= ''), 
ctrdobleimp STRING  OPTIONS(description= ''), 
ctrimppago STRING  OPTIONS(description= ''), 
ctrimpcuota STRING  OPTIONS(description= ''), 
ctrimpdeuda STRING  OPTIONS(description= ''), 
ctrclave STRING  OPTIONS(description= ''), 
ctrnummasterkey STRING  OPTIONS(description= ''), 
ntrnrohopper STRING  OPTIONS(description= ''), 
ctrcodmoneda1 STRING  OPTIONS(description= ''), 
ntrnromoneda1 STRING  OPTIONS(description= ''), 
ctrcodmoneda2 STRING  OPTIONS(description= ''), 
ntrnromoneda2 STRING  OPTIONS(description= ''), 
ctrcodmoneda3 STRING  OPTIONS(description= ''), 
ntrnromoneda3 STRING  OPTIONS(description= ''), 
ctrcodmoneda4 STRING  OPTIONS(description= ''), 
ntrnromoneda4 STRING  OPTIONS(description= ''), 
ctraplicaciondest STRING  OPTIONS(description= ''), 
ctrbatchnumber STRING  OPTIONS(description= ''), 
ntrlongitudtrama STRING  OPTIONS(description= ''), 
ctrmodifyuser STRING  OPTIONS(description= ''), 
ftrmodifydate STRING  OPTIONS(description= ''), 
htrmodifytime STRING  OPTIONS(description= ''), 
ftrlastechodate STRING  OPTIONS(description= ''), 
htrlastechotime STRING  OPTIONS(description= ''), 
ftrlasttrxfindate STRING  OPTIONS(description= ''), 
htrlasttrxfintime STRING  OPTIONS(description= ''), 
ftrlasttrxadmdate STRING  OPTIONS(description= ''), 
htrlasttrxadmtime STRING  OPTIONS(description= ''), 
ctrfilesversion STRING  OPTIONS(description= ''), 
ctrdownloadstate STRING  OPTIONS(description= ''), 
ntrdownloadattempts STRING  OPTIONS(description= ''), 
ftrlastdownloaddate STRING  OPTIONS(description= ''), 
htrlastdownloadtime STRING  OPTIONS(description= ''), 
ctrterminalstatus STRING  OPTIONS(description= ''), 
ctrprinterstatus STRING  OPTIONS(description= ''), 
ctrhopper1status STRING  OPTIONS(description= ''), 
ctrhopper2status STRING  OPTIONS(description= ''), 
ctrhopper3status STRING  OPTIONS(description= ''), 
ctrhopper4status STRING  OPTIONS(description= ''), 
ctrforceupdate STRING  OPTIONS(description= ''), 
ctrsaldoamount STRING  OPTIONS(description= ''), 
ctrsaldoamountdollar STRING  OPTIONS(description= ''), 
ctrmode STRING  OPTIONS(description= ''), 
ctrstatuschangereason STRING  OPTIONS(description= ''), 
ftrcreationdate STRING  OPTIONS(description= ''), 
htrcreationtime STRING  OPTIONS(description= ''), 
ctrlogicalstatus STRING  OPTIONS(description= ''), 
ctrmultmerchantid STRING  OPTIONS(description= ''), 
ctramountpaid STRING  OPTIONS(description= ''), 
ntrtxndia STRING  OPTIONS(description= ''), 
ntrtxnmes STRING  OPTIONS(description= ''), 
ntrtxnanio STRING  OPTIONS(description= ''), 
dtrmergesicode STRING  OPTIONS(description= ''), 
ntrchipnumber STRING  OPTIONS(description= ''), 
ctrpinpadsn STRING  OPTIONS(description= ''), 
dtrpinpadmodel STRING  OPTIONS(description= ''), 
ntrinventorynumber STRING  OPTIONS(description= ''), 
ctrprintersn STRING  OPTIONS(description= ''), 
ftrinventorydate STRING  OPTIONS(description= ''), 
dtrprintermodel STRING  OPTIONS(description= ''), 
ctrinventorystatus STRING  OPTIONS(description= ''), 
dtrterminalcompletesn STRING  OPTIONS(description= ''), 
dtrosversion STRING  OPTIONS(description= ''), 
ctrremovaldate STRING  OPTIONS(description= ''), 
ctrremovalnumber STRING  OPTIONS(description= ''), 
ctrinternetprotocol STRING  OPTIONS(description= ''), 
ntrnroinimoneda1 STRING  OPTIONS(description= ''), 
ntrnroinimoneda2 STRING  OPTIONS(description= ''), 
ntrnroinimoneda3 STRING  OPTIONS(description= ''), 
ntrnroinimoneda4 STRING  OPTIONS(description= ''), 
ntrnrominmoneda1 STRING  OPTIONS(description= ''), 
ntrnrominmoneda2 STRING  OPTIONS(description= ''), 
ntrnrominmoneda3 STRING  OPTIONS(description= ''), 
ntrnrominmoneda4 STRING  OPTIONS(description= ''), 
ctrcodacep1 STRING  OPTIONS(description= ''), 
ntrnroacep1 STRING  OPTIONS(description= ''), 
ctrcodacep2 STRING  OPTIONS(description= ''), 
ntrnroacep2 STRING  OPTIONS(description= ''), 
ctrcodacep3 STRING  OPTIONS(description= ''), 
ntrnroacep3 STRING  OPTIONS(description= ''), 
ctrcodacep4 STRING  OPTIONS(description= ''), 
ntrnroacep4 STRING  OPTIONS(description= ''), 
ntrnroiniacep1 STRING  OPTIONS(description= ''), 
ntrnroiniacep2 STRING  OPTIONS(description= ''), 
ntrnroiniacep3 STRING  OPTIONS(description= ''), 
ntrnroiniacep4 STRING  OPTIONS(description= ''), 
ctrcodbillete1 STRING  OPTIONS(description= ''), 
ntrnrobillete1 STRING  OPTIONS(description= ''), 
ctrcodbillete2 STRING  OPTIONS(description= ''), 
ntrnrobillete2 STRING  OPTIONS(description= ''), 
ctrcodbillete3 STRING  OPTIONS(description= ''), 
ntrnrobillete3 STRING  OPTIONS(description= ''), 
ctrcodbillete4 STRING  OPTIONS(description= ''), 
ntrnrobillete4 STRING  OPTIONS(description= ''), 
ntrnroinibillete1 STRING  OPTIONS(description= ''), 
ntrnroinibillete2 STRING  OPTIONS(description= ''), 
ntrnroinibillete3 STRING  OPTIONS(description= ''), 
ntrnroinibillete4 STRING  OPTIONS(description= ''), 
ctrsilentalarm STRING  OPTIONS(description= ''), 
ftrfechaactiv STRING  OPTIONS(description= ''), 
ftrfechadesac STRING  OPTIONS(description= ''), 
ntrdacum STRING  OPTIONS(description= ''), 
ntrdacumfact STRING  OPTIONS(description= ''), 
ctrmotivo STRING  OPTIONS(description= ''), 
ftrultcont STRING  OPTIONS(description= ''), 
ntrnroticketsimpr STRING  OPTIONS(description= ''), 
dtrimei STRING  OPTIONS(description= ''), 
dtre105sn STRING  OPTIONS(description= ''), 
dtrmodcommversion STRING  OPTIONS(description= ''), 
ctrmasterkey STRING  OPTIONS(description= ''), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_mccenter_caco.tmchipsgprs( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
simcard STRING  OPTIONS(description= ''), 
telefono BYTES  OPTIONS(description= ''), 
operador STRING  OPTIONS(description= ''), 
ftrcreationdate STRING  OPTIONS(description= ''), 
ftrdeletedate STRING  OPTIONS(description= ''), 
ctrlogicalstatus STRING  OPTIONS(description= ''), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_mccenter_caco.taterminalapplication( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
ctamerchantid STRING  OPTIONS(description= ''), 
ctaterminalnum STRING  OPTIONS(description= ''), 
ctaterminalsn STRING  OPTIONS(description= ''), 
ctaapplicationid STRING  OPTIONS(description= ''), 
ntafilesgroup STRING  OPTIONS(description= ''), 
ctafilesversion STRING  OPTIONS(description= ''), 
ctastatus STRING  OPTIONS(description= ''), 
ntaapplicationflowsize STRING  OPTIONS(description= ''), 
ctamodifyuser STRING  OPTIONS(description= ''), 
ftamodifydate STRING  OPTIONS(description= ''), 
htamodifytime STRING  OPTIONS(description= ''), 
ctareqcashback STRING  OPTIONS(description= ''), 
ctamultiproduct STRING  OPTIONS(description= ''), 
ctacardwriter STRING  OPTIONS(description= ''), 
ctaonlinetip STRING  OPTIONS(description= ''), 
ctasavemoney STRING  OPTIONS(description= ''), 
ctamultimerchantwriter STRING  OPTIONS(description= ''), 
ctaautomaticclose STRING  OPTIONS(description= ''), 
ctabatchnumber STRING  OPTIONS(description= ''), 
ftalasttrxaprodate STRING  OPTIONS(description= ''), 
htalasttrxaprotime STRING  OPTIONS(description= ''), 
ctaopenbatchnum STRING  OPTIONS(description= ''), 
ntaflagopened STRING  OPTIONS(description= ''), 
ftalastopeningdate STRING  OPTIONS(description= ''), 
htalastopeningtime STRING  OPTIONS(description= ''), 
htabatchclosehour STRING  OPTIONS(description= ''), 
ctaflagbatchclose STRING  OPTIONS(description= ''), 
ctaversionapl STRING  OPTIONS(description= ''), 
ctaversionaplpos STRING  OPTIONS(description= ''), 
ctamodelpos STRING  OPTIONS(description= ''), 
ftaupdatedate STRING  OPTIONS(description= ''), 
htaupdatetime STRING  OPTIONS(description= ''), 
dtafilesdownload STRING  OPTIONS(description= ''), 
ctatypemerchantid STRING  OPTIONS(description= ''), 
ntanumsendclosemessage STRING  OPTIONS(description= ''), 
ctabatchclosemessage STRING  OPTIONS(description= ''), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_mccenter_caco.tmdownloadprofile( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
cdpprofileid STRING  OPTIONS(description= ''), 
ddpprofilename STRING  OPTIONS(description= ''), 
ddpdescription STRING  OPTIONS(description= ''), 
cdpversioid STRING  OPTIONS(description= ''), 
hdpdownloadtime STRING  OPTIONS(description= ''), 
fdpaplicdate STRING  OPTIONS(description= ''), 
hdptolerancedwntime STRING  OPTIONS(description= ''), 
cdpmodifyuser STRING  OPTIONS(description= ''), 
fdpmodifydate STRING  OPTIONS(description= ''), 
hdpmodifytime STRING  OPTIONS(description= ''), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_mccenter_caco.tafloorlimit( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
cflmrprofileid STRING  OPTIONS(description= ''), 
cfltransactionid STRING  OPTIONS(description= ''), 
nflfloorlimit STRING  OPTIONS(description= ''), 
cflstatus STRING  OPTIONS(description= ''), 
nflfloorlimitdollar STRING  OPTIONS(description= ''), 
cflaplicacion STRING  OPTIONS(description= ''), 
cflmodifyuser STRING  OPTIONS(description= ''), 
fflmodifydate STRING  OPTIONS(description= ''), 
hflmodifytime STRING  OPTIONS(description= ''), 
cflstatusmin STRING  OPTIONS(description= ''), 
nflfloorlimmin STRING  OPTIONS(description= ''), 
nflfloorlimmindollar STRING  OPTIONS(description= ''), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_mccenter_caco.taterminalappltransaction( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
ctatmerchantid STRING  OPTIONS(description= ''), 
ctatterminalnum STRING  OPTIONS(description= ''), 
ctatterminalsn STRING  OPTIONS(description= ''), 
ctatapplicationid STRING  OPTIONS(description= ''), 
ctattransactionid STRING  OPTIONS(description= ''), 
ctattransactionstatus STRING  OPTIONS(description= ''), 
ntatfloorlimit STRING  OPTIONS(description= ''), 
ntatfloorlimitdollar STRING  OPTIONS(description= ''), 
ctatmodifyuser STRING  OPTIONS(description= ''), 
ftatmodifydate STRING  OPTIONS(description= ''), 
htatmodifytime STRING  OPTIONS(description= ''), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_mccenter_caco.tamerchantprofileapplication( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
cmamerchantprofileid STRING  OPTIONS(description= ''), 
cmaapplicationid STRING  OPTIONS(description= ''), 
cmaaccesstype STRING  OPTIONS(description= ''), 
cmaclosetype STRING  OPTIONS(description= ''), 
cmaaccesstrx STRING  OPTIONS(description= ''), 
cmacardwriter STRING  OPTIONS(description= ''), 
cmatip STRING  OPTIONS(description= ''), 
cmamultcurrency STRING  OPTIONS(description= ''), 
cmareqlastnumber STRING  OPTIONS(description= ''), 
cmareqdocid STRING  OPTIONS(description= ''), 
cmareqcashback STRING  OPTIONS(description= ''), 
cmatranstip STRING  OPTIONS(description= ''), 
nmafloorlimit STRING  OPTIONS(description= ''), 
nmarecamount STRING  OPTIONS(description= ''), 
cmamultiproduct STRING  OPTIONS(description= ''), 
cmatrxdefault STRING  OPTIONS(description= ''), 
cmamodifyuser STRING  OPTIONS(description= ''), 
fmamodifydate STRING  OPTIONS(description= ''), 
hmamodifytime STRING  OPTIONS(description= ''), 
cmareqtar STRING  OPTIONS(description= ''), 
cmatardef STRING  OPTIONS(description= ''), 
cmapinbypass STRING  OPTIONS(description= ''), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_mccenter_caco.tmversion( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
cvrversionid STRING  OPTIONS(description= ''), 
cvrapplicationid STRING  OPTIONS(description= ''), 
dvrversionnumber STRING  OPTIONS(description= ''), 
dvrdescription STRING  OPTIONS(description= ''), 
cvrmodifyuser STRING  OPTIONS(description= ''), 
fvrmodifydate STRING  OPTIONS(description= ''), 
hvrmodifytime STRING  OPTIONS(description= ''), 
dvrfile STRING  OPTIONS(description= ''), 
fvrcreationdate STRING  OPTIONS(description= ''), 
hvrcreationtime STRING  OPTIONS(description= ''), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_mccenter_caco.tatariffgroup( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
ctgtariffid STRING  OPTIONS(description= ''), 
ctggroupid STRING  OPTIONS(description= ''), 
ctgdescription STRING  OPTIONS(description= ''), 
ctgcurrency STRING  OPTIONS(description= ''), 
ctgtipo STRING  OPTIONS(description= ''), 
ctgtransactionid STRING  OPTIONS(description= ''), 
ctgapplicationid STRING  OPTIONS(description= ''), 
ctgmodifyuser STRING  OPTIONS(description= ''), 
ftgmodifydate STRING  OPTIONS(description= ''), 
htgmodifytime STRING  OPTIONS(description= ''), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_mccenter_caco.tmtariff( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
ctftariffid STRING  OPTIONS(description= ''), 
ftfaplicdate STRING  OPTIONS(description= ''), 
ctfapplicationid STRING  OPTIONS(description= ''), 
ctfcurrency STRING  OPTIONS(description= ''), 
ctfdescription1 STRING  OPTIONS(description= ''), 
ntfamount1 STRING  OPTIONS(description= ''), 
ctfdescription2 STRING  OPTIONS(description= ''), 
ntfamount2 STRING  OPTIONS(description= ''), 
ctfdescription3 STRING  OPTIONS(description= ''), 
ntfamount3 STRING  OPTIONS(description= ''), 
ctfdescription4 STRING  OPTIONS(description= ''), 
ntfamount4 STRING  OPTIONS(description= ''), 
ntfdeniedamount STRING  OPTIONS(description= ''), 
ctfmodifyuser STRING  OPTIONS(description= ''), 
ftfmodifydate STRING  OPTIONS(description= ''), 
htfmodifytime STRING  OPTIONS(description= ''), 
ntfdesinsamount STRING  OPTIONS(description= ''), 
ntfpedeinsamount STRING  OPTIONS(description= ''), 
ntfinstmintime STRING  OPTIONS(description= ''), 
ntfccgprsamount STRING  OPTIONS(description= ''), 
ntfinsamount STRING  OPTIONS(description= ''), 
ntfcostotransaccion STRING  OPTIONS(description= ''), 
ntfcostoafiliacion STRING  OPTIONS(description= ''), 
ntfcostominimo STRING  OPTIONS(description= ''), 
ntfcostomaximo STRING  OPTIONS(description= ''), 
ntfcantidadpos STRING  OPTIONS(description= ''), 
ntcostoterminalstatus STRING  OPTIONS(description= ''), 
ctrincluirdeshab STRING  OPTIONS(description= ''), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_mccenter_caco.tmtransactiontype( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
ctttransactionid STRING  OPTIONS(description= ''), 
cttaplicacion STRING  OPTIONS(description= ''), 
dtttransactionname STRING  OPTIONS(description= ''), 
ctttransgroup STRING  OPTIONS(description= ''), 
cttmerchantval STRING  OPTIONS(description= ''), 
cttterminalval STRING  OPTIONS(description= ''), 
cttfloorlimitval STRING  OPTIONS(description= ''), 
cttactivitylimitval STRING  OPTIONS(description= ''), 
cttmerchantbalanceval STRING  OPTIONS(description= ''), 
cttsavelog STRING  OPTIONS(description= ''), 
ctttranstype STRING  OPTIONS(description= ''), 
ctttransroute STRING  OPTIONS(description= ''), 
cttrequiredfieldsreq STRING  OPTIONS(description= ''), 
cttrequiredfieldsresp STRING  OPTIONS(description= ''), 
cttconvertertype STRING  OPTIONS(description= ''), 
cttmodifyuser STRING  OPTIONS(description= ''), 
fttmodifydate STRING  OPTIONS(description= ''), 
httmodifytime STRING  OPTIONS(description= ''), 
cttwithoutcost STRING  OPTIONS(description= ''), 
cttarchivo STRING  OPTIONS(description= ''), 
dttdescription STRING  OPTIONS(description= ''), 
cttfloorlimitvalmin STRING  OPTIONS(description= ''), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_mccenter_caco.txlistfield( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
dlffieldname STRING  OPTIONS(description= ''), 
clfcode STRING  OPTIONS(description= ''), 
clfrelativecode STRING  OPTIONS(description= ''), 
dlfdescription STRING  OPTIONS(description= ''), 
clfmodifyuser STRING  OPTIONS(description= ''), 
flfmodifydate STRING  OPTIONS(description= ''), 
hlfmodifytime STRING  OPTIONS(description= ''), 
dlfaditionaldescription STRING  OPTIONS(description= ''), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='');

