/****** Object:  StoredProcedure [DWH].[usp_GeneraBI_Maestro_Terminales]    Script Date: 5/29/2025 4:42:53 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [DWH].[usp_GeneraBI_Maestro_Terminales] AS
BEGIN

/*============================================================================================= 
Autor					:Business Analytics SAC
Fecha creación			:2021/04/12
Objetivos				:Insertar la data de la tabla [Stage].[StgMaestroTerminales] a la tabla [DWH].[BI_Maestro_Terminales]
Ejecutar				:EXECUTE [DWH].[usp_GeneraBI_Maestro_Terminales]
Observaciones			:
===============================================================================================*/ 
/*====================================== PROCESO 0 ============================================ 
							Definición de variables temporales 
===============================================================================================*/ 
DECLARE @fecIniLog DATETIME;
SET @fecIniLog			= DATEADD(HOUR,-5,GETDATE());
/*====================================== PROCESO 1 ============================================ 
					Inserta datos en la tabla [DWH].[BI_Maestro_Terminales]
===============================================================================================*/ 

TRUNCATE TABLE [DWH].[BI_Maestro_Terminales];

INSERT INTO [DWH].[BI_Maestro_Terminales]
(
[COMERCIO],
[ADQ_C_COR],
[NOMBRE],
[RUBRO],
[SITUACION],
[CATEGORIA],
[RAZON_SOCIAL],
[RUC],
[DIRECCION],
[DEPARTAMENTO],
[PROVINCIA],
[DISTRITO],
[MULTICOMERCIO],
[TELEFONO_COMERCIO],
[CONTACTO],
[PERFIL_COMERCIO],
[PERFIL_DESCARGA],
[TERMINAL],
[SERIE],
[MEDIO_MCC],
[MEDIO],
[DESCRIPCION_TERMINAL],
[FECHA_ULTIMO_ECO],
[FECHA_ULTIMA_TRANSACCION_FINANCIERA],
[FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA],
[SITUACION_TERMINAL],
[MODELO],
[MODELO_MCC],
[VERSION_SWB],
[OS_VERSION],
[CHIP],
[TELEFONO_CHIP],
[OPERADOR],
[ESTADO_COMERCIO],
[ESTADO_LOGICO_COMERCIO],
[ESTADO_TERMINAL],
[ESTADO_LOGICO_TERMINAL],
[APLICACION],
[APL_DESC],
[FACTURACION],
[DTRE105SN],
[VERSION_FLUJO],
[VERSION_MAIN],
[SERIE_COMPLETA],
[MARCA],
[FLG_PCI],
[SW_CTLS],
[HW_CTLS],
[PRE_AUTORIZACION_NIVEL_COMERCIO],
[PRE_AUTORIZACION_NIVEL_TERMINAL],
[DIGITACION_MANUAL_NIVEL_COMERCIO],
[DIGITACION_MANUAL_NIVEL_TERMINAL],
[PROPINA],
[FECHA_ACTUALIZACION_APP],
[HORA_ACTUALIZACION_APP],
[NUM_INTENTOS],
[FECHA_ULTIMA_ACTUALIZACION],
[HORA_ULTIMA_ACTUALIZACION],
[VERSION_ACTUALIZADO],
[CTAFILESVERSION],
[CVRVERSIONID],
[CTAVERSIONAPL],
[DVRFILE],
[MARGUESI],
[FEC_COMPRA],
[SITUACION_AS400],
[EMV_DINERS],
[CANT_TERM],
[CANT_TERM_ACT],
[FLG_PINPAD],
[FLG_INGENICO],
[FLG_MULT_APP],
[FLG_MULTICOMERCIO],
[FLG_TELECARGA],
[GIRO],
[GIRO_MC],
[SERIE_UNICA],
[RAZON_SOCIAL2],
[GRUPO_ECONÓMICO],
[UNIDAD_DE_NEGOCIO],
[FECAPE],
[QR_CRC],
[QR_CRC_PENDIENTE],
[CV_LIMIT_150],
[COSECHA],
[OFICINA],
[MODELO_TERMINAL],
[VERSION_BASE],
[VERSION_ENVIADA],
FEC_INST,
FLAG_COD_INTERNOS
)
SELECT 
A.[COMERCIO],
[ADQ_C_COR],
A.[NOMBRE],
[RUBRO],
[SITUACION],
[CATEGORIA],
[RAZON_SOCIAL],
[RUC],
[DIRECCION],
[DEPARTAMENTO],
[PROVINCIA],
[DISTRITO],
[MULTICOMERCIO],
[TELEFONO_COMERCIO],
[CONTACTO],
[PERFIL_COMERCIO],
[PERFIL_DESCARGA],
[TERMINAL],
[SERIE],
[MEDIO_MCC],
[MEDIO],
[DESCRIPCION_TERMINAL],
[FECHA_ULTIMO_ECO],
[FECHA_ULTIMA_TRANSACCION_FINANCIERA],
[FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA],
[SITUACION_TERMINAL],
[MODELO],
[MODELO_MCC],
[VERSION_SWB],
[OS_VERSION],
[CHIP],
[TELEFONO_CHIP],
[OPERADOR],
[ESTADO_COMERCIO],
[ESTADO_LOGICO_COMERCIO],
[ESTADO_TERMINAL],
[ESTADO_LOGICO_TERMINAL],
[APLICACION],
[APL_DESC],
[FACTURACION],
[dTrE105SN],
[VERSION_FLUJO],
[VERSION_MAIN],
[SERIE_COMPLETA],
[MARCA],
[FLG_PCI],
[SW_CTLS],
[HW_CTLS],
[PRE_AUTORIZACION_NIVEL_COMERCIO],
[PRE_AUTORIZACION_NIVEL_TERMINAL],
[DIGITACION_MANUAL_NIVEL_COMERCIO],
[DIGITACION_MANUAL_NIVEL_TERMINAL],
[PROPINA],
[FECHA_ACTUALIZACION_APP],
[HORA_ACTUALIZACION_APP],
[NUM_INTENTOS],
[FECHA_ULTIMA_ACTUALIZACION],
[HORA_ULTIMA_ACTUALIZACION],
[VERSION_ACTUALIZADO],
[cTAFilesVersion],
[cVrVersionId],
[cTAVersionApl],
[dVrFile],
[MARGUESI],
[FEC_COMPRA],
[SITUACION_AS400],
[EMV_DINERS],
[CANT_TERM],
[CANT_TERM_ACT],
[FLG_PINPAD],
[FLG_INGENICO],
[FLG_MULT_APP],
[FLG_MULTICOMERCIO],
[FLG_TELECARGA],
[GIRO],
[GIRO_MC],
[SERIE_UNICA],
[Razón Social],
[Grupo Económico],
[Unidad de Negocio],
[fecape],
[QR_CRC],
[QR_CRC_Pendiente],
[CV_LIMIT_150],
[COSECHA],
[Oficina],
[Modelo_Terminal],
[Version_Base],
[Version_Enviada],
FEC_INST,
CASE WHEN B.COMERCIO IS NULL THEN 1 ELSE 0 END FlagCodigosInternos

FROM [Stage].[StgMaestroTerminales] A
LEFT JOIN RAW.Cod_Internos_RP B ON B.COMERCIO=A.[COMERCIO];

INSERT INTO Stage.stglog (Fuente,Tabla,Cantidad,FechaINicio,FechaFIN)
SELECT 'Carga BI_Maestro_Terminales - Paso 8/8','BI_Maestro_Terminales',(SELECT COUNT(*) FROM DWH.BI_Maestro_Terminales),@fecIniLog,DATEADD(HOUR,5,GETDATE());

END