/****** Object:  StoredProcedure [Stage].[usp_GeneraStgMaestroTerminales_RedPOS]    Script Date: 5/29/2025 4:45:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [Stage].[usp_GeneraStgMaestroTerminales_RedPOS] AS
BEGIN
/*======================================================================================= 
	Autor			:TR9656
	Fecha creación	:2023/10/19
	Objetivos		:Generar la tabla terminales
	Ejecutar		:EXECUTE  [Stage].[usp_GeneraStgMaestroTerminales_RedPOS]  
=======================================================================================*/ 
/*
Input Tables:
[DWH].[BI_Mcestab]			: 5:30 AM
[Stage].[StgTerminalA]		: 7:45 AM
[Stage].[StgTerminalCc]		: 7:45 AM
[RAW].[MCFV030E]			: 2:00 AM
[RAW].[AKFMITEM]			: 2:30 AM
[RAW].[MCFM019i]			: 3:00 AM
*/
/*====================================== PROCESO 0 ====================================== 
	Definición de variables temporales 
========================================================================================*/ 
DECLARE @FECHA CHAR(8)
SET @FECHA = (SELECT MAX([FECHA_ULTIMA_TRANSACCION_FINANCIERA]) FROM [Stage].[StgTerminalA])

/*====================================== PROCESO 1 ======================================= 
	Limpieza y Generación de la tabla temporal de #TEMP_COMERCIO_A
=========================================================================================*/ 
IF OBJECT_ID('TempDB..#TEMP_COMERCIO_A') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMP_COMERCIO_A;
	DROP TABLE #TEMP_COMERCIO_A;
END;

SELECT [COMERCIO]
	,COUNT(DISTINCT SERIE) 'CANT_TERM'
	,COUNT(DISTINCT CASE 
						WHEN datediff(month,cast([FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime)) <= 3 THEN SERIE
						ELSE NULL
					END) 'CANT_TERM_ACT'
	,COUNT(DISTINCT CASE 
						WHEN datediff(month,cast([FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime)) <= 3 AND
							MODELO IN ('P400','VX820_CHIPAMEX','VX810_8012_PCI','VX810_8012_CHIPAMEX','MX915','VX810_8012','VX810','VX820','VX820_PCI','MX925') THEN SERIE
						ELSE NULL
					END)'CANT_PINPAD'
INTO #TEMP_COMERCIO_A
FROM [Stage].[StgTerminalA]
GROUP BY [COMERCIO];
-- 717,845 filas
-- 00:05 sec

/*====================================== PROCESO 2 ======================================= 
	Limpieza y Generación de la tabla temporal de #TEMP_COMERCIO_CC
=========================================================================================*/ 
IF OBJECT_ID('TempDB..#TEMP_COMERCIO_CC') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMP_COMERCIO_CC;
	DROP TABLE #TEMP_COMERCIO_CC;
END;

SELECT [COMERCIO]
	,COUNT(DISTINCT SERIE) 'CANT_TERM'
	,COUNT(DISTINCT CASE 
						WHEN datediff(month,cast([FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime)) <= 3 THEN SERIE
						ELSE NULL
					END) 'CANT_TERM_ACT'
	,COUNT(DISTINCT CASE 
						WHEN datediff(month,cast([FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime)) <= 3 AND
							MODELO IN ('P400','VX820_CHIPAMEX','VX810_8012_PCI','VX810_8012_CHIPAMEX','MX915','VX810_8012','VX810','VX820','VX820_PCI','MX925') THEN SERIE
						ELSE NULL
					END)'CANT_PINPAD'
INTO #TEMP_COMERCIO_CC
FROM [Stage].[StgTerminalCc]
GROUP BY [COMERCIO];
-- 41,356 filas
-- 00:04 sec

/*====================================== PROCESO 3 ======================================= 
	Tabla temporal auxiliar #TEMP_MODELO para completar modelo de terminales
=========================================================================================*/ 
IF OBJECT_ID('TempDB..#TEMP_MODELO') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMP_MODELO;
	DROP TABLE #TEMP_MODELO;
END;

CREATE TABLE #TEMP_MODELO (Modelo_MCC VARCHAR(50),Modelo_Terminal VARCHAR(50),Marca VARCHAR(50),PCI VARCHAR(50),CTLS VARCHAR(50),Modelo_Corto VARCHAR(50),Medio VARCHAR(50));

INSERT INTO #TEMP_MODELO VALUES ('ICT220', 'Ingenico - ICT220', 'Ingenico ','NO PCI','NO SW CTLS','ICT220',null);
INSERT INTO #TEMP_MODELO VALUES ('ICT250', 'Ingenico - ICT220', 'Ingenico ','NO PCI','NO SW CTLS','ICT250',null);
INSERT INTO #TEMP_MODELO VALUES ('IWL250', 'Ingenico - IWL250', 'Ingenico ','NO PCI','NO SW CTLS','IWL250','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('OMNI3750', 'Verifone - Omni3750', 'Verifone ','PRE PCI','NO SW CTLS','OMNI3750',null);
INSERT INTO #TEMP_MODELO VALUES ('VX520', 'Verifone - VX520', 'Verifone ','NO PCI','NO SW CTLS','VX520',null);
INSERT INTO #TEMP_MODELO VALUES ('VX520_CHIPAMEX', 'Verifone - VX520', 'Verifone ','NO PCI','NO SW CTLS','VX520',null);
INSERT INTO #TEMP_MODELO VALUES ('VX520_DIAL', 'Verifone - VX520', 'Verifone ','NO PCI','NO SW CTLS','VX520',null);
INSERT INTO #TEMP_MODELO VALUES ('VX520_PREAMP', 'Verifone - VX520', 'Verifone ','NO PCI','NO SW CTLS','VX520',null);
INSERT INTO #TEMP_MODELO VALUES ('VX520_SBP', 'Verifone - VX520', 'Verifone ','NO PCI','NO SW CTLS','VX520',null);
INSERT INTO #TEMP_MODELO VALUES ('VX520_SP', 'Verifone - VX520', 'Verifone ','NO PCI','NO SW CTLS','VX520',null);
INSERT INTO #TEMP_MODELO VALUES ('VX520_SP_CHIPAMEX', 'Verifone - VX520', 'Verifone ','NO PCI','NO SW CTLS','VX520',null);
INSERT INTO #TEMP_MODELO VALUES ('VX680', 'Verifone - VX680', 'Verifone ','NO PCI','NO SW CTLS','VX680','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('VX680_CHIPAMEX', 'Verifone - VX680', 'Verifone ','NO PCI','NO SW CTLS','VX680','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('VX680_SP', 'Verifone - VX680', 'Verifone ','NO PCI','NO SW CTLS','VX680','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('VX680_SP_CHIPAMEX', 'Verifone - VX680', 'Verifone ','NO PCI','NO SW CTLS','VX680','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('VX820', 'Verifone - VX820', 'Verifone ','NO PCI','NO SW CTLS','VX820','PINPAD');
INSERT INTO #TEMP_MODELO VALUES ('VX820_CHIPAMEX', 'Verifone - VX820', 'Verifone ','NO PCI','NO SW CTLS','VX820','PINPAD');
INSERT INTO #TEMP_MODELO VALUES ('VX510', 'Verifone - VX510', 'Verifone ','PRE PCI','NO HW CTLS','VX510',null);
INSERT INTO #TEMP_MODELO VALUES ('VX510_CHIPAMEX', 'Verifone - VX510', 'Verifone ','PRE PCI','NO HW CTLS','VX510',null);
INSERT INTO #TEMP_MODELO VALUES ('VX510_DIAL', 'Verifone - VX510', 'Verifone ','PRE PCI','NO HW CTLS','VX510',null);
INSERT INTO #TEMP_MODELO VALUES ('VX510_PCI', 'Verifone - VX510', 'Verifone ','PRE PCI','NO HW CTLS','VX510',null);
INSERT INTO #TEMP_MODELO VALUES ('VX510_PREAMP', 'Verifone - VX510', 'Verifone ','PRE PCI','NO HW CTLS','VX510',null);
INSERT INTO #TEMP_MODELO VALUES ('VX510_SBP', 'Verifone - VX510', 'Verifone ','PRE PCI','NO HW CTLS','VX510',null);
INSERT INTO #TEMP_MODELO VALUES ('VX510_SP', 'Verifone - VX510', 'Verifone ','PRE PCI','NO HW CTLS','VX510',null);
INSERT INTO #TEMP_MODELO VALUES ('VX510_SP_CHIPAMEX', 'Verifone - VX510', 'Verifone ','PRE PCI','NO HW CTLS','VX510',null);
INSERT INTO #TEMP_MODELO VALUES ('VX610', 'Verifone - VX610', 'Verifone ','PRE PCI','NO HW CTLS','VX610',null);
INSERT INTO #TEMP_MODELO VALUES ('VX610_CHIPAMEX', 'Verifone - VX610', 'Verifone ','PRE PCI','NO HW CTLS','VX610',null);
INSERT INTO #TEMP_MODELO VALUES ('VX610_PCI', 'Verifone - VX610', 'Verifone ','PRE PCI','NO HW CTLS','VX610',null);
INSERT INTO #TEMP_MODELO VALUES ('VX610_SBP', 'Verifone - VX610', 'Verifone ','PRE PCI','NO HW CTLS','VX610',null);
INSERT INTO #TEMP_MODELO VALUES ('VX610_SP', 'Verifone - VX610', 'Verifone ','PRE PCI','NO HW CTLS','VX610',null);
INSERT INTO #TEMP_MODELO VALUES ('VX670', 'Verifone - VX670', 'Verifone ','PRE PCI','NO HW CTLS','VX670',null);
INSERT INTO #TEMP_MODELO VALUES ('VX810', 'Verifone - VX810', 'Verifone ','PRE PCI','NO HW CTLS','VX810','PINPAD');
INSERT INTO #TEMP_MODELO VALUES ('VX810_8012', 'Verifone - VX810	', 'Verifone ','PRE PCI','NO HW CTLS','VX810','PINPAD');
INSERT INTO #TEMP_MODELO VALUES ('VX810_8012_CHIPAMEX', 'Verifone - VX810', 'Verifone ','PRE PCI','NO HW CTLS','VX810','PINPAD');
INSERT INTO #TEMP_MODELO VALUES ('VX810_8012_PCI', 'Verifone - VX810', 'Verifone ','PRE PCI','NO HW CTLS','VX810','PINPAD');
INSERT INTO #TEMP_MODELO VALUES ('C680', 'Verifone - C680', 'Verifone ',null,null,'C680','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('ClienteIPH', 'DSPREAD - QPOS Mini', 'DSPREAD ',null,null,'Cliente','mPOS');
INSERT INTO #TEMP_MODELO VALUES ('D200', 'Pax - D200', 'Pax ',null,null,'D200','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('DX8000', 'Ingenico - DX8000', 'Ingenico ',null,null,'DX8000','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('ICT220_PCI', 'Ingenico - ICT220', 'Ingenico ',null,null,'ICT220',null);
INSERT INTO #TEMP_MODELO VALUES ('ICT250_PCI', 'Ingenico - ICT220', 'Ingenico ',null,null,'ICT220',null);
INSERT INTO #TEMP_MODELO VALUES ('IWL220_PCI', 'Ingenico - IWL220', 'Ingenico ',null,null,'IWL220','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('IWL250_PCI', 'Ingenico - IWL250', 'Ingenico ',null,null,'IWL250','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('LINK2500', 'Ingenico - Link2500', 'Ingenico ',null,null,'LINK2500','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('MOVE5000', 'Ingenico - Move5000', 'Ingenico ',null,null,'MOVE5000','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('MX915', 'Verifone - Mx915', 'Verifone ',null,null,'MX915','PINPAD');
INSERT INTO #TEMP_MODELO VALUES ('MX925', 'Verifone - Mx925', 'Verifone ',null,null,'MX925','PINPAD');
INSERT INTO #TEMP_MODELO VALUES ('P2MINI', 'Sunmi - P2MINI', 'Sunmi ',null,null,'P2MINI','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('P2SE', 'Sunmi - P2SE', 'Sunmi ',null,null,'P2SE','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('P400', 'Verifone - P400', 'Verifone ',null,null,'P400','PINPAD');
INSERT INTO #TEMP_MODELO VALUES ('V240M', 'Verifone - V240M', 'Verifone ',null,null,'V240M','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('VX520_PCI', 'Verifone - VX520', 'Verifone ',null,null,'VX520',null);
INSERT INTO #TEMP_MODELO VALUES ('VX520C', 'Verifone - VX520C', 'Verifone ',null,null,'VX520C','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('VX680_PCI', 'Verifone - VX680', 'Verifone ',null,null,'VX680','GPRS Movil');
INSERT INTO #TEMP_MODELO VALUES ('VX820_PCI', 'Verifone - VX820', 'Verifone ',null,null,'VX820','PINPAD');
INSERT INTO #TEMP_MODELO VALUES ('ClienteAD', 'DSPREAD - QPOS Mini', 'DSPREAD ',null,null,'Cliente','mPOS');
-- 56 filas
-- 00:04 sec

/*===================================== PROCESO 4 ====================================== 
	Tabla temporal auxiliar #DataTerminalesAS del AS400
=========================================================================================*/ 
IF OBJECT_ID('TempDB..#DataTerminalesAS') IS NOT NULL
BEGIN
	TRUNCATE TABLE #DataTerminalesAS;
	DROP TABLE #DataTerminalesAS;
END;

SELECT *
INTO #DataTerminalesAS
FROM [DWH].[DataTerminalesAS]
WHERE MARCA IN ('DS1READ','DSPREAD','INGENICO','PAX','SUNMI','VERIFON','VERIFONE','SUMNI','WISEPAD')
AND MODELO NOT IN ('IMPRESORA','OMNI 3600','EI/T1 M','OMNI 3750','MIPB-1307','INFO7000','VX 810','TRANZ 340','VX810'
					,'TRANZIT 12','1000','GENISYS','1000SE-PC','5100','OMNI VX610','BASE VX670','VX510 D/L','VX 610'
					,'5100 - II','MNG BLADE','NS010','SOVE 5000','ULC004','SC 552','OMNI 395 D','DLC004','1000 SE'
					,'NS020','IMP.250','EI/T1 F+M','SC 5000','TCP/IP','OMNI VX510','VX510 DIAL','NCC-14','VX610 GPRS'
					,'VX670','TRCV 500','EFT5400','VX510 GPRS','VX670 GPRS')
AND MARGUESI NOT IN ('00000000000006418990','00000000000002832491','00000000000002832632','00000000000004713913'
	,'00000000000002898534','00000000000002899979','00000000000003229275','00000000000001672690','00000000000001674795'
	,'00000000000001674829','00000000000001677830','00000000000001678333','00000000000001680784','00000000000001684984'
	,'00000000000001685106','00000000000001685478','00000000000001686831','00000000000002893139','00000000000002893170'
	,'00000000000002893337','00000000000002893410','00000000000002893493','00000000000002893519','00000000000002893600'
	,'00000000000002893659','00000000000002893675','00000000000002893758','00000000000002893808','00000000000002893865'
	,'00000000000002893873','00000000000002893964','00000000000002894368','00000000000002894426','00000000000002894467'
	,'00000000000002894590','00000000000002894699','00000000000002894921','00000000000002895134','00000000000002895159'
	,'00000000000002895258','00000000000002895290','00000000000002895472','00000000000002895480','00000000000002895605'
	,'00000000000002895662','00000000000002895753','00000000000002895886','00000000000002896041','00000000000002896066'
	,'00000000000002896330','00000000000002896363','00000000000002896413','00000000000002896546','00000000000002896645'
	,'00000000000002896959','00000000000002897056','00000000000002897148','00000000000002897262','00000000000002897437'
	,'00000000000002897692','00000000000002897841','00000000000002898211','00000000000002898310','00000000000002898328'
	,'00000000000002898369','00000000000002898468','00000000000002898484','00000000000002898492','00000000000002898658'
	,'00000000000002899052','00000000000002899532','00000000000002899920','00000000000002899987','00000000000003168267'
	,'00000000000003169067','00000000000003177482','00000000000003207891','00000000000003208626','00000000000003220712'
	,'00000000000003221256','00000000000003222957','00000000000003223203','00000000000003224268','00000000000003228459'
	,'00000000000003230364','00000000000003231610','00000000000003234374','00000000000003234929','00000000000003715687'
	,'00000000000003978848','00000000000004057923','00000000000004090676','00000000000004100541','00000000000005110457'
	,'00000000000005740964','00000000000006825533','00000000000006827091','00000000000006915474','00000000000003027992'
	,'00000000000009704677') -- PARCHE SERIE DUPLICADA EN EL ACTIVO FIJO / V810 / SERIES MAL ASIGNADAS
AND ((MARCA IN ('VERIFON','VERIFONE')	AND LEFT(RTRIM(LTRIM(SERIE)),1)<>'F')
		OR (LEFT(RTRIM(LTRIM(MODELO)),4) ='MOVE' AND LEFT(RTRIM(LTRIM(SERIE)),1) NOT IN ('V','F'))
		OR (MARCA NOT IN ('VERIFON','VERIFONE') AND LEFT(RTRIM(LTRIM(MODELO)),4) <>'MOVE' AND  ESTADO<>'B')
		OR RTRIM(LTRIM(MODELO)) IN ('ICT220-EM','IWL250','ICT220 EMC','IWL250 3G','ICT220 EM','IWL220 3G','ICT220GEMC'))
AND CODCOMERCIO<>'7010427'
AND MODELO <> ''
-- 992,132 filas
-- 00:09 sec

/*===================================== PROCESO 5.1 ====================================== 
	Tabla para completar las series completas por serie unica
=========================================================================================*/ 
IF OBJECT_ID('TempDB..#TEMP_SERIES_U8') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMP_SERIES_U8;
	DROP TABLE #TEMP_SERIES_U8;
END;

SELECT 
	MAX([Serie]) 'Serie',
	RIGHT(REPLACE(REPLACE([Serie],' ',''),'-',''),8) 'Serie_corta',
	COUNT(1) CANT 
INTO #TEMP_SERIES_U8
FROM #DataTerminalesAS
WHERE MARCA IN ('INGENICO','PAX','SUNMI','VERIFON','VERIFONE','SUMNI')
GROUP BY RIGHT(REPLACE(REPLACE([Serie],' ',''),'-',''),8)
HAVING COUNT(1)=1

IF OBJECT_ID('TempDB..#TEMP_SERIES_U9') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMP_SERIES_U9;
	DROP TABLE #TEMP_SERIES_U9;
END;

SELECT 
	MAX([Serie]) 'Serie',
	RIGHT(REPLACE(REPLACE([Serie],' ',''),'-',''),9) 'Serie_corta',
	COUNT(1) CANT 
INTO #TEMP_SERIES_U9
FROM #DataTerminalesAS
WHERE MARCA IN ('DS1READ','DSPREAD','WISEPAD')
GROUP BY RIGHT(REPLACE(REPLACE([Serie],' ',''),'-',''),9)
HAVING COUNT(1)=1
-- 802,108 / 165,468 filas
-- 00:06 sec

/*===================================== PROCESO 5.2 ====================================== 
	Tabla situacion de codigo de comercio
=========================================================================================*/ 
IF OBJECT_ID('TempDB..#SITUACION') IS NOT NULL
BEGIN
	TRUNCATE TABLE #SITUACION;
	DROP TABLE #SITUACION;
END;

CREATE TABLE #SITUACION (Situac VARCHAR(1),Situac_Desc VARCHAR(25));

INSERT INTO #SITUACION VALUES ('1', '1.C/mov ult 3 meses');
INSERT INTO #SITUACION VALUES ('2', '2.S/mov mas 12 meses');
INSERT INTO #SITUACION VALUES ('3', '3.Bloqueo definitivo');
INSERT INTO #SITUACION VALUES ('4', '4.S/mov mas 3 meses');
INSERT INTO #SITUACION VALUES ('5', '5.Nuevo s/mov');
INSERT INTO #SITUACION VALUES ('6', '6.S/mov mas 6 meses');
INSERT INTO #SITUACION VALUES ('7', '7.Nuevo');
INSERT INTO #SITUACION VALUES ('8', '8.Nuevo s/mov mas 3 meses');
INSERT INTO #SITUACION VALUES ('9', '9.Bloqueo temporal');
-- 9 filas
-- 00:01 sec

/*===================================== PROCESO 6.1 ====================================== 
	Generamos la tabla temporal #MAESTRO_TERMINALES para ADQUIRIENTE
=========================================================================================*/ 
IF OBJECT_ID('TempDB..#MAESTRO_TERMINALES') IS NOT NULL
BEGIN
	TRUNCATE TABLE #MAESTRO_TERMINALES;
	DROP TABLE #MAESTRO_TERMINALES;
END;

SELECT DISTINCT
	RTRIM(LTRIM(A.[COMERCIO])) 'COMERCIO',
	CASE
		WHEN B.[Pay_faci_id]='IZI*IZIPAY' THEN 'ADQ-IZIPAY'
		WHEN B.[Pay_faci_id] IS NULL THEN 'ADQ-PMP'
		ELSE B.[Pay_faci_id]
	END 'ADQ/C.COR',
	RTRIM(LTRIM(A.[NOMBRE])) 'NOMBRE',
	ISNULL(RTRIM(LTRIM(B.[Mcc])), RTRIM(LTRIM(A.[RUBRO]))) 'RUBRO',
	G.Situac_Desc 'SITUACION',
	CASE B.[Cta_esp]
		WHEN 'N' THEN '3. NEGOCIOS'
		WHEN 'E' THEN '2. EMPRESAS'
		WHEN 'G' THEN '1. GRANDES EMPRESAS'
		WHEN 'C' THEN '0. CORPORACIONES'
	END 'CATEGORIA',
	RTRIM(LTRIM(B.[Razsoc])) 'RAZON_SOCIAL',
	ISNULL(RTRIM(LTRIM(B.[Nroruc])),RTRIM(LTRIM(A.[RUC]))) 'RUC',
	RTRIM(LTRIM(A.[DIRECCION])) 'DIRECCION',
	RTRIM(LTRIM(A.[DEPARTAMENTO])) 'DEPARTAMENTO',
	RTRIM(LTRIM(A.[PROVINCIA])) 'PROVINCIA',
	RTRIM(LTRIM(A.[DISTRITO])) 'DISTRITO',
	RTRIM(LTRIM(A.[MULTICOMERCIO])) 'MULTICOMERCIO',
	RTRIM(LTRIM(A.[TELEFONO_COMERCIO])) 'TELEFONO_COMERCIO',
	RTRIM(LTRIM(A.[CONTACTO])) 'CONTACTO',
	RTRIM(LTRIM(A.[PERFIL_COMERCIO])) 'PERFIL_COMERCIO',
	RTRIM(LTRIM(A.[PERFIL_DESCARGA])) 'PERFIL_DESCARGA',
	RTRIM(LTRIM(A.[TERMINAL])) 'TERMINAL',
	RTRIM(LTRIM(A.[SERIE])) 'SERIE',
	RTRIM(LTRIM(A.[MEDIO])) 'MEDIO_MCC',
	ISNULL(RTRIM(LTRIM(F.medio)),
	CASE
		WHEN RTRIM(LTRIM(A.[CHIP])) <> '' THEN 'GPRS Fijo'
		WHEN RTRIM(LTRIM(A.[MEDIO])) = 'ETHERNET' THEN 'IP'
		WHEN RTRIM(LTRIM(A.[MEDIO])) = 'DIAL' THEN 'DIAL'
		ELSE  'IP'
	END ) 'MEDIO',
	RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) 'DESCRIPCION_TERMINAL',
	RTRIM(LTRIM(A.[FECHA_ULTIMO_ECO])) 'FECHA_ULTIMO_ECO',
	RTRIM(LTRIM(A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA])) 'FECHA_ULTIMA_TRANSACCION_FINANCIERA',
	RTRIM(LTRIM(A.[FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA])) 'FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA',
	-- CALCULO SITUACION DE TERMINAL --
	CASE
		WHEN A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA] IS NULL THEN '99 - Sin registro de trx.'
		WHEN datediff(month,cast(A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>12 THEN '2 - Sin movimiento ultimos 12 meses.'
		WHEN datediff(month,cast(A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>6 THEN '6 - Sin movimiento ultimos 6 meses.'
		WHEN datediff(month,cast(A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>3 THEN '4 - Sin movimiento ultimos 3 meses.'
		WHEN datediff(month,cast(A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>=0 THEN '1 - Con movimiento en los ultimos 3 meses.'
		ELSE '2 - Sin movimiento ultimos 12 meses.'
	END 'SITUACION_TERMINAL',
	RTRIM(LTRIM(C.MODELO)) 'MODELO', -- MODELO AS400
    RTRIM(LTRIM(A.[MODELO])) 'MODELO_MCC',
	RTRIM(LTRIM(A.[VERSION_SWB])) 'VERSION_SWB',
	RTRIM(LTRIM(A.[OS_VERSION])) 'OS_VERSION',
	RTRIM(LTRIM(A.[CHIP])) 'CHIP',
	RTRIM(LTRIM(A.[TELEFONO_CHIP])) 'TELEFONO_CHIP', -- IDENTIFICAR CHIP --
    CASE LEFT(RTRIM(LTRIM(A.CHIP)),6)
		WHEN '893407' THEN 'MOVISTAR-SM'
		WHEN '895106' THEN 'MOVISTAR'
		WHEN '895110' THEN 'CLARO'
		WHEN '895117' THEN 'ENTEL'
		WHEN '895115' THEN 'BITEL'
		ELSE RTRIM(LTRIM(A.[OPERADOR]))
	END 'OPERADOR',
	RTRIM(LTRIM(A.[ESTADO_COMERCIO])) 'ESTADO_COMERCIO',
	RTRIM(LTRIM(A.[ESTADO_LOGICO_COMERCIO])) 'ESTADO_LOGICO_COMERCIO',
	RTRIM(LTRIM(A.[ESTADO_TERMINAL])) 'ESTADO_TERMINAL',
	RTRIM(LTRIM(A.[ESTADO_LOGICO_TERMINAL])) 'ESTADO_LOGICO_TERMINAL',
	RTRIM(LTRIM(A.[APLICACION])) 'APLICACION',
	-- IDENTIFICAR APLICACION POS --
	CASE
		WHEN A.[APLICACION]='POS' THEN 'ADQUIRIENTE'
		WHEN A.[APLICACION]='BNACJCO' THEN 'BANCO NACION'
		WHEN A.[APLICACION]='BRIPLEY' THEN 'ADQUIRIENTE'
		WHEN A.[APLICACION]='CAJERO' THEN 'SCOTIABANK'
		WHEN A.[APLICACION]='CMACHYO' THEN 'CMAC HUANCAYO'
		WHEN A.[APLICACION]='CMAREQUIPA' THEN 'CMAC AREQUIPA'
		WHEN A.[APLICACION]='HERMESMB' THEN 'SCOTIABANK'
		WHEN A.[APLICACION]='IBDIRECTO' THEN 'INTERBANK'
		WHEN A.[APLICACION]='PUNTOS' THEN 'ADQUIRIENTE'
		WHEN A.[APLICACION]='APLSCOTCUPN' THEN 'ADQUIRIENTE'
		WHEN A.[APLICACION]='CMICA' THEN 'CMAC ICA'
	END 'APL_DESC',
	RTRIM(LTRIM(A.[FACTURACION])) 'FACTURACION',
	RTRIM(LTRIM(A.[dTrE105SN])) 'dTrE105SN',
	RTRIM(LTRIM(A.[VERSION_FLUJO])) 'VERSION_FLUJO',
	RTRIM(LTRIM(A.[VERSION_MAIN])) 'VERSION_MAIN',
	-- OBTENER SERIE COMPLETA DE POS --
    CASE
		WHEN C.Serie IS NOT NULL THEN C.Serie
		WHEN D.Serie IS NOT NULL THEN D.Serie
		WHEN H.Serie IS NOT NULL THEN H.Serie
	END AS 'SERIE_COMPLETA',
	-- OBTENER MODELO POS --
	CASE
		WHEN F.Marca IS NOT NULL THEN F.Marca
		ELSE A.MODELO
	END AS 'MARCA',
	CASE 
		WHEN A.MODELO IN ('ClienteAD','ClienteIPH') THEN 'PCI'
		WHEN RTRIM(LTRIM(A.[VERSION_SWB])) IN ('B8.001','B8.002','B8.003','B8.012','B8.013','B8.014','B8.015',
					'B8.017','B8.018','B8.019','B8.022','B8.100','B8.110','B8.111','B8.114',
					'B8.306','B8.401','B8.420','B8.423','B8.460') THEN 'PRE PCI'
		WHEN F.PCI IS NOT NULL THEN F.PCI
		ELSE 'PCI'
	END AS 'FLG_PCI',
	CASE
		WHEN F.CTLS IN ('NO HW CTLS','NO SW CTLS') THEN '2.POS sin App CTLS'	
		WHEN A.VERSION_SWB IN ('B7.854','B8.001','B8.002','B8.003','B8.012','B8.013',
		'B8.014','B8.015','B8.017','B8.018','B8.019','B8.022','B8.100','B8.110','B8.111','B8.114','B8.306','B8.401','B8.420',
		'B8.423','B8.460','B8.463','B8.464','B8.481','B8.4815','B80106','B80107','B80108','B80112','B80113','B80114','B80115',
		'B80117','B80118','B80119')THEN '2.POS sin App CTLS'
		ELSE '1.POS con App CTLS'
	END AS 'SW_CTLS',
	CASE
		WHEN F.CTLS ='NO HW CTLS' THEN '2.POS sin HW CTLS'		
		ELSE '1.POS con HW CTLS'
	END AS 'HW_CTLS',
	RTRIM(LTRIM(A.[PRE_AUTORIZACION_NIVEL_COMERCIO])) 'PRE_AUTORIZACION_NIVEL_COMERCIO',
	RTRIM(LTRIM(A.[PRE_AUTORIZACION_NIVEL_TERMINAL])) 'PRE_AUTORIZACION_NIVEL_TERMINAL',
	RTRIM(LTRIM(A.[DIGITACION_MANUAL_NIVEL_COMERCIO])) 'DIGITACION_MANUAL_NIVEL_COMERCIO',
	RTRIM(LTRIM(A.[DIGITACION_MANUAL_NIVEL_TERMINAL])) 'DIGITACION_MANUAL_NIVEL_TERMINAL',
	RTRIM(LTRIM(A.[PROPINA])) 'PROPINA',
	RTRIM(LTRIM(A.[FECHA_ACTUALIZACION_APP])) 'FECHA_ACTUALIZACION_APP',
	RTRIM(LTRIM(A.[HORA_ACTUALIZACION_APP])) 'HORA_ACTUALIZACION_APP',
	RTRIM(LTRIM(A.[NUM_INTENTOS])) 'NUM_INTENTOS',
	RTRIM(LTRIM(A.[FECHA_ULTIMA_ACTUALIZACION])) 'FECHA_ULTIMA_ACTUALIZACION',
	RTRIM(LTRIM(A.[HORA_ULTIMA_ACTUALIZACION])) 'HORA_ULTIMA_ACTUALIZACION',
	RTRIM(LTRIM(A.[VERSION_ACTUALIZADO])) 'VERSION_ACTUALIZADO',
	RTRIM(LTRIM(A.[cTAFilesVersion])) 'cTAFilesVersion',
	RTRIM(LTRIM(A.[cVrVersionId])) 'cVrVersionId',
	RTRIM(LTRIM(A.[cTAVersionApl])) 'cTAVersionApl',
	RTRIM(LTRIM(A.[dVrFile])) 'dVrFile',
	RTRIM(LTRIM(C.[Marguesi])) 'Marguesi',
	RTRIM(LTRIM(C.[FecCompra])) 'FEC_COMPRA',
	CASE
		WHEN RTRIM(LTRIM(C.[Estado]))='A' THEN 'Activo'
		WHEN RTRIM(LTRIM(C.[Estado]))='B' THEN 'Baja'
		WHEN RTRIM(LTRIM(C.[Estado]))='Q' THEN 'Alquiler'
		WHEN RTRIM(LTRIM(C.[Estado]))='V' THEN 'Venta'
	END AS 'SITUACION_AS400',
	CASE 
		WHEN CAST(CASE WHEN A.[VERSION_FLUJO]='' THEN 0 ELSE A.[VERSION_FLUJO] END AS numeric)<=214 AND A.[VERSION_SWB] IN ('B7.854','B8.001','B8.002','B8.003','B8.012','B8.013',
		'B8.014','B8.015','B8.017','B8.018','B8.019','B8.022','B8.100','B8.110','B8.111','B8.114','B8.306','B8.401','B8.420',
		'B80106','B80107','B80108','B80112','B80113','B80114','B80115','B80117','B80118','B80119')	THEN '2.POS no EMV DINERS'
		WHEN A.[VERSION_SWB] IN ('B80106','B80107','B80108','B80112','B80113','B80114','B80115','B80117','B80118','B80119') THEN '2.POS no EMV DINERS'
		ELSE '1.POS EMV DINERS'
	END AS 'EMV_DINERS',
	E.CANT_TERM,
	E.CANT_TERM_ACT,
	CASE
		WHEN E.CANT_PINPAD = 0 THEN 'COMERCIO_NO_PINPAD'
		ELSE 'COMERCIO_PINPAD'
	END AS 'FLG_PINPAD',
	CASE
		WHEN A.MULTICOMERCIO IN ('0','2') THEN 'MULTICOMERCIO'
		ELSE 'COMERCIO'
	END AS 'FLG_MULTICOMERCIO',
	RTRIM(LTRIM(B.GIRO)) 'GIRO',
	'***REVISAR***' AS 'SERIE_UNICA',
	RTRIM(LTRIM(B.[Grup_econo_desc])) 'GRUPO_ECONOMICO',
	RTRIM(LTRIM(B.FECAPE)) 'FECAPE',
	CASE
		WHEN B.FECAPE <>'' AND B.FECAPE<>'01' AND datediff(month,cast(cast(B.FECAPE as char) as datetime),cast(@FECHA as datetime))>=12 then '1. Cosecha 1 anio a mas'
		WHEN B.FECAPE <>'' AND B.FECAPE<>'01' AND datediff(month,cast(cast(B.FECAPE as char) as datetime),cast(@FECHA as datetime))>=6 then '2 .Cosecha de 6 a 12 meses'
		WHEN B.FECAPE <>'' AND B.FECAPE<>'01' AND datediff(month,cast(cast(B.FECAPE as char) as datetime),cast(@FECHA as datetime))>=3 then '3. Cosecha de 3 a 6 meses'
		WHEN B.FECAPE <>'' AND B.FECAPE<>'01' then  concat('4. ',LEFT(rtrim(ltrim(B.FECAPE)),6))
	END AS 'COSECHA',
	CASE
		WHEN A.DEPARTAMENTO='LA LIBERTAD' THEN 'OF. Trujillo'
		WHEN A.DEPARTAMENTO='AREQUIPA' THEN 'OF. Arequipa'
		WHEN A.DEPARTAMENTO='PIURA' THEN 'OF. Piura'
		WHEN A.DEPARTAMENTO='CUSCO' THEN 'OF. Cusco'
		WHEN A.DEPARTAMENTO='LAMBAYEQUE' THEN 'OF. Chiclayo'
		WHEN A.DEPARTAMENTO='ICA' THEN 'OF. Ica'
		WHEN A.DEPARTAMENTO='JUNIN' THEN 'OF. Huancayo'
		WHEN A.DEPARTAMENTO='ANCASH' THEN 'OF. Trujillo'
		WHEN A.DEPARTAMENTO='CAJAMARCA' THEN 'OF. Chiclayo'
		WHEN A.DEPARTAMENTO='LORETO' THEN 'OF. Iquitos'
		WHEN A.DEPARTAMENTO='SAN MARTIN' THEN 'OF. Chiclayo'
		WHEN A.DEPARTAMENTO='PUNO' THEN 'OF. Cusco'
		WHEN A.DEPARTAMENTO='UCAYALI' THEN 'OF. Huancayo'
		WHEN A.DEPARTAMENTO='HUANUCO' THEN 'OF. Huancayo'
		WHEN A.DEPARTAMENTO='TACNA' THEN 'OF. Arequipa'
		WHEN A.DEPARTAMENTO='TUMBES' THEN 'OF. Piura'
		WHEN A.DEPARTAMENTO='AYACUCHO' THEN 'OF. Ica'
		WHEN A.DEPARTAMENTO='MOQUEGUA' THEN 'OF. Arequipa'
		WHEN A.DEPARTAMENTO='HUANCAVELICA' THEN 'OF.Huancayo'
		WHEN A.DEPARTAMENTO='APURIMAC' THEN 'OF. Cusco'
		WHEN A.DEPARTAMENTO='AMAZONAS' THEN 'OF. Chiclayo'
		WHEN A.DEPARTAMENTO='PASCO' THEN 'OF. Huancayo'
		WHEN A.DEPARTAMENTO='MADRE DE DIOS' THEN 'OF. Cusco'
		ELSE 'Lima'
	END 'OFICINA',
	ISNULL(RTRIM(LTRIM(F.Modelo_Terminal)),RTRIM(LTRIM(A.MODELO))) 'MODELO_TERMINAL',
	CASE
		WHEN A.VERSION_SWB='' THEN 's/version'
		WHEN A.VERSION_SWB='000000' THEN 'v/error'
		ELSE A.VERSION_SWB
	END AS 'VERSION_BASE',
	'***REVISAR***' AS 'FEC_INST',
	RTRIM(LTRIM(B.Multcom)) 'COD_MADRE',
	RTRIM(LTRIM(B.Multmon)) 'COD_DOL'
INTO #MAESTRO_TERMINALES
FROM [Stage].[StgTerminalA] A
	LEFT JOIN [DWH].[BI_Mcestab] B ON LEFT(A.[COMERCIO],7)=B.[Codigo]
	LEFT JOIN #DataTerminalesAS C ON LEFT(A.COMERCIO,7) =C.CodComercio 
		AND ((A.SERIE = RIGHT(REPLACE(REPLACE(C.[Serie],' ',''),'-',''),8) 
		AND LEFT(RTRIM(LTRIM(A.[MODELO])),7) <> 'Cliente'
		AND C.MARCA IN ('INGENICO','PAX','SUNMI','VERIFON','VERIFONE','SUMNI'))	OR (A.[dTrE105SN] = RIGHT(REPLACE(REPLACE(C.[Serie],' ',''),'-',''),9)
		AND LEFT(RTRIM(LTRIM(A.[MODELO])),7) = 'Cliente'
		AND C.MARCA IN ('DS1READ','DSPREAD','WISEPAD')))
	LEFT JOIN #TEMP_SERIES_U8 D  ON (A.SERIE = RIGHT(REPLACE(REPLACE(D.[Serie],' ',''),'-',''),8) AND LEFT(RTRIM(LTRIM(A.[MODELO])),7) <> 'Cliente')
	LEFT JOIN #TEMP_COMERCIO_A E ON A.COMERCIO=E.COMERCIO
	LEFT JOIN #TEMP_MODELO F ON A.MODELO=F.Modelo_MCC
	LEFT JOIN #SITUACION G ON B.[Situac]=G.[Situac]
	LEFT JOIN #TEMP_SERIES_U9 H ON (A.[dTrE105SN] = RIGHT(REPLACE(REPLACE(H.[Serie],' ',''),'-',''),9) AND LEFT(RTRIM(LTRIM(A.[MODELO])),7) = 'Cliente')
WHERE LEFT(A.COMERCIO,1)<>'3'
-- 854,023 filas
-- 03:06 sec

/*===================================== PROCESO 6.2 ====================================== 
	Generamos la tabla temporal #MAESTRO_TERMINALES para CAJERO
=========================================================================================*/ 
INSERT INTO #MAESTRO_TERMINALES 
SELECT DISTINCT
	RTRIM(LTRIM(A.[COMERCIO])) 'COMERCIO',
	CASE
		WHEN B.[Pay_faci_id]='IZI*IZIPAY' THEN 'C.COR-IZIPAY'
		WHEN B.[Pay_faci_id]='BN*FP' THEN 'C.COR-PMP'
		WHEN B.[Pay_faci_id] IS NULL THEN 'C.COR-PMP'
		ELSE B.[Pay_faci_id]
	END 'ADQ/C.COR',
	RTRIM(LTRIM(A.[NOMBRE])) 'NOMBRE',
	ISNULL(RTRIM(LTRIM(B.[Mcc])),RTRIM(LTRIM(A.[RUBRO]))) 'RUBRO',
	G.Situac_Desc 'SITUACION',
	CASE 
		WHEN A.[APLICACION]='BNACJCO' THEN '4. BANCO NACION'
		WHEN A.[APLICACION]='CAJERO' THEN '8. SCOTIABANK'
		WHEN A.[APLICACION]='CMACHYO' THEN '6. CMAC HUANCAYO'
		WHEN A.[APLICACION]='CMAREQUIPA' THEN '5. CMAC AREQUIPA'
		WHEN A.[APLICACION]='HERMESMB' THEN '8. SCOTIABANK'
		WHEN A.[APLICACION]='IBDIRECTO' THEN '7. INTERBANK'
		WHEN A.[APLICACION]='CMICA' THEN '9. CMAC ICA'
	END 'CATEGORIA',
	RTRIM(LTRIM(B.[Razsoc])) 'RAZON_SOCIAL',
	ISNULL(RTRIM(LTRIM(B.[Nroruc])),RTRIM(LTRIM(A.[RUC]))) 'RUC',
	RTRIM(LTRIM(A.[DIRECCION])) 'DIRECCION',
	RTRIM(LTRIM(A.[DEPARTAMENTO])) 'DEPARTAMENTO',
	RTRIM(LTRIM(A.[PROVINCIA])) 'PROVINCIA',
	RTRIM(LTRIM(A.[DISTRITO])) 'DISTRITO',
	RTRIM(LTRIM(A.[MULTICOMERCIO])) 'MULTICOMERCIO',
	RTRIM(LTRIM(A.[TELEFONO_COMERCIO])) 'TELEFONO_COMERCIO',
	RTRIM(LTRIM(A.[CONTACTO])) 'CONTACTO',
	RTRIM(LTRIM(A.[PERFIL_COMERCIO])) 'PERFIL_COMERCIO',
	RTRIM(LTRIM(A.[PERFIL_DESCARGA])) 'PERFIL_DESCARGA',
	RTRIM(LTRIM(A.[TERMINAL])) 'TERMINAL',
	RTRIM(LTRIM(A.[SERIE])) 'SERIE',
	RTRIM(LTRIM(A.[MEDIO])) 'MEDIO_MCC',
	ISNULL(RTRIM(LTRIM(F.medio)),
	CASE
		WHEN RTRIM(LTRIM(A.[CHIP])) <> '' THEN 'GPRS Fijo'
		WHEN RTRIM(LTRIM(A.[MEDIO])) = 'ETHERNET' THEN 'IP'
		WHEN RTRIM(LTRIM(A.[MEDIO])) = 'DIAL' THEN 'DIAL'
		ELSE  'IP'
	END ) 'MEDIO',
	RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) 'DESCRIPCION_TERMINAL',
	RTRIM(LTRIM(A.[FECHA_ULTIMO_ECO])) 'FECHA_ULTIMO_ECO',
	RTRIM(LTRIM(A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA])) 'FECHA_ULTIMA_TRANSACCION_FINANCIERA',
	RTRIM(LTRIM(A.[FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA])) 'FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA',
	-- CALCULO SITUACION DE TERMINAL --
	CASE
		WHEN A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA] IS NULL THEN '99 - Sin registro de trx.'
		WHEN datediff(month,cast(A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>12 THEN '2 - Sin movimiento ultimos 12 meses.'
		WHEN datediff(month,cast(A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>6 THEN '6 - Sin movimiento ultimos 6 meses.'
		WHEN datediff(month,cast(A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>3 THEN '4 - Sin movimiento ultimos 3 meses.'
		WHEN datediff(month,cast(A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>=0 THEN '1 - Con movimiento en los ultimos 3 meses.'
		ELSE '2 - Sin movimiento ultimos 12 meses.'
	END 'SITUACION_TERMINAL',
	RTRIM(LTRIM(C.MODELO)) 'MODELO', -- MODELO AS400
	RTRIM(LTRIM(A.[MODELO])) 'MODELO_MCC',
	RTRIM(LTRIM(A.[VERSION_SWB])) 'VERSION_SWB',
	RTRIM(LTRIM(A.[OS_VERSION])) 'OS_VERSION',
	RTRIM(LTRIM(A.[CHIP])) 'CHIP',
	RTRIM(LTRIM(A.[TELEFONO_CHIP])) 'TELEFONO_CHIP',
	-- IDENTIFICAR CHIP --
    CASE LEFT(RTRIM(LTRIM(A.CHIP)),6)
		WHEN '893407' THEN 'MOVISTAR-SM'
		WHEN '895106' THEN 'MOVISTAR'
		WHEN '895110' THEN 'CLARO'
		WHEN '895117' THEN 'ENTEL'
		WHEN '895115' THEN 'BITEL'
		ELSE RTRIM(LTRIM(A.[OPERADOR]))
	END 'OPERADOR',
	RTRIM(LTRIM(A.[ESTADO_COMERCIO])) 'ESTADO_COMERCIO',
	RTRIM(LTRIM(A.[ESTADO_LOGICO_COMERCIO])) 'ESTADO_LOGICO_COMERCIO',
	RTRIM(LTRIM(A.[ESTADO_TERMINAL])) 'ESTADO_TERMINAL',
	RTRIM(LTRIM(A.[ESTADO_LOGICO_TERMINAL])) 'ESTADO_LOGICO_TERMINAL',
	RTRIM(LTRIM(A.[APLICACION])) 'APLICACION',
	-- IDENTIFICAR APLICACION POS --
	CASE
		WHEN A.[APLICACION]='POS' THEN 'ADQUIRIENTE'
		WHEN A.[APLICACION]='BNACJCO' THEN 'BANCO NACION'
		WHEN A.[APLICACION]='BRIPLEY' THEN 'ADQUIRIENTE'
		WHEN A.[APLICACION]='CAJERO' THEN 'SCOTIABANK'
		WHEN A.[APLICACION]='CMACHYO' THEN 'CMAC HUANCAYO'
		WHEN A.[APLICACION]='CMAREQUIPA' THEN 'CMAC AREQUIPA'
		WHEN A.[APLICACION]='HERMESMB' THEN 'SCOTIABANK'
		WHEN A.[APLICACION]='IBDIRECTO' THEN 'INTERBANK'
		WHEN A.[APLICACION]='PUNTOS' THEN 'ADQUIRIENTE'
		WHEN A.[APLICACION]='APLSCOTCUPN' THEN 'ADQUIRIENTE'
		WHEN A.[APLICACION]='CMICA' THEN 'CMAC ICA'
	END 'APL_DESC',
	RTRIM(LTRIM(A.[FACTURACION])) 'FACTURACION',
	RTRIM(LTRIM(A.[dTrE105SN])) 'dTrE105SN',
	RTRIM(LTRIM(A.[VERSION_FLUJO])) 'VERSION_FLUJO',
	RTRIM(LTRIM(A.[VERSION_MAIN])) 'VERSION_MAIN',
	-- OBTENER SERIE COMPLETA DE POS --
    CASE
		WHEN C.Serie IS NOT NULL THEN C.Serie
		WHEN D.Serie IS NOT NULL THEN D.Serie
		WHEN H.Serie IS NOT NULL THEN H.Serie
	END 'SERIE_COMPLETA',
	-- OBTENER MODELO POS --
	CASE
		WHEN F.Marca IS NOT NULL THEN F.Marca
		ELSE A.MODELO
	END 'MARCA',
	'No Aplica' 'FLG_PCI',
	'No Aplica' 'SW_CTLS',
	'No Aplica' 'HW_CTLS',
	RTRIM(LTRIM(A.[PRE_AUTORIZACION_NIVEL_COMERCIO])) 'PRE_AUTORIZACION_NIVEL_COMERCIO',
	RTRIM(LTRIM(A.[PRE_AUTORIZACION_NIVEL_TERMINAL])) 'PRE_AUTORIZACION_NIVEL_TERMINAL',
	RTRIM(LTRIM(A.[DIGITACION_MANUAL_NIVEL_COMERCIO])) 'DIGITACION_MANUAL_NIVEL_COMERCIO',
	RTRIM(LTRIM(A.[DIGITACION_MANUAL_NIVEL_TERMINAL])) 'DIGITACION_MANUAL_NIVEL_TERMINAL',
	RTRIM(LTRIM(A.[PROPINA])) 'PROPINA',
	RTRIM(LTRIM(A.[FECHA_ACTUALIZACION_APP])) 'FECHA_ACTUALIZACION_APP',
	RTRIM(LTRIM(A.[HORA_ACTUALIZACION_APP])) 'HORA_ACTUALIZACION_APP',
	RTRIM(LTRIM(A.[NUM_INTENTOS])) 'NUM_INTENTOS',
	RTRIM(LTRIM(A.[FECHA_ULTIMA_ACTUALIZACION])) 'FECHA_ULTIMA_ACTUALIZACION',
	RTRIM(LTRIM(A.[HORA_ULTIMA_ACTUALIZACION])) 'HORA_ULTIMA_ACTUALIZACION',
	RTRIM(LTRIM(A.[VERSION_ACTUALIZADO])) 'VERSION_ACTUALIZADO',
	RTRIM(LTRIM(A.[cTAFilesVersion])) 'cTAFilesVersion',
	RTRIM(LTRIM(A.[cVrVersionId])) 'cVrVersionId',
	RTRIM(LTRIM(A.[cTAVersionApl])) 'cTAVersionApl',
	RTRIM(LTRIM(A.[dVrFile])) 'dVrFile',
	RTRIM(LTRIM(C.[Marguesi])) 'Marguesi',
	RTRIM(LTRIM(C.[FecCompra])) 'FEC_COMPRA',
	CASE
		WHEN RTRIM(LTRIM(C.[Estado]))='A' THEN 'Activo'
		WHEN RTRIM(LTRIM(C.[Estado]))='B' THEN 'Baja'
		WHEN RTRIM(LTRIM(C.[Estado]))='Q' THEN 'Alquiler'
		WHEN RTRIM(LTRIM(C.[Estado]))='V' THEN 'Venta'
	END 'SITUACION_AS400',
	'No Aplica' 'EMV_DINERS',
	E.CANT_TERM,
	E.CANT_TERM_ACT,
	'No Aplica' 'FLG_PINPAD',
	CASE
		WHEN A.MULTICOMERCIO IN ('0','2') THEN 'MULTICOMERCIO'
		ELSE 'COMERCIO'
	END 'FLG_MULTICOMERCIO',
	RTRIM(LTRIM(B.GIRO)) 'GIRO',
	'***REVISAR***' AS 'SERIE_UNICA',
	RTRIM(LTRIM(B.[Grup_econo_desc])) 'GRUPO_ECONOMICO',
	RTRIM(LTRIM(B.FECAPE)) 'FECAPE',
	CASE
		WHEN B.FECAPE <>'' AND B.FECAPE<>'01' AND datediff(month,cast(cast(B.FECAPE as char) as datetime),cast(@FECHA as datetime))>=12 then '1. Cosecha 1 anio a mas'
		WHEN B.FECAPE <>'' AND B.FECAPE<>'01' AND datediff(month,cast(cast(B.FECAPE as char) as datetime),cast(@FECHA as datetime))>=6 then '2 .Cosecha de 6 a 12 meses'
		WHEN B.FECAPE <>'' AND B.FECAPE<>'01' AND datediff(month,cast(cast(B.FECAPE as char) as datetime),cast(@FECHA as datetime))>=3 then '3. Cosecha de 3 a 6 meses'
		WHEN B.FECAPE <>'' AND B.FECAPE<>'01' THEN  concat('4. ',LEFT(rtrim(ltrim(B.FECAPE)),6))
	END 'COSECHA',
    CASE
		WHEN A.DEPARTAMENTO='LA LIBERTAD' THEN 'OF. Trujillo'
		WHEN A.DEPARTAMENTO='AREQUIPA' THEN 'OF. Arequipa'
		WHEN A.DEPARTAMENTO='PIURA' THEN 'OF. Piura'
		WHEN A.DEPARTAMENTO='CUSCO' THEN 'OF. Cusco'
		WHEN A.DEPARTAMENTO='LAMBAYEQUE' THEN 'OF. Chiclayo'
		WHEN A.DEPARTAMENTO='ICA' THEN 'OF. Ica'
		WHEN A.DEPARTAMENTO='JUNIN' THEN 'OF. Huancayo'
		WHEN A.DEPARTAMENTO='ANCASH' THEN 'OF. Trujillo'
		WHEN A.DEPARTAMENTO='CAJAMARCA' THEN 'OF. Chiclayo'
		WHEN A.DEPARTAMENTO='LORETO' THEN 'OF. Iquitos'
		WHEN A.DEPARTAMENTO='SAN MARTIN' THEN 'OF. Chiclayo'
		WHEN A.DEPARTAMENTO='PUNO' THEN 'OF. Cusco'
		WHEN A.DEPARTAMENTO='UCAYALI' THEN 'OF. Huancayo'
		WHEN A.DEPARTAMENTO='HUANUCO' THEN 'OF. Huancayo'
		WHEN A.DEPARTAMENTO='TACNA' THEN 'OF. Arequipa'
		WHEN A.DEPARTAMENTO='TUMBES' THEN 'OF. Piura'
		WHEN A.DEPARTAMENTO='AYACUCHO' THEN 'OF. Ica'
		WHEN A.DEPARTAMENTO='MOQUEGUA' THEN 'OF. Arequipa'
		WHEN A.DEPARTAMENTO='HUANCAVELICA' THEN 'OF.Huancayo'
		WHEN A.DEPARTAMENTO='APURIMAC' THEN 'OF. Cusco'
		WHEN A.DEPARTAMENTO='AMAZONAS' THEN 'OF. Chiclayo'
		WHEN A.DEPARTAMENTO='PASCO' THEN 'OF. Huancayo'
		WHEN A.DEPARTAMENTO='MADRE DE DIOS' THEN 'OF. Cusco'
		ELSE 'Lima'
	END 'OFICINA',
    ISNULL(RTRIM(LTRIM(F.Modelo_Terminal)),RTRIM(LTRIM(A.MODELO))) 'MODELO_TERMINAL',
    CASE
		WHEN A.VERSION_SWB='' THEN 's/version'
		WHEN A.VERSION_SWB='000000' THEN 'v/error'
		ELSE A.VERSION_SWB
	END 'VERSION_BASE',
	'***REVISAR***' AS 'FEC_INST',
	RTRIM(LTRIM(B.Multcom)) 'COD_MADRE',
	RTRIM(LTRIM(B.Multmon)) 'COD_DOL'
FROM [Stage].[StgTerminalCc] A
LEFT JOIN [DWH].[BI_Mcestab] B ON LEFT(A.[COMERCIO],7)=B.[Codigo]
LEFT JOIN #DataTerminalesAS C ON LEFT(A.COMERCIO,7) =C.CodComercio 
	AND ((A.SERIE = RIGHT(REPLACE(REPLACE(C.[Serie],' ',''),'-',''),8) 
	AND LEFT(RTRIM(LTRIM(A.[MODELO])),7) <> 'Cliente'
	AND C.MARCA IN ('INGENICO','PAX','SUNMI','VERIFON','VERIFONE','SUMNI'))
	OR (A.[dTrE105SN] = RIGHT(REPLACE(REPLACE(C.[Serie],' ',''),'-',''),9) 
		AND LEFT(RTRIM(LTRIM(A.[MODELO])),7) = 'Cliente'
		AND C.MARCA IN ('DS1READ','DSPREAD','WISEPAD')))
LEFT JOIN #TEMP_SERIES_U8 D ON (A.SERIE = RIGHT(REPLACE(REPLACE(D.[Serie],' ',''),'-',''),8) AND LEFT(RTRIM(LTRIM(A.[MODELO])),7) <> 'Cliente')
LEFT JOIN #TEMP_COMERCIO_CC E ON A.COMERCIO=E.COMERCIO
LEFT JOIN #TEMP_MODELO F ON A.MODELO=F.Modelo_MCC
LEFT JOIN #SITUACION G ON B.[Situac]=G.[Situac]
LEFT JOIN #TEMP_SERIES_U9 H ON (A.[dTrE105SN] = RIGHT(REPLACE(REPLACE(H.[Serie],' ',''),'-',''),9) AND LEFT(RTRIM(LTRIM(A.[MODELO])),7) = 'Cliente')
WHERE LEFT(A.COMERCIO,1)='3'
-- 47,023 filas
-- 00:46 sec

------ Borrado de tablas temporales ------ 
DROP TABLE #TEMP_COMERCIO_A;
DROP TABLE #TEMP_COMERCIO_CC;
DROP TABLE #TEMP_MODELO;
DROP TABLE #TEMP_SERIES_U8;
DROP TABLE #TEMP_SERIES_U9;
DROP TABLE #SITUACION;

/*===================================== PROCESO 7 ====================================== 
	Tabla para completar las series completas por serie unica 8 Y 9
=========================================================================================*/ 
IF OBJECT_ID('TempDB..#SERIES_COMPLETAS') IS NOT NULL
BEGIN
	TRUNCATE TABLE #SERIES_COMPLETAS;
	DROP TABLE #SERIES_COMPLETAS;
END;

SELECT DISTINCT SERIE_COMPLETA
	,COD_MADRE
	,FLG_MULTICOMERCIO
INTO #SERIES_COMPLETAS
FROM #MAESTRO_TERMINALES
WHERE SERIE_COMPLETA IS NOT NULL

IF OBJECT_ID('TempDB..#TEMP_SERIES_U8_2') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMP_SERIES_U8_2;
	DROP TABLE #TEMP_SERIES_U8_2;
END;

SELECT 
	MIN(A.[Serie]) 'Serie',
	RIGHT(REPLACE(REPLACE(A.[Serie],' ',''),'-',''),8) 'Serie_corta'
INTO #TEMP_SERIES_U8_2
FROM #DataTerminalesAS A
	LEFT JOIN #SERIES_COMPLETAS B ON A.SERIE=B.SERIE_COMPLETA
WHERE A.MARCA IN ('INGENICO','PAX','SUNMI','VERIFON','VERIFONE','SUMNI')
	AND A.ESTADO <>'B'
	AND (B.SERIE_COMPLETA IS NULL OR B.FLG_MULTICOMERCIO='MULTICOMERCIO')
GROUP BY RIGHT(REPLACE(REPLACE(A.[Serie],' ',''),'-',''),8)
	
IF OBJECT_ID('TempDB..#TEMP_SERIES_U9_2') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMP_SERIES_U9_2;
	DROP TABLE #TEMP_SERIES_U9_2;
END;

SELECT 
	MIN(A.[Serie]) 'Serie',
	RIGHT(REPLACE(REPLACE(A.[Serie],' ',''),'-',''),9) 'Serie_corta'
INTO #TEMP_SERIES_U9_2
FROM #DataTerminalesAS A
	LEFT JOIN #SERIES_COMPLETAS B ON A.SERIE=B.SERIE_COMPLETA
WHERE A.MARCA IN ('DS1READ','DSPREAD','WISEPAD')
	AND A.ESTADO <>'B'
	AND B.SERIE_COMPLETA IS NULL
GROUP BY RIGHT(REPLACE(REPLACE(A.[Serie],' ',''),'-',''),9)
-- 754,196 / 174,347 / 21,483 filas
-- 00:13 sec

/*===================================== PROCESO 8 ====================================== 
	Actualizacion de series completas en la tabla temporal #MAESTRO_TERMINALES_2
=========================================================================================*/ 
IF OBJECT_ID('TempDB..#MAESTRO_TERMINALES_2') IS NOT NULL
BEGIN
	TRUNCATE TABLE #MAESTRO_TERMINALES_2;
	DROP TABLE #MAESTRO_TERMINALES_2;
END;

SELECT DISTINCT
	A.[COMERCIO],
	A.[ADQ/C.COR],
	A.[NOMBRE],
	A.[RUBRO],
	A.[SITUACION],
	A.[CATEGORIA],
	A.[RAZON_SOCIAL],
	A.[RUC],
	A.[DIRECCION],
	A.[DEPARTAMENTO],
	A.[PROVINCIA],
	A.[DISTRITO],
	A.[MULTICOMERCIO],
	A.[TELEFONO_COMERCIO],
	A.[CONTACTO],
	A.[PERFIL_COMERCIO],
	A.[PERFIL_DESCARGA],
	A.[TERMINAL],
	A.[SERIE],
	A.[MEDIO_MCC],
	A.[MEDIO],
	A.[DESCRIPCION_TERMINAL],
	A.[FECHA_ULTIMO_ECO],
	A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA],
	A.[FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA],
	A.[SITUACION_TERMINAL],
	A.[MODELO],
	A.[MODELO_MCC],
	A.[VERSION_SWB],
	A.[OS_VERSION],
	A.[CHIP],
	A.[TELEFONO_CHIP],
	A.[OPERADOR],
	A.[ESTADO_COMERCIO],
	A.[ESTADO_LOGICO_COMERCIO],
	A.[ESTADO_TERMINAL],
	A.[ESTADO_LOGICO_TERMINAL],
	A.[APLICACION],
	A.[APL_DESC],
	A.[FACTURACION],
	A.[dTrE105SN],
	A.[VERSION_FLUJO],
	A.[VERSION_MAIN],
	ISNULL(A.[SERIE_COMPLETA],ISNULL(D.SERIE_COMPLETA,ISNULL(B.SERIE,C.SERIE))) 'SERIE_COMPLETA',
	A.[MARCA],
	A.[FLG_PCI],
	A.[SW_CTLS],
	A.[HW_CTLS],
	A.[PRE_AUTORIZACION_NIVEL_COMERCIO],
	A.[PRE_AUTORIZACION_NIVEL_TERMINAL],
	A.[DIGITACION_MANUAL_NIVEL_COMERCIO],
	A.[DIGITACION_MANUAL_NIVEL_TERMINAL],
	A.[PROPINA],
	A.[FECHA_ACTUALIZACION_APP],
	A.[HORA_ACTUALIZACION_APP],
	A.[NUM_INTENTOS],
	A.[FECHA_ULTIMA_ACTUALIZACION],
	A.[HORA_ULTIMA_ACTUALIZACION],
	A.[VERSION_ACTUALIZADO],
	A.[cTAFilesVersion],
	A.[cVrVersionId],
	A.[cTAVersionApl],
	A.[dVrFile],
	A.[Marguesi],
	A.[FEC_COMPRA],
	A.[SITUACION_AS400],
	A.[EMV_DINERS],
	A.[CANT_TERM],
	A.[CANT_TERM_ACT],
	A.[FLG_PINPAD],
	A.[FLG_MULTICOMERCIO],
	A.[GIRO],
	A.[SERIE_UNICA],
	A.[GRUPO_ECONOMICO],
	A.[FECAPE],
	A.[COSECHA],
	A.[OFICINA],
	A.[MODELO_TERMINAL],
	A.[VERSION_BASE],
	A.[FEC_INST],
	A.[COD_MADRE],
	A.[COD_DOL]
INTO #MAESTRO_TERMINALES_2
FROM #MAESTRO_TERMINALES A
	LEFT JOIN #TEMP_SERIES_U8_2 B ON (A.SERIE = RIGHT(REPLACE(REPLACE(B.[Serie],' ',''),'-',''),8) AND LEFT(RTRIM(LTRIM(A.[MODELO_MCC])),7) <> 'Cliente')
	LEFT JOIN #TEMP_SERIES_U9_2 C ON (A.[dTrE105SN] = RIGHT(REPLACE(REPLACE(C.[Serie],' ',''),'-',''),9) AND LEFT(RTRIM(LTRIM(A.[MODELO_MCC])),7) = 'Cliente')
	LEFT JOIN #SERIES_COMPLETAS D ON ((A.[COD_MADRE] =D.COD_MADRE OR D.COD_MADRE=LEFT(A.[COMERCIO],7))  AND LEFT(A.[ADQ/C.COR],3)='ADQ'
		AND A.SERIE = RIGHT(REPLACE(REPLACE(D.SERIE_COMPLETA,' ',''),'-',''),8) AND LEFT(RTRIM(LTRIM(A.[MODELO_MCC])),7) <> 'Cliente')
		OR (LEFT(A.[ADQ/C.COR],5)='C.COR'
		AND A.SERIE = RIGHT(REPLACE(REPLACE(D.SERIE_COMPLETA,' ',''),'-',''),8) AND LEFT(RTRIM(LTRIM(A.[MODELO_MCC])),7) <> 'Cliente')
-- 854,023 filas
-- 01:39 sec

------ Borrado de tablas temporales ------ 
DROP TABLE #DataTerminalesAS
DROP TABLE #SERIES_COMPLETAS
DROP TABLE #TEMP_SERIES_U8_2
DROP TABLE #TEMP_SERIES_U9_2
DROP TABLE #MAESTRO_TERMINALES

/*===================================== PROCESO 9 ====================================== 
	Actualizacion de series unicas en la tabla temporal #MAESTRO_TERMINALES_3
=========================================================================================*/ 
IF OBJECT_ID('TempDB..#SERIES_UNICAS') IS NOT NULL
BEGIN
	TRUNCATE TABLE #SERIES_UNICAS;
	DROP TABLE #SERIES_UNICAS;
END;

SELECT
	A.SERIE_COMPLETA,
	A.COMERCIO,
	A.TERMINAL,
	A.IDEM
INTO #SERIES_UNICAS
FROM (
	SELECT
		ROW_NUMBER() OVER (PARTITION BY A.SERIE_COMPLETA ORDER BY A.SERIE_COMPLETA ASC,A.FECHA_ULTIMA_TRANSACCION_FINANCIERA DESC,A.COMERCIO ASC) AS IDEM,
		A.SERIE_COMPLETA,
		A.COMERCIO,
		A.TERMINAL
	FROM #MAESTRO_TERMINALES_2 A
	WHERE A.SERIE_COMPLETA IS NOT NULL
) AS A
WHERE IDEM='1';

IF OBJECT_ID('TempDB..#MAESTRO_TERMINALES_3') IS NOT NULL
BEGIN
	TRUNCATE TABLE #MAESTRO_TERMINALES_3;
	DROP TABLE #MAESTRO_TERMINALES_3;
END;

SELECT DISTINCT
	A.[COMERCIO],
	A.[ADQ/C.COR],
	A.[NOMBRE],
	A.[RUBRO],
	A.[SITUACION],
	A.[CATEGORIA],
	A.[RAZON_SOCIAL],
	A.[RUC],
	A.[DIRECCION],
	A.[DEPARTAMENTO],
	A.[PROVINCIA],
	A.[DISTRITO],
	A.[MULTICOMERCIO],
	A.[TELEFONO_COMERCIO],
	A.[CONTACTO],
	A.[PERFIL_COMERCIO],
	A.[PERFIL_DESCARGA],
	A.[TERMINAL],
	A.[SERIE],
	A.[MEDIO_MCC],
	A.[MEDIO],
	A.[DESCRIPCION_TERMINAL],
	A.[FECHA_ULTIMO_ECO],
	A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA],
	A.[FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA],
	A.[SITUACION_TERMINAL],
	A.[MODELO],
	A.[MODELO_MCC],
	A.[VERSION_SWB],
	A.[OS_VERSION],
	A.[CHIP],
	A.[TELEFONO_CHIP],
	A.[OPERADOR],
	A.[ESTADO_COMERCIO],
	A.[ESTADO_LOGICO_COMERCIO],
	A.[ESTADO_TERMINAL],
	A.[ESTADO_LOGICO_TERMINAL],
	A.[APLICACION],
	A.[APL_DESC],
	A.[FACTURACION],
	A.[dTrE105SN],
	A.[VERSION_FLUJO],
	A.[VERSION_MAIN],
	A.SERIE_COMPLETA,
	A.[MARCA],
	A.[FLG_PCI],
	A.[SW_CTLS],
	A.[HW_CTLS],
	A.[PRE_AUTORIZACION_NIVEL_COMERCIO],
	A.[PRE_AUTORIZACION_NIVEL_TERMINAL],
	A.[DIGITACION_MANUAL_NIVEL_COMERCIO],
	A.[DIGITACION_MANUAL_NIVEL_TERMINAL],
	A.[PROPINA],
	A.[FECHA_ACTUALIZACION_APP],
	A.[HORA_ACTUALIZACION_APP],
	A.[NUM_INTENTOS],
	A.[FECHA_ULTIMA_ACTUALIZACION],
	A.[HORA_ULTIMA_ACTUALIZACION],
	A.[VERSION_ACTUALIZADO],
	A.[cTAFilesVersion],
	A.[cVrVersionId],
	A.[cTAVersionApl],
	A.[dVrFile],
	A.[Marguesi],
	A.[FEC_COMPRA],
	A.[SITUACION_AS400],
	A.[EMV_DINERS],
	A.[CANT_TERM],
	A.[CANT_TERM_ACT],
	A.[FLG_PINPAD],
	A.[FLG_MULTICOMERCIO],
	A.[GIRO],
	ISNULL(B.IDEM,0) 'SERIE_UNICA',
	A.[GRUPO_ECONOMICO],
	A.[FECAPE],
	A.[COSECHA],
	A.[OFICINA],
	A.[MODELO_TERMINAL],
	A.[VERSION_BASE],
	A.[FEC_INST],
	A.[COD_MADRE],
	A.[COD_DOL]
INTO #MAESTRO_TERMINALES_3
FROM #MAESTRO_TERMINALES_2 A
	LEFT JOIN #SERIES_UNICAS B ON A.SERIE_COMPLETA=B.SERIE_COMPLETA
		AND A.COMERCIO=B.COMERCIO
		AND A.TERMINAL=B.TERMINAL
		AND ((A.APLICACION IN ('IBDIRECTO','BNACJCO','CAJERO','CMACHYO','CMAREQUIPA','CMICA') AND LEFT(A.[ADQ/C.COR],5)='C.COR')
			OR (A.APLICACION = 'POS' AND LEFT(A.[ADQ/C.COR],3)='ADQ'))
-- 755,190 / 854,023 filas
-- 00:40 sec

/*===================================== PROCESO 10 ==============================================
	Retirar duplicados de MARGUESI/FEC_COMPRA en la tabla Stage.StgMaestroTerminales_RedPOS
=================================================================================================*/ 
IF OBJECT_ID('Stage.StgMaestroTerminales_RedPOS') IS NOT NULL
BEGIN
	TRUNCATE TABLE Stage.StgMaestroTerminales_RedPOS;
	DROP TABLE Stage.StgMaestroTerminales_RedPOS;
END;

SELECT 
	A.[COMERCIO],
	A.[ADQ/C.COR],
	A.[NOMBRE],
	A.[RUBRO],
	A.[SITUACION],
	A.[CATEGORIA],
	A.[RAZON_SOCIAL],
	A.[RUC],
	A.[DIRECCION],
	A.[DEPARTAMENTO],
	A.[PROVINCIA],
	A.[DISTRITO],
	A.[MULTICOMERCIO],
	A.[TELEFONO_COMERCIO],
	A.[CONTACTO],
	A.[PERFIL_COMERCIO],
	A.[PERFIL_DESCARGA],
	A.[TERMINAL],
	A.[SERIE],
	A.[MEDIO_MCC],
	A.[MEDIO],
	A.[DESCRIPCION_TERMINAL],
	A.[FECHA_ULTIMO_ECO],
	A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA],
	A.[FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA],
	A.[SITUACION_TERMINAL],
	A.[MODELO],
	A.[MODELO_MCC],
	A.[VERSION_SWB],
	A.[OS_VERSION],
	A.[CHIP],
	A.[TELEFONO_CHIP],
	A.[OPERADOR],
	A.[ESTADO_COMERCIO],
	A.[ESTADO_LOGICO_COMERCIO],
	A.[ESTADO_TERMINAL],
	A.[ESTADO_LOGICO_TERMINAL],
	A.[APLICACION],
	A.[APL_DESC],
	A.[FACTURACION],
	A.[dTrE105SN],
	A.[VERSION_FLUJO],
	A.[VERSION_MAIN],
	A.SERIE_COMPLETA,
	A.[MARCA],
	A.[FLG_PCI],
	A.[SW_CTLS],
	A.[HW_CTLS],
	A.[PRE_AUTORIZACION_NIVEL_COMERCIO],
	A.[PRE_AUTORIZACION_NIVEL_TERMINAL],
	A.[DIGITACION_MANUAL_NIVEL_COMERCIO],
	A.[DIGITACION_MANUAL_NIVEL_TERMINAL],
	A.[PROPINA],
	A.[FECHA_ACTUALIZACION_APP],
	A.[HORA_ACTUALIZACION_APP],
	A.[NUM_INTENTOS],
	A.[FECHA_ULTIMA_ACTUALIZACION],
	A.[HORA_ULTIMA_ACTUALIZACION],
	A.[VERSION_ACTUALIZADO],
	A.[cTAFilesVersion],
	A.[cVrVersionId],
	A.[cTAVersionApl],
	A.[dVrFile],
	MIN(A.[Marguesi]) 'Marguesi',
	MIN(A.[FEC_COMPRA]) 'FEC_COMPRA',
	MIN(A.[SITUACION_AS400]) 'SITUACION_AS400',
	A.[EMV_DINERS],
	A.[CANT_TERM],
	A.[CANT_TERM_ACT],
	A.[FLG_PINPAD],
	A.[FLG_MULTICOMERCIO],
	A.[GIRO],
	A.SERIE_UNICA,
	A.[GRUPO_ECONOMICO],
	A.[FECAPE],
	A.[COSECHA],
	A.[OFICINA],
	A.[MODELO_TERMINAL],
	A.[VERSION_BASE],
	MIN(B.[MDFERE]) 'FEC_INST',
	A.[COD_MADRE],
	A.[COD_DOL],
	@FECHA as [FEC_PROC],	-- Modifyed by TR9656 | Agregar fecha de proceso
	ROW_NUMBER ( ) OVER ( ORDER BY A.[COMERCIO] ) as [ROW_NUM]	-- Modifyed by TR9656 | Agregar conteo de comercios.
INTO Stage.StgMaestroTerminales_RedPOS
FROM #MAESTRO_TERMINALES_3 A
	LEFT JOIN [RAW].[MCFV030E] B ON (CAST(B.MDTERM as CHAR(4)) <> '9999' AND A.SERIE_COMPLETA=B.MDSERM AND LEFT(A.COMERCIO,7)=CAST(B.MDCOCO as VARCHAR(9)))
GROUP BY 
	A.[COMERCIO],
	A.[ADQ/C.COR],
	A.[NOMBRE],
	A.[RUBRO],
	A.[SITUACION],
	A.[CATEGORIA],
	A.[RAZON_SOCIAL],
	A.[RUC],
	A.[DIRECCION],
	A.[DEPARTAMENTO],
	A.[PROVINCIA],
	A.[DISTRITO],
	A.[MULTICOMERCIO],
	A.[TELEFONO_COMERCIO],
	A.[CONTACTO],
	A.[PERFIL_COMERCIO],
	A.[PERFIL_DESCARGA],
	A.[TERMINAL],
	A.[SERIE],
	A.[MEDIO_MCC],
	A.[MEDIO],
	A.[DESCRIPCION_TERMINAL],
	A.[FECHA_ULTIMO_ECO],
	A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA],
	A.[FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA],
	A.[SITUACION_TERMINAL],
	A.[MODELO],
	A.[MODELO_MCC],
	A.[VERSION_SWB],
	A.[OS_VERSION],
	A.[CHIP],
	A.[TELEFONO_CHIP],
	A.[OPERADOR],
	A.[ESTADO_COMERCIO],
	A.[ESTADO_LOGICO_COMERCIO],
	A.[ESTADO_TERMINAL],
	A.[ESTADO_LOGICO_TERMINAL],
	A.[APLICACION],
	A.[APL_DESC],
	A.[FACTURACION],
	A.[dTrE105SN],
	A.[VERSION_FLUJO],
	A.[VERSION_MAIN],
	A.SERIE_COMPLETA,
	A.[MARCA],
	A.[FLG_PCI],
	A.[SW_CTLS],
	A.[HW_CTLS],
	A.[PRE_AUTORIZACION_NIVEL_COMERCIO],
	A.[PRE_AUTORIZACION_NIVEL_TERMINAL],
	A.[DIGITACION_MANUAL_NIVEL_COMERCIO],
	A.[DIGITACION_MANUAL_NIVEL_TERMINAL],
	A.[PROPINA],
	A.[FECHA_ACTUALIZACION_APP],
	A.[HORA_ACTUALIZACION_APP],
	A.[NUM_INTENTOS],
	A.[FECHA_ULTIMA_ACTUALIZACION],
	A.[HORA_ULTIMA_ACTUALIZACION],
	A.[VERSION_ACTUALIZADO],
	A.[cTAFilesVersion],
	A.[cVrVersionId],
	A.[cTAVersionApl],
	A.[dVrFile],
	A.[EMV_DINERS],
	A.[CANT_TERM],
	A.[CANT_TERM_ACT],
	A.[FLG_PINPAD],
	A.[FLG_MULTICOMERCIO],
	A.[GIRO],
	A.SERIE_UNICA,
	A.[GRUPO_ECONOMICO],
	A.[FECAPE],
	A.[COSECHA],
	A.[OFICINA],
	A.[MODELO_TERMINAL],
	A.[VERSION_BASE],
	A.[COD_MADRE],
	A.[COD_DOL]
-- 853,994 filas
-- 00:37 sec
/*===================================== PROCESO 11 ==============================================
	se agrega el segmento
=================================================================================================*/ 

IF OBJECT_ID('TempDB..#StgMaestroTerminales_RedPOS_segmento') IS NOT NULL
BEGIN
	TRUNCATE TABLE #StgMaestroTerminales_RedPOS_segmento;
	DROP TABLE #StgMaestroTerminales_RedPOS_segmento;
END;

with periodo_max as 
(
	select  
		max(periodo) as periodo
	from dwh.segmentacion
), segmento as
(
	select 
		codigo,
		segmento
	from dwh.segmentacion a
	inner join periodo_max b on (a.periodo = b.periodo)
	group by codigo,segmento
)
select 
	a.*,
	case 
		when segmento = 'CORP' then '01. CORPORACIONES'
		when segmento = 'NEG' then '02. NEGOCIOS'
		when segmento = 'RETAIL' then '03. RETAIL'
		else '04. -' end as segmento
	into #StgMaestroTerminales_RedPOS_segmento
from Stage.StgMaestroTerminales_RedPOS a 
left join segmento b on (left(a.COMERCIO,7) = b.codigo)
; 


IF OBJECT_ID('Stage.StgMaestroTerminales_RedPOS') IS NOT NULL
BEGIN
	TRUNCATE TABLE Stage.StgMaestroTerminales_RedPOS;
	DROP TABLE Stage.StgMaestroTerminales_RedPOS;
END;

select *
into Stage.StgMaestroTerminales_RedPOS
from #StgMaestroTerminales_RedPOS_segmento

------ Borrado de tablas temporales ------ 
DROP TABLE #SERIES_UNICAS
DROP TABLE #MAESTRO_TERMINALES_2
DROP TABLE #MAESTRO_TERMINALES_3
DROP TABLE #StgMaestroTerminales_RedPOS_segmento
/*--------------------------------------------------------------------------------------*/ 
END
