	/****** Object:  StoredProcedure [Stage].[usp_GeneraStgMaestroTerminales_05]    Script Date: 5/29/2025 4:29:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [Stage].[usp_GeneraStgMaestroTerminales_05] AS
BEGIN

/*============================================================================================= 
Autor					:Business Analytics SAC
Fecha creación			:2021/04/12
Objetivos				:Agrega los campos QR_CRC, QR_CRC_Pendiente,CV_LIMIT_150
Ejecutar				:EXECUTE [Stage].[usp_GeneraStgMaestroTerminales_05]
Observaciones			:
Comentarios				:Este SP es equivalente a 
							S4_P12_Update_QR
===============================================================================================*/ 
/*====================================== PROCESO 0 ============================================ 
							Definición de variables temporales 
===============================================================================================*/ 
DECLARE @fecIniLog DATETIME;
SET @fecIniLog			= DATEADD(HOUR,-5,GETDATE());
/*====================================== PROCESO 1 ============================================ 
							Comprobación de tablas temporales
===============================================================================================*/ 

IF OBJECT_ID('TempDB..#TEMP') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMP;
	DROP TABLE #TEMP;
END;

/*====================================== PROCESO 2 ============================================ 
					Agrega los campos QR_CRC, QR_CRC_Pendiente,CV_LIMIT_150
===============================================================================================*/ 


SELECT *
	  ,CASE

	  /* ADQUIRIENTE */
		WHEN PERFIL_DESCARGA='TELECARGA_PMP_QR_CRC'
			AND PERFIL_COMERCIO IN ('POS_UNICO_QR','POS_UNICODOL_QR','POS_PROPINA_QR')
			AND VERSION_FLUJO='348'
			AND VERSION_MAIN='351' 
			AND VERSION_SWB IN ('B8.652', 'B80510','B80511') THEN '0.Actualizado con QR activo'
		WHEN PERFIL_DESCARGA='ADQUIRIENTE_PMP_QR'
			AND PERFIL_COMERCIO IN ('POS_UNICO_QR','POS_UNICODOL_QR','POS_PROPINA_QR')
			AND VERSION_FLUJO='345'
			AND VERSION_MAIN='241'
			AND VERSION_SWB IN ('B8.652', 'B80510','B80511') THEN '0.Actualizado con QR activo'

		WHEN PERFIL_DESCARGA='TELECARGA_PMP_QR_CRC'
			AND VERSION_FLUJO='348'
			AND VERSION_MAIN='351' 
			AND MODELO = 'IZI SMART'
			AND VERSION_SWB NOT IN ('B80511','B80510') THEN '2.En proceso de actualización'		

		WHEN PERFIL_DESCARGA='TELECARGA_PMP_QR_CRC'
			AND VERSION_FLUJO='348'
			AND VERSION_MAIN='351'
			AND VERSION_SWB IN ('B8.652', 'B80510','B80511') THEN '1.Actualizado sin QR activo'
		WHEN PERFIL_DESCARGA='ADQUIRIENTE_PMP_QR'
			AND VERSION_FLUJO='345'
			AND VERSION_MAIN='241'
			AND VERSION_SWB IN ('B8.652', 'B80510','B80511') THEN '1.Actualizado sin QR activo'

	  /* ADQUIRIENTE */

	  /* FACILITADOR */
	  /* HABILITADO QR */

		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR_CRC'
			AND PERFIL_COMERCIO IN ('IZIPAY_QR','IZIPAY_TIP_QR','IZIPAY_DOL_QR','IZIPAY_TPDOL_QR')
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='350'
			AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN '0.Actualizado con QR activo'
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR'
			AND PERFIL_COMERCIO IN ('IZIPAY_QR','IZIPAY_TIP_QR','IZIPAY_DOL_QR','IZIPAY_TPDOL_QR')
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='343'
			AND VERSION_SWB='I8.652' THEN '0.Actualizado con QR activo'
		WHEN PERFIL_DESCARGA='IZIPAY'
			AND PERFIL_COMERCIO IN ('IZIPAY_QR','IZIPAY_TIP_QR','IZIPAY_DOL_QR','IZIPAY_TPDOL_QR')
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='241'
			AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN '0.Actualizado con QR activo'
		WHEN PERFIL_DESCARGA='IZIPAY_QR'
			AND PERFIL_COMERCIO IN ('IZIPAY_QR','IZIPAY_TIP_QR','IZIPAY_DOL_QR','IZIPAY_TPDOL_QR')
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='241'
			AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN '0.Actualizado con QR activo'
	   /* HABILITADO QR */

		/* INICIO PARCHE PARA NO DEJAR MAL A CESAR */
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR_CRC'
			AND VERSION_FLUJO <>'346'
			AND VERSION_MAIN <>'350' THEN '2.En proceso de actualización'	
	
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR_CRC'
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='350' 
			AND MODELO = 'IZI'
			AND VERSION_SWB NOT IN ('B80409','B80410') THEN '2.En proceso de actualización'	
			
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR_CRC'
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='350' 
			AND MODELO = 'IZI SMART'
			AND VERSION_SWB NOT IN ('B80511','B80510') THEN '2.En proceso de actualización'				
		/* FIN PARCHE PARA NO DEJAR MAL A CESAR */

		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR_CRC'
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='350'
			AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN '1.Actualizado sin QR activo'
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR'
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='343'
			AND VERSION_SWB='I8.652' THEN '1.Actualizado sin QR activo'
		WHEN PERFIL_DESCARGA='IZIPAY'
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='241'
			AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN '1.Actualizado sin QR activo'
		WHEN PERFIL_DESCARGA='IZIPAY_QR'
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='241'
			AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN '1.Actualizado sin QR activo'

		/* INICIO PARCHE PARA NO DEJAR MAL A JUAN */		
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_F11'
			THEN '2.En proceso de actualización'		
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_F21'
			THEN '2.En proceso de actualización'	
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_F28_1'
			THEN '2.En proceso de actualización'	
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_F25'
			THEN '2.En proceso de actualización'	
		WHEN PERFIL_DESCARGA='TELECARGA_ IZIPAY_F27'
			THEN '2.En proceso de actualización'		
		WHEN PERFIL_DESCARGA='IZIPAY_QR'
			THEN '2.En proceso de actualización'	
		/* FIN PARCHE PARA NO DEJAR MAL A JUAN */

		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR_CRC'
			THEN '2.En proceso de actualización'	
		WHEN PERFIL_DESCARGA='TELECARGA_PMP_QR_CRC'
			THEN '2.En proceso de actualización'	

		ELSE '3.Pendientes de actualizar'
	  END 'QR_CRC'
	/* LOS NO ACTUALIZADOS */
	  ,CASE
	  /* ADQUIRIENTE */
		WHEN PERFIL_DESCARGA='TELECARGA_PMP_QR_CRC'
			AND PERFIL_COMERCIO IN ('POS_UNICO_QR','POS_UNICODOL_QR','POS_PROPINA_QR')
			AND VERSION_FLUJO='348'
			AND VERSION_MAIN='351' 
			AND VERSION_SWB IN ('B8.652', 'B80510','B80511') THEN '0.Actualizado con QR activo'
		WHEN PERFIL_DESCARGA='ADQUIRIENTE_PMP_QR'
			AND PERFIL_COMERCIO IN ('POS_UNICO_QR','POS_UNICODOL_QR','POS_PROPINA_QR')
			AND VERSION_FLUJO='345'
			AND VERSION_MAIN='241'
			AND VERSION_SWB IN ('B8.652', 'B80510','B80511') THEN '0.Actualizado con QR activo'

		WHEN PERFIL_DESCARGA='TELECARGA_PMP_QR_CRC'
			AND VERSION_FLUJO='348'
			AND VERSION_MAIN='351' 
			AND MODELO = 'IZI SMART'
			AND VERSION_SWB NOT IN ('B80511','B80510') THEN '2.3.Pendiente error 6%'	

		WHEN PERFIL_DESCARGA='TELECARGA_PMP_QR_CRC'
			AND VERSION_FLUJO='348'
			AND VERSION_MAIN='351'
			AND VERSION_SWB IN ('B8.652', 'B80510','B80511') THEN '1.Actualizado sin QR activo'
		WHEN PERFIL_DESCARGA='ADQUIRIENTE_PMP_QR'
			AND VERSION_FLUJO='345'
			AND VERSION_MAIN='241'
			AND VERSION_SWB IN ('B8.652', 'B80510','B80511') THEN '1.Actualizado sin QR activo'

	  /* ADQUIRIENTE */

	   /* HABILITADO QR */
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR_CRC'
			AND PERFIL_COMERCIO IN ('IZIPAY_QR','IZIPAY_TIP_QR','IZIPAY_DOL_QR','IZIPAY_TPDOL_QR')
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='350'
			AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN '0.Actualizado con QR activo'
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR'
			AND PERFIL_COMERCIO IN ('IZIPAY_QR','IZIPAY_TIP_QR','IZIPAY_DOL_QR','IZIPAY_TPDOL_QR')
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='343'
			AND VERSION_SWB='I8.652' THEN '0.Actualizado con QR activo'
		WHEN PERFIL_DESCARGA='IZIPAY'
			AND PERFIL_COMERCIO IN ('IZIPAY_QR','IZIPAY_TIP_QR','IZIPAY_DOL_QR','IZIPAY_TPDOL_QR')
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='241'
			AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN '0.Actualizado con QR activo'
		WHEN PERFIL_DESCARGA='IZIPAY_QR'
			AND PERFIL_COMERCIO IN ('IZIPAY_QR','IZIPAY_TIP_QR','IZIPAY_DOL_QR','IZIPAY_TPDOL_QR')
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='241'
			AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN '0.Actualizado con QR activo'
	   /* HABILITADO QR */

		/* INICIO PARCHE PARA NO DEJAR MAL A CESAR */
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR_CRC'
			AND VERSION_FLUJO <>'346'
			AND VERSION_MAIN <>'350' THEN '2.4.POS pendientes de descarga, pos no encendido'	
		
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR_CRC'
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='350' 
			AND MODELO = 'IZI'
			AND VERSION_SWB NOT IN ('B80409','B80410') THEN '2.3.Pendiente error 6%'
			
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR_CRC'
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='350' 
			AND MODELO = 'IZI SMART'
			AND VERSION_SWB NOT IN ('B80511','B80510') THEN '2.3.Pendiente error 6%'			

		/* FIN PARCHE PARA NO DEJAR MAL A CESAR */

		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR_CRC'
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='350'
			AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN '1.Actualizado sin QR activo'
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR'
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='343'
			AND VERSION_SWB='I8.652' THEN '1.Actualizado sin QR activo'
		WHEN PERFIL_DESCARGA='IZIPAY'
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='241'
			AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN '1.Actualizado sin QR activo'
		WHEN PERFIL_DESCARGA='IZIPAY_QR'
			AND VERSION_FLUJO='346'
			AND VERSION_MAIN='241'
			AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN '1.Actualizado sin QR activo'

		WHEN PERFIL_DESCARGA='TELECARGA_PMP_QR_CRC'
			AND VERSION_FLUJO <>'348'
			AND VERSION_MAIN <>'351' THEN '2.4.POS pendientes de descarga, pos no encendido'

		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR_CRC'
			THEN '2.1.Actualizaciones en curso'	
		WHEN PERFIL_DESCARGA='TELECARGA_PMP_QR_CRC'
			THEN '2.1.Actualizaciones en curso'	

		/* EN PROCESO DE ACTUALIZACION PASO 1 */		
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_F11'
		AND VERSION_SWB IN ('B80410','B80511','B80409','B80510')
			THEN '2.2.2.Pendiente de segunda descarga'	
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_F21'
		AND VERSION_SWB IN ('B80410','B80511','B80409','B80510')
			THEN '2.2.2.Pendiente de segunda descarga'	
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_F28_1'
		AND VERSION_SWB IN ('B80410','B80511','B80409','B80510')
			THEN '2.2.2.Pendiente de segunda descarga'		
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_F25'
		AND VERSION_SWB IN ('B80410','B80511','B80409','B80510')
			THEN '2.2.2.Pendiente de segunda descarga'	
		WHEN PERFIL_DESCARGA='TELECARGA_ IZIPAY_F27'
		AND VERSION_SWB IN ('B80410','B80511','B80409','B80510')
			THEN '2.2.2.Pendiente de segunda descarga'			
		WHEN PERFIL_DESCARGA='IZIPAY_QR'
		AND VERSION_SWB IN ('B80410','B80511','B80409','B80510')
			THEN '2.2.2.Pendiente de segunda descarga'	
		/* EN PROCESO DE ACTUALIZACION PASO 1 */
		
		
		/* EN PROCESO DE ACTUALIZACION PASO 1 */		
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_F11'
		AND VERSION_SWB NOT IN ('B80410','B80511','B80409','B80510')
			THEN '2.2.1.Pendiente de primera descarga'		
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_F21'
		AND VERSION_SWB NOT IN ('B80410','B80511','B80409','B80510')
			THEN '2.2.1.Pendiente de primera descarga'		
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_F28_1'
		AND VERSION_SWB NOT IN ('B80410','B80511','B80409','B80510')
			THEN '2.2.1.Pendiente de primera descarga'			
		WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_F25'
		AND VERSION_SWB NOT IN ('B80410','B80511','B80409','B80510')
			THEN '2.2.1.Pendiente de primera descarga'			
		WHEN PERFIL_DESCARGA='TELECARGA_ IZIPAY_F27'
		AND VERSION_SWB NOT IN ('B80410','B80511','B80409','B80510')
			THEN '2.2.1.Pendiente de primera descarga'				
		WHEN PERFIL_DESCARGA='IZIPAY_QR'
		AND VERSION_SWB NOT IN ('B80410','B80511','B80409','B80510')
			THEN '2.2.1.Pendiente de primera descarga'		
		/* EN PROCESO DE ACTUALIZACION PASO 1 */

		ELSE '5.Pendiente'
	END 'QR_CRC_Pendiente'
	,CASE
		--WHEN PERFIL_DESCARGA='TELECARGA_CV_LIMIT_150'
		--	AND VERSION_FLUJO='333'
		--	AND VERSION_MAIN='342' THEN 'Actualizado'
		--WHEN PERFIL_DESCARGA='TELECARGA_PMP_QR'
		--	AND VERSION_FLUJO='345'
		--	AND VERSION_MAIN='336' THEN 'Actualizado'
		--WHEN PERFIL_DESCARGA='TELECARGA_PMP_QR_CRC'
		--	AND VERSION_FLUJO='348'
		--	AND VERSION_MAIN='351' THEN 'Actualizado'
		--WHEN PERFIL_DESCARGA='ADQUIRIENTE_PMP_QR'
		--	AND VERSION_FLUJO='345'
		--	AND VERSION_MAIN='241'
		--	AND VERSION_SWB IN ('B8.652','B80510', 'B80511') THEN 'Actualizado'
		--WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR'
		--	AND VERSION_FLUJO='346'
		--	AND VERSION_MAIN='343' THEN 'Actualizado'
		--WHEN PERFIL_DESCARGA='TELECARGA_IZIPAY_QR_CRC'
		--	AND VERSION_FLUJO='346'
		--	AND VERSION_MAIN='350' THEN 'Actualizado'
		--WHEN PERFIL_DESCARGA='IZIPAY'
		--	AND VERSION_FLUJO='346'
		--	AND VERSION_MAIN='241'
		--	AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN 'Actualizado'
		--WHEN PERFIL_DESCARGA='IZIPAY_QR'
		--	AND VERSION_FLUJO='346'
		--	AND VERSION_MAIN='241'
		--	AND VERSION_SWB IN ('I8.652','B80410','B80511','B80409','B80510') THEN '1.Actualizado sin QR activo'
		--ELSE 'Pendiente'
		WHEN VERSION_SWB IN (
			'B8.652',
			'B80407',
			'B80408',
			'B80409',
			'B80410',
			'B80508',
			'B80509',
			'B80510',
			'B80511',
			'B9.114',
			'B9.124',
			'I8.652') THEN 'Actualizado'
		WHEN PERFIL_DESCARGA='TELECARGA_PMP_QR_CRC' THEN 'Enviado a Telecargar'
		ELSE 'Pendiente'
	END 'CV_LIMIT_150'
INTO #TEMP
  FROM [Stage].[StgMaestroTerminales]

IF OBJECT_ID('Stage.StgMaestroTerminales') IS NOT NULL
	BEGIN
		TRUNCATE TABLE [Stage].[StgMaestroTerminales];
		DROP TABLE 	[Stage].[StgMaestroTerminales];
	END

SELECT * INTO [Stage].[StgMaestroTerminales] FROM #TEMP



/*====================================== PROCESO 3 ============================================ 
							Eliminación de tablas temporales
===============================================================================================*/ 

IF OBJECT_ID('TempDB..#TEMP') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMP;
	DROP TABLE #TEMP;
END;

--drop table #TEMP

--ALTER TABLE [Stage].[StgMaestroTerminales]
--DROP COLUMN CV_LIMIT_150;

--ALTER TABLE [Stage].[StgMaestroTerminales]
--DROP COLUMN QR_CRC_Pendiente;

--ALTER TABLE [Stage].[StgMaestroTerminales]
--DROP COLUMN QR_CRC;

INSERT INTO Stage.stglog (Fuente,Tabla,Cantidad,FechaINicio,FechaFIN)
SELECT 'Actualiza BI_Maestro_Terminales - Paso 6/8','BI_Maestro_Terminales',0,@fecIniLog,DATEADD(HOUR,5,GETDATE());

END
