/****** Object:  StoredProcedure [Stage].[usp_GeneraStgMaestroTerminales_01]    Script Date: 5/29/2025 4:01:02 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [Stage].[usp_GeneraStgMaestroTerminales_01] AS
BEGIN

/*============================================================================================= 
Autor					:Business Analytics SAC
Fecha creación			:2021/04/12
Objetivos				:Generar la tabla [Stage].[StgMaestroTerminales]
Ejecutar				:EXECUTE [Stage].[usp_GeneraStgMaestroTerminales_01]
Observaciones			:Se renombró el campo [ADQ/C.COR] a [ADQ_C_COR] 
Comentarios				:Este SP es equivalente a 
							S4_P02_CreacionTabla
===============================================================================================*/ 
/*====================================== PROCESO 0 ============================================ 
							Definición de variables temporales 
===============================================================================================*/ 
DECLARE @fecIniLog DATETIME;
SET @fecIniLog			= DATEADD(HOUR,-5,GETDATE());
/*====================================== PROCESO 1 ============================================ 
								  Definición de Variables
===============================================================================================*/ 

DECLARE @FECHA CHAR(8)

SET @FECHA = (SELECT MAX([FECHA_ULTIMA_TRANSACCION_FINANCIERA]) FROM [Stage].[StgTerminalA])

/*====================================== PROCESO 2 ============================================ 
							 Comprobación de tablas temporales
===============================================================================================*/ 

IF OBJECT_ID('TempDB..#TEMPORAL_0') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMPORAL_0;
	DROP TABLE #TEMPORAL_0;
END;

IF OBJECT_ID('TempDB..#TEMPORAL_1') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMPORAL_1;
	DROP TABLE #TEMPORAL_1;
END;

IF OBJECT_ID('TempDB..#TEMPORAL_2') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMPORAL_2;
	DROP TABLE #TEMPORAL_2;
END;

/*===================================== PROCESO 3 =============================================
							Carga de la tabla [Stage].[StgMaestroTerminales]
===============================================================================================*/ 


IF OBJECT_ID('Stage.StgMaestroTerminales') IS NOT NULL
	BEGIN
		TRUNCATE TABLE [Stage].[StgMaestroTerminales];
		DROP TABLE 	[Stage].[StgMaestroTerminales];
	END

SELECT
    RTRIM(LTRIM(A.[COMERCIO])) COMERCIO
	,CASE
		WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[PERFIL_COMERCIO] LIKE '%IZIPAY%' THEN 'ADQ-IZIPAY'
		WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[NOMBRE] LIKE '%IZI%' THEN 'ADQ-IZIPAY'
		ELSE CAST('ADQ-PMP' AS VARCHAR(11))
	END AS 'ADQ_C_COR',
	RTRIM(LTRIM(A.[NOMBRE])) 'NOMBRE',RTRIM(LTRIM(A.[RUBRO])) 'RUBRO',RTRIM(LTRIM(A.[RUC])) 'RUC',RTRIM(LTRIM(A.[DIRECCION])) 'DIRECCION',
	RTRIM(LTRIM(A.[DEPARTAMENTO])) 'DEPARTAMENTO',RTRIM(LTRIM(A.[PROVINCIA])) 'PROVINCIA',RTRIM(LTRIM(A.[DISTRITO])) 'DISTRITO',
	RTRIM(LTRIM(A.[MULTICOMERCIO])) 'MULTICOMERCIO',RTRIM(LTRIM(A.[TELEFONO_COMERCIO])) 'TELEFONO_COMERCIO',RTRIM(LTRIM(A.[CONTACTO])) 'CONTACTO',
	RTRIM(LTRIM(A.[PERFIL_COMERCIO])) 'PERFIL_COMERCIO',RTRIM(LTRIM(A.[PERFIL_DESCARGA])) 'PERFIL_DESCARGA',RTRIM(LTRIM(A.[TERMINAL])) 'TERMINAL',
	RTRIM(LTRIM(A.[SERIE])) 'SERIE', RTRIM(LTRIM(A.[MEDIO])) 'MEDIO_MCC'
	,CASE 
		WHEN case charindex('_',RTRIM(LTRIM(A.[MODELO])))
				when 0 then RTRIM(LTRIM(A.[MODELO]))
				else left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)
				end IN ('IWL250','VX680','C680','IWL220','MOVE5000','LINK2500') THEN 'GPRS Movil'
		WHEN RTRIM(LTRIM(A.[MEDIO])) = 'ETHERNET' THEN 'IP'
		WHEN RTRIM(LTRIM(A.[MEDIO])) = 'DIAL' THEN 'DIAL'
		WHEN RTRIM(LTRIM(A.[CHIP])) <> '' THEN 'GPRS Fijo'
		WHEN case charindex('_',RTRIM(LTRIM(A.[MODELO])))
			when 0 then RTRIM(LTRIM(A.[MODELO]))
			else left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1) end IN ('VX810','VX820','P400') THEN 'PINPAD'
		WHEN A.dTrE105SN <> '' THEN 'mPOS'
		ELSE  'IP'
	END 'MEDIO'
	,RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) 'DESCRIPCION_TERMINAL'
	,RTRIM(LTRIM(A.[FECHA_ULTIMO_ECO]))'FECHA_ULTIMO_ECO',RTRIM(LTRIM(A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA])) 'FECHA_ULTIMA_TRANSACCION_FINANCIERA'
	,RTRIM(LTRIM(A.[FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA])) 'FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA'
	,case 
		when datediff(month,cast([FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>12 then '2 - Sin movimiento ultimos 12 meses.'
		when datediff(month,cast([FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>6 then '6 - Sin movimiento ultimos 6 meses.'
		when datediff(month,cast([FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>3 then '4 - Sin movimiento ultimos 3 meses.'
		when datediff(month,cast([FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>=0 then '1 - Con movimiento en los ultimos 3 meses.'
		else '2 - Sin movimiento ultimos 12 meses.'
	end 'SITUACION_TERMINAL'
	,case charindex('_',RTRIM(LTRIM(A.[MODELO])))
		when 0 then
			CASE 

			-- MODELOS IZIPAY
			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[PERFIL_COMERCIO] LIKE '%IZIPAY%' AND A.dTrE105SN<>'' THEN 'IZI JR'
			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[NOMBRE] LIKE '%IZI%' AND A.dTrE105SN<>'' THEN 'IZI JR'

			WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'IZI'

			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[PERFIL_COMERCIO] LIKE '%IZIPAY%' AND RTRIM(LTRIM(A.[MODELO]))='C680' THEN 'IZI PRINT'
			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[NOMBRE] LIKE '%IZI%' AND RTRIM(LTRIM(A.[MODELO]))='C680' THEN 'IZI PRINT'
		
			WHEN RTRIM(LTRIM(A.[MODELO]))='MOVE5000' THEN 'IZI SMART'

			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[PERFIL_COMERCIO] LIKE '%IZIPAY%' THEN 'OTROS'
			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[NOMBRE] LIKE '%IZI%' THEN 'OTROS'

			-- MODELOS IZIPAY
			WHEN LEFT(RTRIM(LTRIM(A.[MODELO])),1)='I' THEN 'Ingenico - '+RTRIM(LTRIM(A.[MODELO]))
			WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'Ingenico - '+RTRIM(LTRIM(A.[MODELO]))
			WHEN RTRIM(LTRIM(A.[MODELO]))='C680' THEN 'Verifone - '+RTRIM(LTRIM(A.[MODELO]))
			WHEN RTRIM(LTRIM(A.[MODELO]))='VX520C' THEN 'Verifone - '+RTRIM(LTRIM(A.[MODELO]))
			WHEN A.[MODELO] LIKE '%VX820%' THEN 'Verifone - VX820'
			WHEN RTRIM(LTRIM(A.[MODELO])) IN ('ClienteAD','ClienteIPH') THEN
															CASE
															WHEN RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) LIKE '%MPOS%' THEN 'Verifone - E105'
															WHEN RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) LIKE '%WISEPAD%' THEN 'WISEPAD'
															WHEN RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) LIKE '%PAD%' THEN 'WISEPAD'
															WHEN RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) LIKE '%105%' THEN 'Verifone - E105'
															WHEN RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) LIKE '%POS%' THEN 'Verifone - E105'
															ELSE RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL]))
															END
			ELSE RTRIM(LTRIM(A.[MODELO]))
			END 
		else 
			CASE 

			-- MODELOS IZIPAY
			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[PERFIL_COMERCIO] LIKE '%IZIPAY%' AND A.dTrE105SN<>'' THEN 'IZI JR'
			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[NOMBRE] LIKE '%IZI%' AND A.dTrE105SN<>'' THEN 'IZI JR'
			WHEN A.[MODELO] LIKE '%VX820%' THEN 'Verifone - VX820'
			WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'IZI'

			WHEN RTRIM(LTRIM(A.[MODELO]))='C680' THEN 'IZI PRINT'
		
			WHEN RTRIM(LTRIM(A.[MODELO]))='MOVE5000' THEN 'IZI SMART'

			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[PERFIL_COMERCIO] LIKE '%IZIPAY%' THEN 'OTROS'
			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[NOMBRE] LIKE '%IZI%' THEN 'OTROS'

			-- MODELOS IZIPAY
			WHEN LEFT(RTRIM(LTRIM(A.[MODELO])),1)='I' THEN 'Ingenico - '+left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)
			WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'Ingenico - '+left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)
			ELSE left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)
			END 
	end 'MODELO'
	,RTRIM(LTRIM(A.[MODELO])) 'MODELO_MCC'
	,RTRIM(LTRIM(A.[VERSION_SWB])) 'VERSION_SWB',RTRIM(LTRIM(A.[OS_VERSION])) 'OS_VERSION',RTRIM(LTRIM(A.[CHIP])) 'CHIP',
	RTRIM(LTRIM(A.[TELEFONO_CHIP])) 'TELEFONO_CHIP'
	,CASE LEFT(RTRIM(LTRIM(A.CHIP)),6)
		WHEN '893407' THEN 'MOVISTAR-SM'
		WHEN '895106' THEN 'MOVISTAR'
		WHEN '895110' THEN 'CLARO'
		WHEN '895117' THEN 'ENTEL'
		WHEN '895115' THEN 'BITEL'
		ELSE ''
		END 'OPERADOR'
	,RTRIM(LTRIM(A.[ESTADO_COMERCIO])) 'ESTADO_COMERCIO',
	RTRIM(LTRIM(A.[ESTADO_LOGICO_COMERCIO])) 'ESTADO_LOGICO_COMERCIO',RTRIM(LTRIM(A.[ESTADO_TERMINAL])) 'ESTADO_TERMINAL',
	RTRIM(LTRIM(A.[ESTADO_LOGICO_TERMINAL])) 'ESTADO_LOGICO_TERMINAL',RTRIM(LTRIM(A.[APLICACION])) 'APLICACION',RTRIM(LTRIM(B.[ADQUIRIENTE])) 'APL_DESC',
	RTRIM(LTRIM(A.[FACTURACION])) 'FACTURACION',RTRIM(LTRIM(A.[dTrE105SN])) 'dTrE105SN',RTRIM(LTRIM(A.[VERSION_FLUJO])) 'VERSION_FLUJO',
	RTRIM(LTRIM(A.[VERSION_MAIN])) 'VERSION_MAIN'
	,CASE WHEN dTrE105SN<>'' THEN RTRIM(LTRIM(A.[dTrE105SN]))	ELSE RTRIM(LTRIM(A.[SERIE_COMPLETA])) END  'SERIE_COMPLETA'
	,CASE 
		WHEN LEFT(RTRIM(LTRIM(A.[MODELO])),1)='I' THEN 'Ingenico'
		WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'Ingenico'
		WHEN RTRIM(LTRIM(A.[MODELO]))='MOVE5000' THEN 'Ingenico'
		WHEN RTRIM(LTRIM(A.[MODELO])) IN ('ClienteAD','ClienteIPH') THEN 'OTROS'
		ELSE 'Verifone'
		END 'MARCA'
    ,case charindex('_',A.[MODELO])
		when 0 then
			CASE 
				WHEN RTRIM(LTRIM(A.[MODELO]))='VX510' THEN 'PRE PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='VX610' THEN 'PRE PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='VX810' THEN 'PRE PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='OMNI3750' THEN 'PRE PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO])) IN ('ClienteAD','ClienteIPH') THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[VERSION_SWB])) IN ('B8.001','B8.002','B8.003','B8.012','B8.013','B8.014','B8.015',
					'B8.017','B8.018','B8.019','B8.022','B8.100','B8.110','B8.111','B8.114',
					'B8.306','B8.401','B8.420','B8.423','B8.460') THEN 'PRE PCI'
				WHEN LEFT(RTRIM(LTRIM(A.[MODELO])),1)='I' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO])) LIKE '%PCI%' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='P400' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO])) in ('LINK2500','MOVE5000') THEN 'PCI'
				ELSE 'NO PCI'
				END 
		else 
			CASE 
				WHEN left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)='VX510' THEN 'PRE PCI'
				WHEN left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)='VX610' THEN 'PRE PCI'
				WHEN left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)='VX810' THEN 'PRE PCI'
				WHEN left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)='OMNI3750' THEN 'PRE PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO])) IN ('ClienteAD','ClienteIPH') THEN 'PCI'
				WHEN LEFT(RTRIM(LTRIM(A.[MODELO])),1)='I' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO])) LIKE '%PCI%' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='P400'  THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO])) in ('LINK2500','MOVE5000') THEN 'PCI'
				ELSE 'NO PCI'
				END 
	end 'FLG_PCI'
	,CASE 
		WHEN CAST(CASE WHEN A.[VERSION_FLUJO]='' THEN 0 ELSE A.[VERSION_FLUJO] END AS numeric)>244 AND A.[VERSION_SWB] NOT IN ('B7.854','B8.001','B8.002','B8.003','B8.012','B8.013',
		'B8.014','B8.015','B8.017','B8.018','B8.019','B8.022','B8.100','B8.110','B8.111','B8.114','B8.306','B8.401','B8.420',
		'B8.423','B8.460','B8.463','B8.464','B8.481','B8.4815','B80106','B80107','B80108','B80112','B80113','B80114','B80115',
		'B80117','B80118','B80119')	THEN '1.POS con App CTLS'
		WHEN RTRIM(LTRIM(A.[MODELO]))='P400'  THEN '1.POS con App CTLS'
		WHEN RTRIM(LTRIM(A.[MODELO])) in ('LINK2500','MOVE5000') THEN '1.POS con App CTLS'
		ELSE '2.POS sin App CTLS'
	END 'SW_CTLS'
	,CASE
		WHEN A.[MODELO] LIKE '%10%' THEN '2.POS sin HW CTLS'		
		ELSE '1.POS con HW CTLS'
	END [HW_CTLS]
	,A.[PRE_AUTORIZACION_NIVEL_COMERCIO]
	,A.[PRE_AUTORIZACION_NIVEL_TERMINAL]
	,A.[DIGITACION_MANUAL_NIVEL_COMERCIO]
	,A.[DIGITACION_MANUAL_NIVEL_TERMINAL]
	,A.[PROPINA]
	,A.[FECHA_ACTUALIZACION_APP]
	,A.[HORA_ACTUALIZACION_APP]
	,A.[NUM_INTENTOS]
	,A.[FECHA_ULTIMA_ACTUALIZACION]
	,A.[HORA_ULTIMA_ACTUALIZACION]
	,A.[VERSION_ACTUALIZADO]
	,A.[cTAFilesVersion]
	,A.[cVrVersionId]
	,A.[cTAVersionApl]
	,A.[dVrFile]
INTO [Stage].[StgMaestroTerminales]
FROM [Stage].[StgTerminalA] A
LEFT JOIN [RAW].[APLICACION_RP] B
ON A.APLICACION=B.POS
WHERE LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)<>'3';




ALTER TABLE [Stage].[StgMaestroTerminales]
ALTER COLUMN [ADQ_C_COR] VARCHAR(1000);




INSERT INTO [Stage].[StgMaestroTerminales]
SELECT 
    RTRIM(LTRIM(A.[COMERCIO])) COMERCIO
	,CASE
		WHEN A.[PERFIL_DESCARGA] LIKE '%IZIPAY%' THEN 'C.COR-IZIPAY'
		WHEN A.[NOMBRE] LIKE 'IZI%' THEN 'C.COR-IZIPAY'
		ELSE CAST('C.COR-PMP' AS VARCHAR(11))
	END AS 'ADQ_C_COR',
	RTRIM(LTRIM(A.[NOMBRE])) 'NOMBRE',RTRIM(LTRIM(A.[RUBRO])) 'RUBRO',RTRIM(LTRIM(A.[RUC])) 'RUC',RTRIM(LTRIM(A.[DIRECCION])) 'DIRECCION',
	RTRIM(LTRIM(A.[DEPARTAMENTO])) 'DEPARTAMENTO',RTRIM(LTRIM(A.[PROVINCIA])) 'PROVINCIA',RTRIM(LTRIM(A.[DISTRITO])) 'DISTRITO',
	RTRIM(LTRIM(A.[MULTICOMERCIO])) 'MULTICOMERCIO',RTRIM(LTRIM(A.[TELEFONO_COMERCIO])) 'TELEFONO_COMERCIO',RTRIM(LTRIM(A.[CONTACTO])) 'CONTACTO',
	RTRIM(LTRIM(A.[PERFIL_COMERCIO])) 'PERFIL_COMERCIO',RTRIM(LTRIM(A.[PERFIL_DESCARGA])) 'PERFIL_DESCARGA',RTRIM(LTRIM(A.[TERMINAL])) 'TERMINAL',
	RTRIM(LTRIM(A.[SERIE])) 'SERIE', RTRIM(LTRIM(A.[MEDIO])) 'MEDIO_MCC'
	,CASE 
		WHEN case charindex('_',RTRIM(LTRIM(A.[MODELO])))
				when 0 then RTRIM(LTRIM(A.[MODELO]))
				else left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)
				end IN ('IWL250','VX680','C680','IWL220','MOVE5000','LINK2500') THEN 'GPRS Movil'
		WHEN RTRIM(LTRIM(A.[MEDIO])) = 'ETHERNET' THEN 'IP'
		WHEN RTRIM(LTRIM(A.[MEDIO])) = 'DIAL' THEN 'DIAL'
		WHEN RTRIM(LTRIM(A.[CHIP])) <> '' THEN 'GPRS Fijo'
		WHEN case charindex('_',RTRIM(LTRIM(A.[MODELO])))
			when 0 then RTRIM(LTRIM(A.[MODELO]))
			else left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1) end IN ('VX810','VX820','P400') THEN 'PINPAD'
		WHEN A.dTrE105SN <> '' THEN 'mPOS'
		ELSE  'IP'
	END 'MEDIO'
	,RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) 'DESCRIPCION_TERMINAL',
	RTRIM(LTRIM(A.[FECHA_ULTIMO_ECO]))'FECHA_ULTIMO_ECO',RTRIM(LTRIM(A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA])) 'FECHA_ULTIMA_TRANSACCION_FINANCIERA',
	RTRIM(LTRIM(A.[FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA])) 'FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA'
	,case 
		when datediff(month,cast([FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>12 then '2 - Sin movimiento ultimos 12 meses.'
		when datediff(month,cast([FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>6 then '6 - Sin movimiento ultimos 6 meses.'
		when datediff(month,cast([FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>3 then '4 - Sin movimiento ultimos 3 meses.'
		when datediff(month,cast([FECHA_ULTIMA_TRANSACCION_FINANCIERA] as datetime),cast(@FECHA as datetime))>=0 then '1 - Con movimiento en los ultimos 3 meses.'
		else '2 - Sin movimiento ultimos 12 meses.'
	end 'SITUACION_TERMINAL'
	,case charindex('_',RTRIM(LTRIM(A.[MODELO])))
		when 0 then
			CASE 

			-- MODELOS IZIPAY
			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[PERFIL_COMERCIO] LIKE '%IZIPAY%' AND A.dTrE105SN <>'' THEN 'IZI JR'
			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[NOMBRE] LIKE '%IZI%' AND A.dTrE105SN <>'' THEN 'IZI JR'

			WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'IZI'

			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[PERFIL_COMERCIO] LIKE '%IZIPAY%' AND RTRIM(LTRIM(A.[MODELO]))='C680' THEN 'IZI PRINT'
			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[NOMBRE] LIKE '%IZI%' AND RTRIM(LTRIM(A.[MODELO]))='C680' THEN 'IZI PRINT'
		
			WHEN RTRIM(LTRIM(A.[MODELO]))='MOVE5000' THEN 'IZI SMART'

			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[PERFIL_COMERCIO] LIKE '%IZIPAY%' THEN 'OTROS'
			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[NOMBRE] LIKE '%IZI%' THEN 'OTROS'

			-- MODELOS IZIPAY
			WHEN LEFT(RTRIM(LTRIM(A.[MODELO])),1)='I' THEN 'Ingenico - '+RTRIM(LTRIM(A.[MODELO]))
			WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'Ingenico - '+RTRIM(LTRIM(A.[MODELO]))
			WHEN RTRIM(LTRIM(A.[MODELO]))='C680' THEN 'Verifone - '+RTRIM(LTRIM(A.[MODELO]))
			WHEN RTRIM(LTRIM(A.[MODELO]))='VX520C' THEN 'Verifone - '+RTRIM(LTRIM(A.[MODELO]))
			WHEN A.[MODELO] LIKE '%VX820%' THEN 'Verifone - VX820'
			WHEN RTRIM(LTRIM(A.[MODELO])) IN ('ClienteAD','ClienteIPH') THEN
															CASE
															WHEN RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) LIKE '%MPOS%' THEN 'Verifone - E105'
															WHEN RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) LIKE '%WISEPAD%' THEN 'WISEPAD'
															WHEN RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) LIKE '%PAD%' THEN 'WISEPAD'
															WHEN RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) LIKE '%105%' THEN 'Verifone - E105'
															WHEN RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL])) LIKE '%POS%' THEN 'Verifone - E105'
															ELSE RTRIM(LTRIM(A.[DESCRIPCION_TERMINAL]))
															END
			ELSE RTRIM(LTRIM(A.[MODELO]))
			END 
		else 
			CASE 

			-- MODELOS IZIPAY
			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[PERFIL_COMERCIO] LIKE '%IZIPAY%' AND A.dTrE105SN <>'' THEN 'IZI JR'
			WHEN LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='8' AND A.[NOMBRE] LIKE '%IZI%' AND A.dTrE105SN <>'' THEN 'IZI JR'
			WHEN A.[MODELO] LIKE '%VX820%' THEN 'Verifone - VX820'
			WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'IZI'

			WHEN RTRIM(LTRIM(A.[MODELO]))='C680' THEN 'IZI PRINT'
		
			WHEN RTRIM(LTRIM(A.[MODELO]))='MOVE5000' THEN 'IZI SMART'

			-- MODELOS IZIPAY
			WHEN LEFT(RTRIM(LTRIM(A.[MODELO])),1)='I' THEN 'Ingenico - '+left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)
			WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'Ingenico - '+left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)
			ELSE left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)
			END 
	end 'MODELO'
	,RTRIM(LTRIM(A.[MODELO])) 'MODELO_MCC',
	RTRIM(LTRIM(A.[VERSION_SWB])) 'VERSION_SWB',RTRIM(LTRIM(A.[OS_VERSION])) 'OS_VERSION',RTRIM(LTRIM(A.[CHIP])) 'CHIP',
	RTRIM(LTRIM(A.[TELEFONO_CHIP])) 'TELEFONO_CHIP'
	,CASE LEFT(RTRIM(LTRIM(A.CHIP)),6)
		WHEN '893407' THEN 'MOVISTAR-SM'
		WHEN '895106' THEN 'MOVISTAR'
		WHEN '895110' THEN 'CLARO'
		WHEN '895117' THEN 'ENTEL'
		WHEN '895115' THEN 'BITEL'
		ELSE ''
		END 'OPERADOR'
	,RTRIM(LTRIM(A.[ESTADO_COMERCIO])) 'ESTADO_COMERCIO',
	RTRIM(LTRIM(A.[ESTADO_LOGICO_COMERCIO])) 'ESTADO_LOGICO_COMERCIO',RTRIM(LTRIM(A.[ESTADO_TERMINAL])) 'ESTADO_TERMINAL',
	RTRIM(LTRIM(A.[ESTADO_LOGICO_TERMINAL])) 'ESTADO_LOGICO_TERMINAL',RTRIM(LTRIM(A.[APLICACION])) 'APLICACION',RTRIM(LTRIM(B.[ADQUIRIENTE])) 'APL_DESC',
	RTRIM(LTRIM(A.[FACTURACION])) 'FACTURACION',RTRIM(LTRIM(A.[dTrE105SN])) 'dTrE105SN',RTRIM(LTRIM(A.[VERSION_FLUJO])) 'VERSION_FLUJO',
	RTRIM(LTRIM(A.[VERSION_MAIN])) 'VERSION_MAIN', RTRIM(LTRIM(A.[SERIE_COMPLETA])) AS 'SERIE_COMPLETA'
	,CASE 
		WHEN LEFT(RTRIM(LTRIM(A.[MODELO])),1)='I' THEN 'Ingenico'
		WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'Ingenico'
		WHEN RTRIM(LTRIM(A.[MODELO]))='MOVE5000' THEN 'Ingenico'
		WHEN RTRIM(LTRIM(A.[MODELO])) IN ('ClienteAD','ClienteIPH') THEN 'OTROS'
		ELSE 'Verifone'
	END 'MARCA'
    ,case charindex('_',A.[MODELO])
		when 0 then
			CASE 
				WHEN RTRIM(LTRIM(A.[MODELO]))='VX510' THEN 'PRE PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='VX610' THEN 'PRE PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='VX810' THEN 'PRE PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='OMNI3750' THEN 'PRE PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO])) IN ('ClienteAD','ClienteIPH') THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[VERSION_SWB])) IN ('B8.001','B8.002','B8.003','B8.012','B8.013','B8.014','B8.015',
					'B8.017','B8.018','B8.019','B8.022','B8.100','B8.110','B8.111','B8.114',
					'B8.306','B8.401','B8.420','B8.423','B8.460') THEN 'PRE PCI'
				WHEN LEFT(RTRIM(LTRIM(A.[MODELO])),1)='I' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO])) LIKE '%PCI%' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='P400' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO])) in ('LINK2500','MOVE5000') THEN 'PCI'
				ELSE 'NO PCI'
				END 
		else 
			CASE 
				WHEN left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)='VX510' THEN 'PRE PCI'
				WHEN left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)='VX610' THEN 'PRE PCI'
				WHEN left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)='VX810' THEN 'PRE PCI'
				WHEN left(RTRIM(LTRIM(A.[MODELO])),charindex('_',RTRIM(LTRIM(A.[MODELO])))-1)='OMNI3750' THEN 'PRE PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='LINK2500' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO])) IN ('ClienteAD','ClienteIPH') THEN 'PCI'
				WHEN LEFT(RTRIM(LTRIM(A.[MODELO])),1)='I' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO])) LIKE '%PCI%' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO]))='P400' THEN 'PCI'
				WHEN RTRIM(LTRIM(A.[MODELO])) in ('LINK2500','MOVE5000') THEN 'PCI'
				ELSE 'NO PCI'
				END 
	end 'FLG_PCI'
	,CASE 
		WHEN CAST(CASE WHEN A.[VERSION_FLUJO]='' THEN 0 ELSE A.[VERSION_FLUJO] END AS numeric)>244 AND A.[VERSION_SWB] NOT IN ('B7.854','B8.001','B8.002','B8.003','B8.012','B8.013',
		'B8.014','B8.015','B8.017','B8.018','B8.019','B8.022','B8.100','B8.110','B8.111','B8.114','B8.306','B8.401','B8.420',
		'B8.423','B8.460','B8.463','B8.464','B8.481','B8.4815','B80106','B80107','B80108','B80112','B80113','B80114','B80115',
		'B80117','B80118','B80119')	THEN '1.POS con App CTLS'
		WHEN RTRIM(LTRIM(A.[MODELO]))='P400'  THEN '1.POS con App CTLS'
		WHEN RTRIM(LTRIM(A.[MODELO])) in ('LINK2500','MOVE5000') THEN '1.POS con App CTLS'
		ELSE '2.POS sin App CTLS'
	END 'SW_CTLS'
	,CASE
		WHEN A.[MODELO] LIKE '%10%' THEN '2.POS sin HW CTLS'		
		ELSE '1.POS con HW CTLS'
	END [HW_CTLS]
	,A.[PRE_AUTORIZACION_NIVEL_COMERCIO]
	,A.[PRE_AUTORIZACION_NIVEL_TERMINAL]
	,A.[DIGITACION_MANUAL_NIVEL_COMERCIO]
	,A.[DIGITACION_MANUAL_NIVEL_TERMINAL]
	,A.[PROPINA]
	,A.[FECHA_ACTUALIZACION_APP]
	,A.[HORA_ACTUALIZACION_APP]
	,A.[NUM_INTENTOS]
	,A.[FECHA_ULTIMA_ACTUALIZACION]
	,A.[HORA_ULTIMA_ACTUALIZACION]
	,A.[VERSION_ACTUALIZADO]
	,A.[cTAFilesVersion]
	,A.[cVrVersionId]
	,A.[cTAVersionApl]
	,A.[dVrFile]
FROM [Stage].[StgTerminalCc] A
LEFT JOIN [RAW].[APLICACION_RP] B
ON A.APLICACION=B.POS
WHERE LEFT(RTRIM(LTRIM(A.[COMERCIO])),1)='3';




-- PARCHES

-- MODELOS
UPDATE [Stage].[StgMaestroTerminales]
SET MODELO = 'Verifone - MX925'
WHERE MODELO='MX925';

UPDATE [Stage].[StgMaestroTerminales]
SET MODELO = 'Verifone - VX510'
WHERE MODELO='VX510';

UPDATE [Stage].[StgMaestroTerminales]
SET MODELO = 'Verifone - VX520'
WHERE MODELO='VX520';

--UPDATE [Stage].[StgMaestroTerminales]
--SET MODELO = 'Verifone - VX520'
--WHERE MODELO='VX520';

UPDATE [Stage].[StgMaestroTerminales]
SET MODELO = 'Verifone - VX610'
WHERE MODELO='VX610';

UPDATE [Stage].[StgMaestroTerminales]
SET MODELO = 'Verifone - VX670'
WHERE MODELO='VX670';

UPDATE [Stage].[StgMaestroTerminales]
SET MODELO = 'Verifone - VX680'
WHERE MODELO='VX680';

UPDATE [Stage].[StgMaestroTerminales]
SET MODELO = 'Verifone - VX810'
WHERE MODELO='VX810';

UPDATE [Stage].[StgMaestroTerminales]
SET MODELO = 'Verifone - VX820'
WHERE MODELO='VX820';

-- FECHAS EN BLANCO // FECHA_ULTIMO_ECO
UPDATE [Stage].[StgMaestroTerminales]
SET FECHA_ULTIMO_ECO = ''
WHERE ltrim(rtrim(FECHA_ULTIMO_ECO))='';

-- FECHA_ULTIMA_TRANSACCION_FINANCIERA
UPDATE [Stage].[StgMaestroTerminales]
SET FECHA_ULTIMA_TRANSACCION_FINANCIERA = ''
WHERE ltrim(rtrim(FECHA_ULTIMA_TRANSACCION_FINANCIERA))='';

-- FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA
UPDATE [Stage].[StgMaestroTerminales]
SET FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA = ''
WHERE ltrim(rtrim(FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA))='';

-- ICT250
UPDATE [Stage].[StgMaestroTerminales]
SET [MODELO]='Ingenico - ICT220'
WHERE [MODELO]='Ingenico - ICT250';

-- C680
UPDATE [Stage].[StgMaestroTerminales]
SET FLG_PCI='PCI'
WHERE MODELO='Verifone - C680';

-- 520C
UPDATE [Stage].[StgMaestroTerminales]
SET FLG_PCI='PCI'
WHERE MODELO='Verifone - VX520C';

-- PinPad
UPDATE [Stage].[StgMaestroTerminales]
SET MEDIO='PINPAD'
WHERE MODELO in ('Verifone - VX810','Verifone - VX820','Verifone - MX925','Verifone - MX915');

-- V240M
UPDATE [Stage].[StgMaestroTerminales]
SET FLG_PCI='PCI'
WHERE MODELO='V240M';

-- D200
UPDATE [Stage].[StgMaestroTerminales]
SET FLG_PCI='PCI',
	MODELO='PAX - D200'
WHERE MODELO_MCC='D200';

---- REGULARIZACIÓN CTLS
UPDATE A
SET 
	  [SW_CTLS]='1.POS no CTLS'
      ,[HW_CTLS]='2.POS sin HW CTLS'
FROM [Stage].[StgMaestroTerminales] A
WHERE EXISTS ( SELECT 1 FROM [RAW].[520_NO_CTLS_RP] B WHERE A.SERIE=B.SERIE)
AND MODELO='Verifone - VX520';

UPDATE A
SET 
	  [SW_CTLS]='1.POS no CTLS'
FROM [Stage].[StgMaestroTerminales] A
WHERE A.[HW_CTLS]='2.POS sin HW CTLS'


UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [SW_CTLS]='2.POS sin App CTLS'
WHERE [ADQ_C_COR]='C.COR'
AND [HW_CTLS]='2.POS sin HW CTLS';

UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [SW_CTLS]='1.POS con App CTLS'
WHERE [MODELO]='Verifone - MX925';

UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [SW_CTLS]='2.POS sin App CTLS'
WHERE CAST(CASE WHEN [VERSION_FLUJO]='' THEN 0 ELSE [VERSION_FLUJO] END AS numeric)='284';

UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [SW_CTLS]='2.POS sin App CTLS'
WHERE CAST(CASE WHEN [VERSION_FLUJO]='' THEN 0 ELSE [VERSION_FLUJO] END AS numeric)='285';

UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [SW_CTLS]='2.POS sin App CTLS'
WHERE CAST(CASE WHEN [VERSION_FLUJO]='' THEN 0 ELSE [VERSION_FLUJO] END AS numeric)='286';

UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [SW_CTLS]='2.POS sin App CTLS'
WHERE [FLG_PCI]='NO PCI';

UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [SW_CTLS]='2.POS sin App CTLS'
WHERE [FLG_PCI]='PRE PCI';

--- INICIO IZIPAY

-- IZI JR
UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [SW_CTLS]='2.POS sin App CTLS'
	  ,[HW_CTLS]='1.POS con HW CTLS'
	  ,[FLG_PCI]='PCI'
	  ,[MODELO]='IZI JR'
	  ,[MARCA]='DSPREAD'
	  ,[MEDIO]='mPOS'
WHERE [ADQ_C_COR]='ADQ-IZIPAY'
AND [dTrE105SN] <>'';

UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [SW_CTLS]='2.POS sin App CTLS'
	  ,[HW_CTLS]='1.POS con HW CTLS'
	  ,[FLG_PCI]='PCI'
	  ,[MARCA]='DSPREAD'
	  ,[MEDIO]='mPOS'
WHERE [ADQ_C_COR]='ADQ-IZIPAY'
AND [MODELO]='IZI JR';



ALTER TABLE [Stage].[StgMaestroTerminales]
ALTER COLUMN [SW_CTLS] VARCHAR(1000);




-- IZI
UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [SW_CTLS]='2.POS con App CTLS MC'
	  ,[HW_CTLS]='1.POS con HW CTLS'
	  ,[FLG_PCI]='PCI'
	  ,[MARCA]='Ingenico'
	  ,[MEDIO]='GPRS Movil'
WHERE [ADQ_C_COR]='ADQ-IZIPAY'
AND [MODELO]='IZI'
AND [VERSION_SWB] IN ('B80205','B80300','B80301');

UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [SW_CTLS]='2.POS con App CTLS MC+VISA'
	  ,[HW_CTLS]='1.POS con HW CTLS'
	  ,[FLG_PCI]='PCI'
	  ,[MARCA]='Ingenico'
	  ,[MEDIO]='GPRS Movil'
WHERE [ADQ_C_COR]='ADQ-IZIPAY'
AND [MODELO]='IZI'
AND [VERSION_SWB] NOT IN ('B80205','B80300','B80301');

-- IZI PRINT
UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [SW_CTLS]='2.POS con App CTLS MC'
	  ,[HW_CTLS]='1.POS con HW CTLS'
	  ,[FLG_PCI]='PCI'
	  ,[MARCA]='Verifone'
	  ,[MEDIO]='GPRS Movil'
WHERE [ADQ_C_COR]='ADQ-IZIPAY'
AND [MODELO]='IZI PRINT';

-- IZI SMART
UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [SW_CTLS]='2.POS con App CTLS MC+VISA'
	  ,[HW_CTLS]='1.POS con HW CTLS'
	  ,[FLG_PCI]='PCI'
	  ,[MARCA]='Ingenico'
	  ,[MEDIO]='GPRS Movil'
WHERE [ADQ_C_COR]='ADQ-IZIPAY'
AND [MODELO]='IZI SMART';

UPDATE [Stage].[StgMaestroTerminales]
SET 
	  [MEDIO]='mPOS'
WHERE MEDIO IS NULL
AND [ADQ_C_COR]='ADQ-IZIPAY'

-- CONSOLIDADO
UPDATE A
SET A.CHIP=RTRIM(LTRIM(B.CHIP))
	,A.OPERADOR =
	CASE LEFT(RTRIM(LTRIM(B.CHIP)),6)
		WHEN '893407' THEN 'MOVISTAR-SM'
		WHEN '895106' THEN 'MOVISTAR'
		WHEN '895110' THEN 'CLARO'
		WHEN '895117' THEN 'ENTEL'
		WHEN '895115' THEN 'BITEL'
		ELSE ''
		END 
FROM [Stage].[StgMaestroTerminales] A
LEFT JOIN [RAW].[CONSOLIDADO_RP] B
ON (RTRIM(LTRIM(A.SERIE))=RIGHT(REPLACE(RTRIM(LTRIM([Numero se Serie])),'-',''),8) AND B.CHIP <>'')
WHERE A.[ADQ_C_COR]='ADQ-IZIPAY'
AND A.OPERADOR =''

-- UPDATE ENTEL SIM MANAGER

UPDATE [Stage].[StgMaestroTerminales]
SET OPERADOR ='ENTEL_SM'
WHERE RTRIM(LTRIM(CHIP)) IN (SELECT RTRIM(LTRIM([ICCID])) FROM [RAW].[ENTEL_RP])
AND RTRIM(LTRIM(CHIP))<>'';




-- AGREGA SEGMENTACION

SELECT A.[COMERCIO]
      ,A.[ADQ_C_COR]
      ,A.[NOMBRE]
      ,A.[RUBRO]
      ,isnull(B.[SITUACION],'') 'SITUACION'
	  ,CASE 
		WHEN B.CTA_ESPECIAL='G' AND A.[ADQ_C_COR] LIKE 'ADQ%' THEN '1. GRANDES EMPRESAS'
		WHEN B.CTA_ESPECIAL='E' AND A.[ADQ_C_COR] LIKE 'ADQ%' THEN '2. EMPRESAS'
		WHEN A.[ADQ_C_COR]='C.COR-PMP' AND A.[APL_DESC]='BANCO NACION' THEN '4. BANCO NACION'
		WHEN A.[ADQ_C_COR]='C.COR-PMP' AND A.[APL_DESC]='CMAC AREQUIPA' THEN '5. CMAC AREQUIPA'
		WHEN A.[ADQ_C_COR]='C.COR-PMP' AND A.[APL_DESC]='CMAC HUANCAYO' THEN '6. CMAC HUANCAYO'
		WHEN A.[ADQ_C_COR]='C.COR-PMP' AND A.[APL_DESC]='INTERBANK' THEN '7. INTERBANK'
		WHEN A.[ADQ_C_COR]='C.COR-PMP' AND A.[APL_DESC]='SCOTIABANK' THEN '8. SCOTIABANK'
		WHEN A.[ADQ_C_COR]='C.COR-PMP' AND A.APLICACION='CMICA' THEN '9. CMAC ICA'
		ELSE '3. NEGOCIOS'
		END 'CATEGORIA'
	  ,isnull(B.GRUPO_ECO_DESC,'') 'GRUPO_ECO_DESC'
	  ,isnull(B.RAZON_SOCIAL,'') 'RAZON_SOCIAL'
	  ,isnull(B.RUC,'') 'RUC'
      ,A.[DIRECCION]
      ,A.[DEPARTAMENTO]
      ,A.[PROVINCIA]
      ,A.[DISTRITO]
      ,A.[MULTICOMERCIO]
      ,A.[TELEFONO_COMERCIO]
      ,A.[CONTACTO]
      ,A.[PERFIL_COMERCIO]
      ,A.[PERFIL_DESCARGA]
      ,A.[TERMINAL]
      ,A.[SERIE]
      ,A.[MEDIO_MCC]
      ,A.[MEDIO]
      ,A.[DESCRIPCION_TERMINAL]
      ,A.[FECHA_ULTIMO_ECO]
      ,A.[FECHA_ULTIMA_TRANSACCION_FINANCIERA]
      ,A.[FECHA_ULTIMA_TRANSACCION_ADMINISTRATIVA]
	  ,A.[SITUACION_TERMINAL]
      ,A.[MODELO]
      ,A.[MODELO_MCC]
      ,A.[VERSION_SWB]
      ,A.[OS_VERSION]
      ,A.[CHIP]
      ,A.[TELEFONO_CHIP]
      ,A.[OPERADOR]
      ,A.[ESTADO_COMERCIO]
      ,A.[ESTADO_LOGICO_COMERCIO]
      ,A.[ESTADO_TERMINAL]
      ,A.[ESTADO_LOGICO_TERMINAL]
      ,A.[APLICACION]
      ,A.[APL_DESC]
      ,A.[FACTURACION]
      ,A.[dTrE105SN]
      ,A.[VERSION_FLUJO]
      ,A.[VERSION_MAIN]
      ,A.[SERIE_COMPLETA]
      ,A.[MARCA]
      ,A.[FLG_PCI]
      ,A.[SW_CTLS]
      ,A.[HW_CTLS]
	  ,A.[PRE_AUTORIZACION_NIVEL_COMERCIO]
	  ,A.[PRE_AUTORIZACION_NIVEL_TERMINAL]
	  ,A.[DIGITACION_MANUAL_NIVEL_COMERCIO]
	  ,A.[DIGITACION_MANUAL_NIVEL_TERMINAL]
	  ,A.[PROPINA]
	  ,A.[FECHA_ACTUALIZACION_APP]
	  ,A.[HORA_ACTUALIZACION_APP]
	  ,A.[NUM_INTENTOS]
	  ,A.[FECHA_ULTIMA_ACTUALIZACION]
	  ,A.[HORA_ULTIMA_ACTUALIZACION]
	  ,A.[VERSION_ACTUALIZADO]
	  ,A.[cTAFilesVersion]
	  ,A.[cVrVersionId]
	  ,A.[cTAVersionApl]
	  ,A.[dVrFile]
INTO #TEMPORAL_0	  
FROM [Stage].[StgMaestroTerminales] A
LEFT JOIN [RAW].[SEGMENTO_RP] B
ON LEFT(RTRIM(LTRIM(A.COMERCIO)),7)=LEFT(RTRIM(LTRIM(B.COMERCIO)),7);

IF OBJECT_ID('Stage.StgMaestroTerminales') IS NOT NULL
	BEGIN
		TRUNCATE TABLE [Stage].[StgMaestroTerminales];
		DROP TABLE 	[Stage].[StgMaestroTerminales];
	END
	
SELECT *
INTO [Stage].[StgMaestroTerminales]
FROM #TEMPORAL_0;





-- OBTENIENDO MARGUESI Y FEC_COMPRA

SELECT A.SERIE
	,MAX(B.MARGUESI) MARGUESI
	,MAX(B.FEC_COMPRA) FEC_COMPRA
INTO #TEMPORAL_1
FROM [Stage].[StgMaestroTerminales] A
LEFT JOIN [Stage].StgTerminalAS400 B
ON RTRIM(LTRIM(A.SERIE))=RIGHT(RTRIM(LTRIM(B.[SERIE_POS])),8)  AND B.MARCA <> 'DSPREAD' AND UPPER(A.MARCA)=B.MARCA
GROUP BY SERIE




-- ACTUALIZANDO SITUACIÓN y SEGMENTACION
UPDATE A
SET	A.[SITUACION]=B.[situac]
FROM [Stage].[StgMaestroTerminales] A
  LEFT JOIN stage.StgMcestab B
  ON LEFT(LTRIM(RTRIM(A.COMERCIO)),7)=LTRIM(RTRIM(B.[codigo]))
  WHERE B.[situac] IS NOT NULL
  AND B.situac<>''
  AND B.[codigo] IS NOT NULL;

UPDATE A
SET	A.[RUBRO]=B.[mcc]
FROM [Stage].[StgMaestroTerminales] A
  LEFT JOIN stage.StgMcestab B
  ON LEFT(LTRIM(RTRIM(A.COMERCIO)),7)=LTRIM(RTRIM(B.[codigo]))
  WHERE B.[situac] IS NOT NULL
  AND B.mcc <>''
  AND B.[codigo] IS NOT NULL;
  
UPDATE A
SET	A.RUC=B.[nroruc]
FROM [Stage].[StgMaestroTerminales] A
  LEFT JOIN stage.StgMcestab B
  ON LEFT(LTRIM(RTRIM(A.COMERCIO)),7)=LTRIM(RTRIM(B.[codigo]))
  WHERE B.[situac] IS NOT NULL
  AND B.[nroruc] <>''
  AND B.[codigo] IS NOT NULL;


UPDATE A
SET	A.[CATEGORIA]= CASE
					WHEN B.[CTA_ESP]='N' THEN '3. NEGOCIOS'
					WHEN B.[CTA_ESP]='E' THEN '2. EMPRESAS'
					WHEN B.[CTA_ESP]='G' THEN '1. GRANDES EMPRESAS'
					ELSE A.[CATEGORIA]
					END 
FROM [Stage].[StgMaestroTerminales] A
  LEFT JOIN stage.StgMcestab B
  ON LEFT(LTRIM(RTRIM(A.COMERCIO)),7)=LTRIM(RTRIM(B.[codigo]))
  WHERE B.[codigo] IS NOT NULL
  AND B.cta_esp IN ('N','E','G')
  AND A.[ADQ_C_COR] NOT LIKE '%C.COR%';

  


-- TERMINALES DE BAJA
SELECT A.*
	,isnull(B.MARGUESI,'') 'MARGUESI'
	,isnull(B.FEC_COMPRA,'') 'FEC_COMPRA'
 	,CASE
		WHEN A.[ADQ_C_COR] LIKE '%IZIPAY%' AND B.MARGUESI IS NULL THEN 'VENDIDO'
		WHEN A.[ADQ_C_COR] LIKE '%PMP%' AND B.MARGUESI IS NULL THEN 'BAJA'
		ELSE 'ACTIVO'
	END SITUACION_AS400
INTO #TEMPORAL_2
FROM [Stage].[StgMaestroTerminales] A
LEFT JOIN #TEMPORAL_1 B
ON A.SERIE=B.SERIE

IF OBJECT_ID('Stage.StgMaestroTerminales') IS NOT NULL
	BEGIN
		TRUNCATE TABLE [Stage].[StgMaestroTerminales];
		DROP TABLE 	[Stage].[StgMaestroTerminales];
	END
	
SELECT *
INTO [Stage].[StgMaestroTerminales]
FROM #TEMPORAL_2;




UPDATE [Stage].[StgMaestroTerminales]
SET CHIP = ''
WHERE COMERCIO ='142881090000';



/*====================================== PROCESO 4 ============================================ 
								Eliminacion de tablas temporales
===============================================================================================*/ 

IF OBJECT_ID('TempDB..#TEMPORAL_0') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMPORAL_0;
	DROP TABLE #TEMPORAL_0;
END;

IF OBJECT_ID('TempDB..#TEMPORAL_1') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMPORAL_1;
	DROP TABLE #TEMPORAL_1;
END;

IF OBJECT_ID('TempDB..#TEMPORAL_2') IS NOT NULL
BEGIN
	TRUNCATE TABLE #TEMPORAL_2;
	DROP TABLE #TEMPORAL_2;
END;

-- RUBRO

-- MOVIMIENTO POS

-- MOVIMIENTO COMERCIO

-- MULTICOMERCIOS

-- OBSERVACIONES

-- CAMPO CON CARACTERES EXTRAÑOS

INSERT INTO Stage.stglog (Fuente,Tabla,Cantidad,FechaINicio,FechaFIN)
SELECT 'Carga BI_Maestro_Terminales - Paso 2/8','BI_Maestro_Terminales',0,@fecIniLog,DATEADD(HOUR,5,GETDATE());

END

