CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_dataentry_operaciones.rol500_incoming (
network STRING  OPTIONS(description='Red de procesamiento (e.g., BASE II, VisaNet).'),
exception_transaction STRING  OPTIONS(description='Tipo de transacción de excepción (e.g., Dispute Financial).'),
settle_date STRING  OPTIONS(description='Fecha de liquidación de la transacción.'),
delivery_time STRING  OPTIONS(description='Tiempo o fecha de entrega del caso o mensaje (puede venir como n/a).'),
member_case STRING  OPTIONS(description='Número de caso asignado por el miembro (banco emisor o adquirente).'),
rol_case STRING  OPTIONS(description='Número de caso generado en la plataforma VROL.'),
pvc_id STRING  OPTIONS(description='Número de tarjeta o cuenta asociada a la transacción.'),
amount STRING  OPTIONS(description='Monto original de la transacción.'),
cr_dr STRING  OPTIONS(description='Indicador de crédito (CR) o débito (DR).'),
curr_code STRING  OPTIONS(description='Código de la moneda utilizada en la transacción (por ejemplo: 604 = Soles).'),
rc STRING  OPTIONS(description='Código de razón o respuesta (puede estar vacío o ser interno).'),
tran_id STRING  OPTIONS(description='Identificador único de la transacción en el sistema.'),
arn STRING  OPTIONS(description='Acquirer Reference Number – identificador global único de la transacción.'),
merchant_name STRING  OPTIONS(description='Nombre del comercio donde se efectuó la transacción.'),
user BYTES  OPTIONS(description='Usuario o sistema que ingresó la transacción (puede venir vacío).'),
trn STRING  OPTIONS(description='Código interno de transacción o tracking (puede variar según red).'),
jurisdiction STRING  OPTIONS(description='Jurisdicción de la transacción (ej. "Visa - Domestic - PE").'),
atm_ind STRING  OPTIONS(description='Indicador de si fue una transacción ATM (Yes/No).'),
pvc_id_alternativo STRING  OPTIONS(description='Identificador alternativo del "PVC" seguro para la transacción. (Ocurre cuando se realizaron los pagos con google pay o apple pay)'),
dispute_category STRING  OPTIONS(description='Categoría del contracargo (ej. código 10 = bienes/servicios no recibidos).'),
dispute_category_condition STRING  OPTIONS(description='Subcategoría o condición específica del contracargo.'),
vrol_financial_id STRING  OPTIONS(description='ID financiero del caso en la plataforma VROL.'),
vrol_bundle_case STRING  OPTIONS(description='Agrupación o ID de bundle del caso en VROL.'),
inter_fee_amount STRING  OPTIONS(description='Monto de comisión internacional aplicada a la transacción.'),
inter_fee_dr_cr STRING  OPTIONS(description='Indicador de débito o crédito sobre la comisión internacional.'),
inter_fee_currency STRING  OPTIONS(description='Moneda de la comisión internacional.'),
dispute_status STRING  OPTIONS(description='Código del estado actual del caso de disputa.'),
dispute_status_description STRING  OPTIONS(description='Descripción del estado actual del caso (ej. “Dispute Financial”).'),
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date TIMESTAMP NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD'),
PRIMARY KEY (pvc_id, arn) NOT ENFORCED
)
PARTITION BY process_date
OPTIONS (description='Tabla que contiene las transacciones que entran a un proceso de contracargos ("Contracargo en primera etapa") provenientes del reporte Visa Rol500, el cual contiene la conciliación financiera de transacciones');
