CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.master_risk.t_contracargo_visa_rol500 (
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
red STRING  OPTIONS(description='Red de procesamiento (e.g., BASE II, VisaNet).'),
tipo_contracargo STRING  OPTIONS(description='Tipo o clasificación del contracargo (ej. "CC Único").'),
tipo_trx_excepcion STRING  OPTIONS(description='Tipo de transacción de excepción (e.g., Dispute Financial).'),
fecha_liquidacion DATE  OPTIONS(description='Fecha de liquidación de la transacción.'),
fecha_entrega DATETIME  OPTIONS(description='Tiempo o fecha de entrega del caso o mensaje (puede venir como n/a).'),
num_caso STRING  OPTIONS(description='Código de caso asignado por el miembro (emisor o adquirente).'),
num_caso_vrol STRING  OPTIONS(description='Número de caso generado en la plataforma VROL.'),
pvc_id STRING  OPTIONS(description='Código identificador del "PVC"'),
mto_venta FLOAT64  OPTIONS(description='Monto total de la transacción en moneda local.'),
tipo_tarjeta STRING  OPTIONS(description='Indicador de crédito (CR) o débito (DR).'),
cod_moneda STRING  OPTIONS(description='Código de moneda usada en la transacción.'),
moneda STRING  OPTIONS(description='Moneda usada en la transacción.'),
cod_respuesta STRING  OPTIONS(description='Código interno'),
cod_transaccion STRING  OPTIONS(description='Identificador único de la transacción.'),
arn_transaccion STRING  OPTIONS(description='Acquirer Reference Number – número único de seguimiento asignado por la red.'),
nom_comercio STRING  OPTIONS(description='Nombre del comercio donde se realizó la transacción.'),
usuario BYTES  OPTIONS(description='Usuario o sistema que registró el caso.'),
cod_tracking STRING  OPTIONS(description='Código o número de referencia de la transacción en la red.'),
jurisdiction STRING  OPTIONS(description='Jurisdicción o país de la transacción.'),
pvc_id_alternativo STRING  OPTIONS(description='Identificador alternativo del "PVC" seguro para la transacción. (Ocurre cuando se realizaron los pagos con google pay o apple pay)'),
cod_categoria_contracargo STRING  OPTIONS(description='Categoría general del contracargo.'),
cod_subcategoria_contracargo STRING  OPTIONS(description='Condición o motivo específico del contracargo.'),
cod_caso_vrol STRING  OPTIONS(description='Identificador financiero asignado en VROL.'),
cod_bundle_vrol STRING  OPTIONS(description='Agrupación o bundle ID del caso en la plataforma de Visa.'),
mto_comision_foraneo FLOAT64  OPTIONS(description='Monto de comisión internacional aplicada.'),
tipo_tarjeta_comision_foranea STRING  OPTIONS(description='Indicador de débito o crédito sobre la comisión internacional.'),
cod_moneda_comision_foranea STRING  OPTIONS(description='Codigo de moneda de la comisión internacional.'),
cod_estado STRING  OPTIONS(description='Código del estado actual del contracargo.'),
descripcion_estado STRING  OPTIONS(description='Descripción legible del estado del contracargo.'),
flag_atm STRING  OPTIONS(description='Flag que indica si fue una transacción ATM'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date TIMESTAMP NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD')
)
PARTITION BY process_date
CLUSTER BY tipo_contracargo, cod_moneda, moneda, cod_estado
OPTIONS (description='Tabla que contiene la informacion historica de contracargos provenientes de la plataforma Visa');
