CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_as400.mcft044t (
peprod STRING  OPTIONS(description='Producto'),
pecest STRING  OPTIONS(description='Establecimiento'),
pectra STRING  OPTIONS(description='Transaccion'),
pefpro STRING  OPTIONS(description='Fecha Proceso'),
pebcop STRING  OPTIONS(description='Bco Pagador'),
petpag STRING  OPTIONS(description='Acc Chq'),
peccch BYTES  OPTIONS(description='Nro Cc O Chq'),
peccmc STRING  OPTIONS(description='Cta Cte Mcp'),
peruc STRING  OPTIONS(description='R.U.C'),
pemone STRING  OPTIONS(description='Moneda'),
peimpo STRING  OPTIONS(description='Importe'),
pecomi STRING  OPTIONS(description='Comision'),
peimpr STRING  OPTIONS(description='Impuesto Proces'),
penet1 STRING  OPTIONS(description='Neto 1'),
peicdv STRING  OPTIONS(description='Cobro De Devoluc'),
penet2 STRING  OPTIONS(description='Neto 2'),
peiret STRING  OPTIONS(description='Imp Retenidos'),
pen2us STRING  OPTIONS(description='Neto 2 Soles'),
penet3 STRING  OPTIONS(description='Neto 3'),
pefabo STRING  OPTIONS(description='Fecha Abono Real'),
petcta STRING  OPTIONS(description='Tipo Cta Ah/Cc'),
pepagt STRING  OPTIONS(description='Pago A Tercero'),
party_id_izi_tercero STRING  OPTIONS(description='Ruc/Dni Tercer'),
penomt STRING  OPTIONS(description='Nombre Tercero'),
party_id_izi STRING  OPTIONS(description='Ruc Establecim'),
pesitu STRING  OPTIONS(description='Situacion'),
peusac STRING  OPTIONS(description='User Actualiza'),
pemens STRING  OPTIONS(description='Mensaje'),
peabom STRING  OPTIONS(description='F.Abono Modifica'),
pendab STRING  OPTIONS(description='Nro Dias Abono'),
pescot STRING  OPTIONS(description='Sist Comp Tercero'),
peqopa STRING  OPTIONS(description='Cantidad'),
peface STRING  OPTIONS(description='Fact Estab'),
pefabr STRING  OPTIONS(description='Fecha Abono Ref'),
pechqn STRING  OPTIONS(description='Chq Pagese A'),
peagru STRING  OPTIONS(description='Agrupa Abonos'),
pefcta STRING  OPTIONS(description='Fuerza Cuenta'),
penfia STRING  OPTIONS(description='Nro File Abono'),
pectib STRING  OPTIONS(description='Cta Interbanc'),
petdot STRING  OPTIONS(description='Tipdoc Tercero'),
pectes STRING  OPTIONS(description='Cta Especial'),
pecafr STRING  OPTIONS(description='Facilitador'),
peemon STRING  OPTIONS(description='Tip Facili'),
peceab STRING  OPTIONS(description='Cod Est Abono'),
pencom STRING  OPTIONS(description='Nom Comercial'),
pepfid STRING  OPTIONS(description='Pay Facil Id'),
petdoi STRING  OPTIONS(description='Tipdoc Iden'),
petipe STRING  OPTIONS(description='Tipo Pendiente'),
pefdcp STRING  OPTIONS(description='Fecha Incomin Dcp'),
peajus STRING  OPTIONS(description='Ajuste Dcp'),
pemoti STRING  OPTIONS(description='Motivo Dcp'),
peobse STRING  OPTIONS(description='Observacion'),
peimem STRING  OPTIONS(description='Impuesto Emisor'),
pecedc STRING  OPTIONS(description='Codigo Dcp'),
peicpr STRING  OPTIONS(description='Ind Capt Proces'),
ocusr STRING  OPTIONS(description='User Ult. Modif.'),
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date TIMESTAMP NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD')
)
PARTITION BY process_date
CLUSTER BY petpag, party_id_izi, pesitu, pescot
OPTIONS (description='Abonos en cuenta pendientes única');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_as400.mcfv017 (
ocide STRING  OPTIONS(description='Codigo De Actividad'),
occia STRING  OPTIONS(description='Codigo De Compañia'),
ocsuc STRING  OPTIONS(description='Codigo De Sucursal'),
ocmon STRING  OPTIONS(description='Codigo De Moneda'),
olcot STRING  OPTIONS(description='Tipo Cotizacion'),
ofano STRING  OPTIONS(description='Año De Cotizacion'),
ofmes STRING  OPTIONS(description='Mes De Cotizacion'),
ofdia STRING  OPTIONS(description='Dia De Cotizacion'),
ovcom STRING  OPTIONS(description='Valor T/C Compra'),
ovven STRING  OPTIONS(description='Valor T/C Venta'),
ofill STRING  OPTIONS(description='Espacio Dispon.'),
ofmod STRING  OPTIONS(description='Fecha Ult. Modif. Ddmmaaaa'),
ohmod STRING  OPTIONS(description='Hora Ult. Modif.'),
ocusr STRING  OPTIONS(description='User Ult. Modif.'),
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date TIMESTAMP NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD')
)
PARTITION BY process_date
OPTIONS (description='Histórico de tipo de cambio soles/dolares');


