CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_cybersource.searchnegativelistresults( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
nombre_registro STRING  OPTIONS(description= 'Identificación o nombre asignado al registro de la marca de fraude.'), 
fecha_creacion STRING  OPTIONS(description= 'Fecha en que se creó el registro en el sistema.'), 
creado_por STRING  OPTIONS(description= 'Usuario o sistema que generó el registro de marca.'), 
id_grupo STRING  OPTIONS(description= 'Identificador único del grupo asociado al registro (puede ser un grupo de análisis, región, etc.).'), 
id_comercio STRING  OPTIONS(description= 'Identificador único del comercio donde ocurrió la transacción.'), 
id_cuenta_cliente STRING  OPTIONS(description= 'Identificador único asociado a la cuenta del cliente involucrado en la transacción.'), 
telefono_facturacion BYTES  OPTIONS(description= 'Número de teléfono proporcionado para la facturación.'), 
telefono_envio BYTES  OPTIONS(description= 'Número de teléfono proporcionado para el envío.'), 
tipo_pago STRING  OPTIONS(description= 'Método de pago utilizado en la transacción (e.g., tarjeta de crédito, débito, etc.).'), 
sufijo_cuenta STRING  OPTIONS(description= 'Últimos dígitos de la cuenta o tarjeta utilizada en la transacción.'), 
bin_tarjeta_credito STRING  OPTIONS(description= 'Los primeros seis dígitos de la tarjeta de crédito, que identifican el banco emisor.'), 
correo BYTES  OPTIONS(description= 'Dirección de correo electrónico asociada a la cuenta o transacción.'), 
dominio_correo STRING  OPTIONS(description= 'Dominio del correo electrónico (e.g., gmail.com, yahoo.com).'), 
direccion_1 STRING  OPTIONS(description= 'Primera línea de la dirección asociada al cliente o la transacción.'), 
direccion_2 STRING  OPTIONS(description= 'Segunda línea de la dirección (opcional).'), 
ciudad STRING  OPTIONS(description= 'Ciudad asociada a la dirección del cliente o transacción.'), 
provincia STRING  OPTIONS(description= 'Provincia, estado o región de la dirección del cliente o transacción.'), 
codigo_postal STRING  OPTIONS(description= 'Código postal de la dirección del cliente o transacción.'), 
pais_region STRING  OPTIONS(description= 'País o región asociado a la dirección del cliente o transacción.'), 
direccion_ip BYTES  OPTIONS(description= 'Dirección IP del dispositivo utilizado para realizar la transacción.'), 
ip_red STRING  OPTIONS(description= 'Segmento de red al que pertenece la dirección IP utilizada.'), 
pais_region_bin_tarjeta STRING  OPTIONS(description= 'País o región asociado al BIN de la tarjeta utilizada.'), 
pais_region_ip STRING  OPTIONS(description= 'País o región asociado a la dirección IP utilizada en la transacción.'), 
pais_region_correo STRING  OPTIONS(description= 'País o región asociado al dominio del correo electrónico.'), 
huella_digital_dispositivo STRING  OPTIONS(description= 'Identificador único generado a partir de las características del dispositivo utilizado en la transacción.'), 
motivo_marca STRING  OPTIONS(description= 'Razón específica por la cual se marcó la transacción como sospechosa o fraudulenta.'), 
notas_marca STRING  OPTIONS(description= 'Notas adicionales relacionadas con la marca de fraude.'), 
id_solicitud_marca STRING  OPTIONS(description= 'Identificador único de la solicitud asociada a la marca de fraude.'), 
cpf_cnpj STRING  OPTIONS(description= 'Identificador fiscal del cliente (específico para Brasil, CPF para personas físicas y CNPJ para empresas).'), 
id_inteligente STRING  OPTIONS(description= 'Identificador generado por sistemas de inteligencia de fraude, basado en patrones o análisis.'), 
fecha_ultimo_uso STRING  OPTIONS(description= 'Fecha de la última actividad o uso de la información marcada.'), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='Transacciones de Izipay en su rol emisor');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.master_risk.t_cybersource_marcacion_fraude( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
nom_registro_marca_fraude STRING  OPTIONS(description= 'Identificación o nombre asignado al registro de la marca de fraude.'), 
fecha_creacion TIMESTAMP  OPTIONS(description= 'Fecha en que se creó el registro en el sistema.'), 
usuario_registro_marca STRING  OPTIONS(description= 'Usuario o sistema que generó el registro de marca.'), 
ident_unico_grupo STRING  OPTIONS(description= 'Identificador único del grupo asociado al registro (puede ser un grupo de análisis, región, etc.).'), 
ident_unico_comercio STRING  OPTIONS(description= 'Identificador único del comercio donde ocurrió la transacción.'), 
ident_unico_cuenta_cliente STRING  OPTIONS(description= 'Identificador único asociado a la cuenta del cliente involucrado en la transacción.'), 
telefono_facturacion BYTES  OPTIONS(description= 'Número de teléfono proporcionado para la facturación.'), 
telefono_envio BYTES  OPTIONS(description= 'Número de teléfono proporcionado para el envío.'), 
metodo_pago STRING  OPTIONS(description= 'Método de pago utilizado en la transacción (e.g., tarjeta de crédito, débito, etc.).'), 
ult_digitos_tarjeta STRING  OPTIONS(description= 'Últimos dígitos de la cuenta o tarjeta utilizada en la transacción.'), 
bin STRING  OPTIONS(description= 'Los primeros seis dígitos de la tarjeta de crédito, que identifican el banco emisor.'), 
correo BYTES  OPTIONS(description= 'Dirección de correo electrónico asociada a la cuenta o transacción.'), 
dominio_correo STRING  OPTIONS(description= 'Dominio del correo electrónico (e.g., gmail.com, yahoo.com).'), 
primera_linea_correo STRING  OPTIONS(description= 'Primera línea de la dirección asociada al cliente o la transacción.'), 
segunda_linea_correo STRING  OPTIONS(description= 'Segunda línea de la dirección (opcional).'), 
ciudad STRING  OPTIONS(description= 'Ciudad asociada a la dirección del cliente o transacción.'), 
provincia STRING  OPTIONS(description= 'Provincia, estado o región de la dirección del cliente o transacción.'), 
codigo_postal STRING  OPTIONS(description= 'Código postal de la dirección del cliente o transacción.'), 
pais STRING  OPTIONS(description= 'País o región asociado a la dirección del cliente o transacción.'), 
direccion_ip BYTES  OPTIONS(description= 'Dirección IP del dispositivo utilizado para realizar la transacción.'), 
segmento_red STRING  OPTIONS(description= 'Segmento de red al que pertenece la dirección IP utilizada.'), 
pais_bin STRING  OPTIONS(description= 'País o región asociado al BIN de la tarjeta utilizada.'), 
pais_ip STRING  OPTIONS(description= 'País o región asociado a la dirección IP utilizada en la transacción.'), 
pais_dominio_correo STRING  OPTIONS(description= 'País o región asociado al dominio del correo electrónico.'), 
huella_digital_dispositivo STRING  OPTIONS(description= 'Identificador único generado a partir de las características del dispositivo utilizado en la transacción.'), 
motivo_marca STRING  OPTIONS(description= 'Razón específica por la cual se marcó la transacción como sospechosa o fraudulenta.'), 
nota_marca STRING  OPTIONS(description= 'Notas adicionales relacionadas con la marca de fraude.'), 
id_solicitud_marca STRING  OPTIONS(description= 'Identificador único de la solicitud asociada a la marca de fraude.'), 
cpf_cnpj STRING  OPTIONS(description= 'Identificador fiscal del cliente (específico para Brasil, CPF para personas físicas y CNPJ para empresas).'), 
id_inteligente STRING  OPTIONS(description= 'Identificador generado por sistemas de inteligencia de fraude, basado en patrones o análisis.'), 
fecha_ultimo_uso TIMESTAMP  OPTIONS(description= 'Fecha de la última actividad o uso de la información marcada.'), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='Transacciones de Izipay en su rol emisor', require_partition_filter = true);

