CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_as400.mcfs005al (
pdprod STRING  OPTIONS(description='Producto'),
pdcest STRING  OPTIONS(description='Comercio'),
pdctra STRING  OPTIONS(description='Transaccion'),
pdfpro STRING  OPTIONS(description='Fecha Proceso'),
pdbcop STRING  OPTIONS(description='Bco Pagador'),
pdlote STRING  OPTIONS(description='Lote'),
pdtpem STRING  OPTIONS(description='Term Pos Entry Mode'),
pdbcor STRING  OPTIONS(description='Bco Receptor'),
pdbcoe STRING  OPTIONS(description='Bco Emisor'),
pvc_id STRING  OPTIONS(description='Tarjeta'),
pdftra STRING  OPTIONS(description='Fecha Transacc'),
pdndoc STRING  OPTIONS(description='Nro Documento'),
pdauto STRING  OPTIONS(description='Autorizacion'),
pdimpo STRING  OPTIONS(description='Importe'),
pdmone STRING  OPTIONS(description='Moneda'),
pdiacc STRING  OPTIONS(description='Abo/Car Comision'),
pdcomi STRING  OPTIONS(description='Comision'),
pdcopr STRING  OPTIONS(description='Comision Proces'),
pdimpr STRING  OPTIONS(description='Impuesto Proces'),
pdcoem STRING  OPTIONS(description='Comision Emisor'),
pdimem STRING  OPTIONS(description='Impuesto Emisor'),
pdmetr STRING  OPTIONS(description='Medio De Transac'),
pdflot STRING  OPTIONS(description='Fecha De Lote'),
pdlotr STRING  OPTIONS(description='Lote Referencia'),
pduser STRING  OPTIONS(description='Usuario'),
pdterm STRING  OPTIONS(description='Terminal'),
pdusap STRING  OPTIONS(description='Aprobado Por'),
pdfpen STRING  OPTIONS(description='Fecha Pendiente'),
pdicai STRING  OPTIONS(description='Ica Emisor'),
pdicaa STRING  OPTIONS(description='Ica Adquir'),
pdfjul STRING  OPTIONS(description='Fecha Juliana'),
pdmcc STRING  OPTIONS(description='Mcc'),
pdtcam STRING  OPTIONS(description='Tipo Cambio'),
pdimus STRING  OPTIONS(description='Importe Soles'),
pdtien STRING  OPTIONS(description='Tienda'),
pdsucu STRING  OPTIONS(description='Sucursal'),
pdtdev STRING  OPTIONS(description='Indica Devolucion (D: Devolución total, P: Devolución Parcial:   No tiene devolución)'),
pdager STRING  OPTIONS(description='Agen.Receptora'),
pdtipe STRING  OPTIONS(description='Tipo Pendiente'),
pdsaem STRING  OPTIONS(description='Saldo Emisor'),
pdpais STRING  OPTIONS(description='Pais'),
pdorig STRING  OPTIONS(description='Origen'),
pdprem STRING  OPTIONS(description='Premiado (P: Tiene premiación)'),
pdbren STRING  OPTIONS(description='Banknet Refe Nbr'),
pdaren STRING  OPTIONS(description='Acquirer Refe Nbr'),
pdpcom STRING  OPTIONS(description='% Comision Estab'),
pdcade STRING  OPTIONS(description='Cadena'),
pditem STRING  OPTIONS(description='Item'),
pdcico STRING  OPTIONS(description='Cod.Interca.Comi'),
pdtain STRING  OPTIONS(description='Tasa Intercambio'),
pdtint STRING  OPTIONS(description='Tipo Intercambio'),
pdrccl STRING  OPTIONS(description='Report Camara Local'),
pdtmci STRING  OPTIONS(description='Transac.Segun Mci (L: Local, I: Internacional: $Internacional Dolares)'),
pdcoer STRING  OPTIONS(description='Comi.Serv.Procesami'),
pdimer STRING  OPTIONS(description='Impu.Serv.Procesami'),
pdtmov STRING  OPTIONS(description='C:Cargo A:Abono'),
pdsens STRING  OPTIONS(description='Sdo Emisor Soles'),
pdfaes STRING  OPTIONS(description='Facturac Especial'),
pdlimi STRING  OPTIONS(description='Limite Piso'),
pdclaf STRING  OPTIONS(description='Clase Facturador'),
pdfpre STRING  OPTIONS(description='Fec.Pro.Referencia'),
pdfopa STRING  OPTIONS(description='Forma Pago'),
pdmpdi STRING  OPTIONS(description='Mes Pago Diferido'),
pdncuo STRING  OPTIONS(description='Nro Cuotas'),
pdvcuo STRING  OPTIONS(description='Valor De Cuota'),
pdfpcu STRING  OPTIONS(description='Fecha 1Ra Cuota'),
pdauol STRING  OPTIONS(description='Autorizado En Ola'),
pdifee STRING  OPTIONS(description='$Flat "Fee"'),
pdtcpr STRING  OPTIONS(description='T.Cambio Proceso'),
pdfpem STRING  OPTIONS(description='Frec Proceso Emisor'),
pdfepe STRING  OPTIONS(description='Fech Proceso Emisor'),
pdfing STRING  OPTIONS(description='Fecha Ingreso'),
pdtcop STRING  OPTIONS(description='Tipo:Fac,N/C'),
pdncop STRING  OPTIONS(description='Nro Comprob Pago'),
pdseil STRING  OPTIONS(description='Serv.Intercam.Local'),
pdimil STRING  OPTIONS(description='Impu.Intercam.Local'),
pdnet1 STRING  OPTIONS(description='Neto1 Establecim'),
pdfaut STRING  OPTIONS(description='Fecha Autorizacion'),
pdiaut STRING  OPTIONS(description='Importe Autorizado'),
pdfire STRING  OPTIONS(description='Fec.Ing.Referencia'),
pdlore STRING  OPTIONS(description='Lote Ref'),
pditre STRING  OPTIONS(description='Item Ref'),
pdpvea STRING  OPTIONS(description='Estab Plaza Vea'),
pdsubp STRING  OPTIONS(description='Sub Prod/Gcms'),
pdfabo STRING  OPTIONS(description='Fecha Abono Real'),
pdndab STRING  OPTIONS(description='Nro Dias Abono'),
pdpsmi STRING  OPTIONS(description='Campaña Emisor'),
pdtire STRING  OPTIONS(description='Tiempo Respuesta'),
pdhaut STRING  OPTIONS(description='Hora Autoriz'),
pdagei STRING  OPTIONS(description='Agente Iata'),
pdairl STRING  OPTIONS(description='Cod Aerolinea'),
pdnopi STRING  OPTIONS(description='Operacion Iata'),
pdppen STRING  OPTIONS(description='1Er Pendiente'),
pdicax STRING  OPTIONS(description='Ica Emisor'),
pdird STRING  OPTIONS(description='Ird'),
pdregi STRING  OPTIONS(description='Region'),
pdsvc STRING  OPTIONS(description='Service Code'),
pdpauc STRING  OPTIONS(description='Protoc-Autent-Ucaf'),
pdicsh STRING  OPTIONS(description='Impo Cash'),
pdccsh STRING  OPTIONS(description='Comis Cash'),
pdrefn STRING  OPTIONS(description='Trace Switch'),
pdposc STRING  OPTIONS(description='Pos Data Code'),
pdtcc STRING  OPTIONS(description='Tcc'),
pdtcta STRING  OPTIONS(description='Tipo Cta'),
pdarer STRING  OPTIONS(description='Arn Referencia'),
party_id_izi STRING  OPTIONS(description='Código identificador único del documento afiliado a iziPay'),
pdbono STRING  OPTIONS(description='Boleto/N Orden'),
pdmoti STRING  OPTIONS(description='Motivo'),
pdcoad STRING  OPTIONS(description='Comision Adq'),
pdimca STRING  OPTIONS(description='Igv Comi Adq'),
pdcpid STRING  OPTIONS(description='Card Prog Id'),
pdlpid STRING  OPTIONS(description='Licen Prod Id'),
pdprco STRING  OPTIONS(description='Procces Code'),
pdbslv STRING  OPTIONS(description='Buss Level'),
pdbsid STRING  OPTIONS(description='Buss Id'),
pdfdep STRING  OPTIONS(description='Fecha Deposito'),
pdfcnf STRING  OPTIONS(description='Fecha Confirmacion'),
pdmp01 STRING  OPTIONS(description='Cod Mprod 1'),
pdmi01 STRING  OPTIONS(description='Imp Mprod 1'),
pdmp02 STRING  OPTIONS(description='Cod Mprod 2'),
pdmi02 STRING  OPTIONS(description='Imp Mprod 2'),
pdmp03 STRING  OPTIONS(description='Cod Mprod 3'),
pdmi03 STRING  OPTIONS(description='Imp Mprod 3'),
pdmp04 STRING  OPTIONS(description='Cod Mprod 4'),
pdmi04 STRING  OPTIONS(description='Imp Mprod 4'),
pdmp05 STRING  OPTIONS(description='Cod Mprod 5'),
pdmi05 STRING  OPTIONS(description='Imp Mprod 5'),
pdcafj STRING  OPTIONS(description='Articulo Afijo'),
pdmint STRING  OPTIONS(description='Modo Intecamb (S: Single, D:Dual)'),
pdsadv STRING  OPTIONS(description='No Aplicar Dev'),
pdtemv STRING  OPTIONS(description='Terminal Emv'),
pdprop STRING  OPTIONS(description='Term Propina'),
pdprau STRING  OPTIONS(description='Pre Aut'),
pdtpmm STRING  OPTIONS(description='Term Pos Mult Mon'),
pdcsqn STRING  OPTIONS(description='Card Seq Nbr'),
pdemv STRING  OPTIONS(description='Emv'),
pdndev STRING  OPTIONS(description='Nro Dev Dia'),
pdprio STRING  OPTIONS(description='Prioridad Dev'),
pdppro STRING  OPTIONS(description='% Propina'),
pdcamp STRING  OPTIONS(description='Campaña'),
pdbin STRING  OPTIONS(description='Bin'),
pvc_id_2 STRING  OPTIONS(description='Tarjeta'),
pdtarm STRING  OPTIONS(description='Tarjeta Mask'),
pdtarr STRING  OPTIONS(description='Tarjeta Rec'),
pdltar STRING  OPTIONS(description='Long Tarj'),
pdface STRING  OPTIONS(description='Fact Estab (D: Diario, M:Mensual)'),
pdobse STRING  OPTIONS(description='Observa'),
pdtiep STRING  OPTIONS(description='Tienda'),
pdfabp STRING  OPTIONS(description='Fec Abo Proce'),
pdfcmp STRING  OPTIONS(description='Fec Compensa'),
pdeiba STRING  OPTIONS(description='Emi Iba'),
pdpiba STRING  OPTIONS(description='Pag Iba'),
pdde22 STRING  OPTIONS(description='D22 Pem'),
pdde61 STRING  OPTIONS(description='D61 Pos Code'),
pdissu STRING  OPTIONS(description='Emisor Swt'),
pdacqu STRING  OPTIONS(description='Adquir Swt'),
pdde07 STRING  OPTIONS(description='De07 Swt'),
pdde15 STRING  OPTIONS(description='De15 Netdate'),
pdfcom STRING  OPTIONS(description='Flat Comis'),
pdfeci STRING  OPTIONS(description='Fec Interc'),
pdimpi STRING  OPTIONS(description='Imp Interc'),
pdesqu STRING  OPTIONS(description='Esquema'),
pdtcom STRING  OPTIONS(description='Tipo Comision (EM: Escal MCC, EE: Estab, ER: Escal RUC, CE: Camp Estab, CR: Camp RUC, FL: Flat, PJ: Porcentaje)'),
pdnrid STRING  OPTIONS(description='Nro Id'),
pddcem STRING  OPTIONS(description='Dist Comi Emi'),
pdimdc STRING  OPTIONS(description='Impo Dcc'),
pdmodc STRING  OPTIONS(description='Mone Dcc'),
pdrmdc STRING  OPTIONS(description='Rate Margin Dcc'),
pdexdc STRING  OPTIONS(description='Exchange Rate Dcc'),
pdiedc STRING  OPTIONS(description='Impo Equiv Dcc'),
pdpfid STRING  OPTIONS(description='Pay Facil Id'),
pdceex STRING  OPTIONS(description='Comi Emis Extr'),
pdseex STRING  OPTIONS(description='Serv Emis Extr'),
pdimse STRING  OPTIONS(description='Impu.Serc Extra'),
pdfexp STRING  OPTIONS(description='Fexpi Aamm'),
pdstxn STRING  OPTIONS(description='Sta.Txn D61.S7'),
pdiauf STRING  OPTIONS(description='Aut.F D48.S61.F5'),
pdtout STRING  OPTIONS(description='Tipo Outgo'),
pdfliq STRING  OPTIONS(description='Fecha Liqui'),
pdwall STRING  OPTIONS(description='Ind Wallet'),
pdcafr STRING  OPTIONS(description='Facilitador'),
pdemon STRING  OPTIONS(description='Tip Facili'),
pdcapt STRING  OPTIONS(description='Capt Switch'),
pdncom STRING  OPTIONS(description='Nom Comercial'),
pdaav STRING  OPTIONS(description='Aav Seccode'),
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date DATETIME NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD'),
PRIMARY KEY (pdcest, pvc_id, pdaren) NOT ENFORCED
)
PARTITION BY process_date
OPTIONS (description='Pagos a establecimientos por detale, transacciones que entraron al proceso de liquidación');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_dataentry_operaciones.ard_arn (
valor_original STRING  OPTIONS(description='valor_original'),
mc_aprobador STRING  OPTIONS(description='mc_aprobador'),
valor_destino STRING  OPTIONS(description='valor_destino'),
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date DATETIME NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD')
)
PARTITION BY process_date
OPTIONS (description='Catálogo de ARN por defecto para cargar al campo arn_ard');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_dataentry_operaciones.arn_ard_fuente_ard_arn_87_034 (
valor_original STRING  OPTIONS(description='valor_original'),
mc_aprobador STRING  OPTIONS(description='mc_aprobador'),
valor_destino STRING  OPTIONS(description='valor_destino'),
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date DATETIME NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD')
)
PARTITION BY process_date
OPTIONS (description='Catálogo de ARN por defecto para cargar al campo arn_ard_fuente');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_dataentry_operaciones.arn_ard_fuente_ard_arnfuente (
valor_original STRING  OPTIONS(description='valor_original'),
mc_aprobador STRING  OPTIONS(description='mc_aprobador'),
valor_destino STRING  OPTIONS(description='valor_destino'),
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date DATETIME NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD')
)
PARTITION BY process_date
OPTIONS (description='Catálogo de ARN por defecto para cargar al campo arn_ard_fuente');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_dataentry_operaciones.entrymode_ard_arn87_03 (
ard_arn87_034 STRING  OPTIONS(description='ard_arn87_034'),
entrymode STRING  OPTIONS(description='entrymode'),
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date DATETIME NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD')
)
PARTITION BY process_date
OPTIONS (description='Catálogo de ARN87_03 para el campo entrymode');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_dataentry_operaciones.entrymode_ard_arnfuente (
ard_arnfuente STRING  OPTIONS(description='ard_arnfuente'),
entrymode STRING  OPTIONS(description='entrymode'),
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date DATETIME NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD')
)
PARTITION BY process_date
OPTIONS (description='Catálogo de ARNfuente para el campo entrymode');


