CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.master_risk.m_contracargo_devolucion (
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
cod_producto STRING  OPTIONS(description='Código del tipo de producto de la transacción.'),
nom_facilitador STRING  OPTIONS(description='Pasarela/agrupador que procesó la transacción (p. ej., Izipay).'),
cod_comercio STRING  OPTIONS(description='Código del comercio (7 dígitos del CIO/establecimiento).'),
desc_situacion_comercio STRING  OPTIONS(description='Situación/estado operativo del comercio o del registro al procesarse.'),
nom_comercio STRING  OPTIONS(description='Nombre comercial o de fantasía del comercio.'),
party_id_izi STRING  OPTIONS(description='Código identificador del documento afiliado a IziPay'),
razon_social BYTES  OPTIONS(description='Razón social registrada del comercio.'),
segmento STRING  OPTIONS(description='Segmento del comercio'),
giro_comercio STRING  OPTIONS(description='Código y nombre del giro del comercio'),
metodo_ingreso STRING  OPTIONS(description='Modo de captura (chip, banda, manual, e-commerce, contactless, etc.).'),
fecha_proceso DATE  OPTIONS(description='Fecha en que el registro fue cargado/procesado en el sistema.'),
fecha_trx DATE  OPTIONS(description='Fecha de la transacción original.'),
cod_tipo_trx STRING  OPTIONS(description='Identificador/número de la transacción.'),
tarjeta_enmascarada STRING  OPTIONS(description='Tarjeta enmascarada, conformada por los 6 primeros dígitos, 6 astericos y 4 últimos dígitos'),
bin STRING  OPTIONS(description='Bin de 9'),
cod_autorizacion STRING  OPTIONS(description='Código de autorización de la transacción.'),
cod_moneda STRING  OPTIONS(description='Código de moneda de la transacción (604=PEN, 840=USD).'),
moneda STRING  OPTIONS(description='Moneda de la transacción (604=PEN, 840=USD).'),
mto_venta_bruto FLOAT64  OPTIONS(description='Monto bruto de la transacción.'),
comision_comercio FLOAT64  OPTIONS(description='Comisión cobrada al comercio'),
comision_adquirente FLOAT64  OPTIONS(description='Comisión del adquirente (MCPerú).'),
impuesto_adquirente FLOAT64  OPTIONS(description='Impuesto aplicado a la comisión del adquirente.'),
comision_emisor FLOAT64  OPTIONS(description='Comisión/interchange del emisor.'),
mto_venta_neto FLOAT64  OPTIONS(description='Monto neto resultante tras comisiones/impuestos (liquidable).'),
mto_pendiente_caso FLOAT64  OPTIONS(description='Saldo pendiente por recuperar asociado al caso.'),
arn STRING  OPTIONS(description='Número de referencia del adquirente (ARN) para trazabilidad.'),
ard STRING  OPTIONS(description='Identificador/código interno de seguimiento en AS400 (PDARER).'),
estado_cobro_adquirente STRING  OPTIONS(description='Estado de cobro gestionado por PMP.'),
estado_cobro_facilitador STRING  OPTIONS(description='Estado de cobro gestionado por Izipay.'),
mto_cobrado_adquirente FLOAT64  OPTIONS(description='Monto cobrado por PMP.'),
mto_pendiente_facilitador FLOAT64  OPTIONS(description='Saldo pendiente de cobro por Izipay.'),
cod_razon_contracargo STRING  OPTIONS(description='Reason code del contracargo/devolución.'),
estado_caso STRING  OPTIONS(description='Estado del caso (p. ej., abierto, cerrado, ganado, perdido).'),
usuario_aprobador STRING  OPTIONS(description='Usuario/área que ingresó o gestionó el registro.'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date DATETIME NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD'),
PRIMARY KEY (party_id_izi) NOT ENFORCED
)
PARTITION BY process_date
CLUSTER BY cod_comercio, giro_comercio, fecha_proceso, estado_caso
OPTIONS (description='Tabla transformada con los datos de retenciones 34 y devoluciones 876');
