CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_as400.mcfh781( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
b1nser STRING  OPTIONS(description= 'Nro. Serie Equipo Pos'), 
b1cest STRING  OPTIONS(description= 'Comercio O Ubicación'), 
b1nchi STRING  OPTIONS(description= 'Nro. Serie Del Chip'), 
b1pdes STRING  OPTIONS(description= 'Perfil De Descarga'), 
b1fins STRING  OPTIONS(description= 'Fecha De Instalación'), 
b1term STRING  OPTIONS(description= 'Nro.Terminal'), 
b1mcom STRING  OPTIONS(description= 'Medio De Comunicacion'), 
b1futf STRING  OPTIONS(description= 'Fecha Ultima Trx Financiera'), 
b1futa STRING  OPTIONS(description= 'Fecha Ultima Trx Administra'), 
b1feco STRING  OPTIONS(description= 'Fecha Ultima Trx Echo'), 
b1hutf STRING  OPTIONS(description= 'Hora  Ultima Trx Financiera'), 
b1huta STRING  OPTIONS(description= 'Hora  Ultima Trx Administra'), 
b1heco STRING  OPTIONS(description= 'Hora  Ultima Trx Echo'), 
b1ffac STRING  OPTIONS(description= 'Flag De Facturación.'), 
b1fmul STRING  OPTIONS(description= 'Flag De Multicomercio'), 
b1futd STRING  OPTIONS(description= 'Fecha De Ultima Descarga'), 
b1hutd STRING  OPTIONS(description= 'Hora De Ultima Descarga'), 
b1vers STRING  OPTIONS(description= 'Version'), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='Base de datos archivo de PC');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_as400.mcft782( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
bdnser STRING  OPTIONS(description= 'NRO. SERIE EQUIPO POS'), 
bdsiac STRING  OPTIONS(description= 'SITUACIÓN EQUIPO'), 
bdcate STRING  OPTIONS(description= 'CATEGORÍA'), 
bdcacf STRING  OPTIONS(description= 'MARGUESI'), 
bdmarc STRING  OPTIONS(description= 'MARCA'), 
bdmode STRING  OPTIONS(description= 'MODELO'), 
bdcest STRING  OPTIONS(description= 'COMERCIO O UBICACIÓN'), 
bdsitu STRING  OPTIONS(description= 'SITUACIÓN DEL COMERCIO'), 
party_id_izi STRING  OPTIONS(description= 'RUC'), 
bdrsoc STRING  OPTIONS(description= 'RAZON SOCIAL'), 
bdncom STRING  OPTIONS(description= 'NOMBRE COMERCIAL'), 
bddire BYTES  OPTIONS(description= 'DIRECCION'), 
bdubof STRING  OPTIONS(description= 'UBIGEO'), 
bddepa STRING  OPTIONS(description= 'DEPARTAMENTO'), 
bdprov STRING  OPTIONS(description= 'PROVINCIA'), 
bddist STRING  OPTIONS(description= 'DISTRITO'), 
bdcpos STRING  OPTIONS(description= 'CODIGO POSTAL'), 
bdzona STRING  OPTIONS(description= 'REFERENCIA'), 
bdnchi STRING  OPTIONS(description= 'NRO. SERIE DEL CHIP'), 
bdcelu STRING  OPTIONS(description= 'TELEFONO'), 
bdtiop STRING  OPTIONS(description= 'OPERADOR'), 
bdains STRING  OPTIONS(description= 'TIPO DE INST DEFAULT'), 
bdfins STRING  OPTIONS(description= 'FECHA DE INSTALACIÓN'), 
bdterm STRING  OPTIONS(description= 'NRO.TERMINAL'), 
bdmcom STRING  OPTIONS(description= 'MEDIO DE COMUNICACION'), 
bdfutf STRING  OPTIONS(description= 'FECHA ULTIMA TRX FINANC'), 
bdfuta STRING  OPTIONS(description= 'FECHA ULTIMA TRX ADM'), 
bdfeco STRING  OPTIONS(description= 'FECHA ULTIMA TRX ECHO'), 
bdhutf STRING  OPTIONS(description= 'HORA  ULTIMA TRX FINANC'), 
bdhuta STRING  OPTIONS(description= 'HORA  ULTIMA TRX ADM'), 
bdheco STRING  OPTIONS(description= 'HORA  ULTIMA TRX ECHO'), 
bdffac STRING  OPTIONS(description= 'FLAG DE FACTURACIÓN.'), 
bdfmul STRING  OPTIONS(description= 'FLAG DE MULTICOMERCIO'), 
bdfutd STRING  OPTIONS(description= 'FECHA DE ULTIMA DESCARGA'), 
bdhutd STRING  OPTIONS(description= 'HORA DE ULTIMA DESCARGA'), 
bdvers STRING  OPTIONS(description= 'VERSION'), 
bdpdes STRING  OPTIONS(description= 'PERFIL DE DESCARGA'), 
bdfpro STRING  OPTIONS(description= 'FECHA DE PROCESO'), 
bdhpro STRING  OPTIONS(description= 'HORA  DE PROCESO'), 
bdfmcc STRING  OPTIONS(description= 'FLAG MCCCENTER = 1'), 
bdfcom STRING  OPTIONS(description= 'FECHA DE COMPRA'), 
bdesta STRING  OPTIONS(description= 'ESTADO'), 
bddisp STRING  OPTIONS(description= 'C.DE SIT. 1=DIS 2=REPAR'), 
bdfdep STRING  OPTIONS(description= 'FECHA DEPRECIACION'), 
bdpcom STRING  OPTIONS(description= 'PRECIO DE COMPRA'), 
bddafj STRING  OPTIONS(description= 'DEPREC. ANIO ANTERIOR'), 
bddefj STRING  OPTIONS(description= 'DEPREC. DEL ANIO'), 
bdpain STRING  OPTIONS(description= 'PREC.AJUSTADO.X.INFLAC.'), 
bdvnet STRING  OPTIONS(description= 'BDPCOM-BDDAFJ-BDIDFJ'), 
bdtico STRING  OPTIONS(description= 'TIPO DE COMERCIO'), 
bdbanc STRING  OPTIONS(description= 'DESCRIPCION DE BANCO'), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='Diario BD Unificadas');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_as400.akfmitem( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
csiac STRING  OPTIONS(description= 'COD. DE SITUACION DEL ACTIVO'), 
cccos STRING  OPTIONS(description= 'CODIGO DEL CENTRO DE COSTO'), 
cseaf STRING  OPTIONS(description= 'CODIGO DE SECCION'), 
cunfj STRING  OPTIONS(description= 'CODIGO DE UNIDAD'), 
cclf1 STRING  OPTIONS(description= 'CLASIFICACION ARTICULO -1'), 
cclf2 STRING  OPTIONS(description= 'CLASIFICACION ARTICULO -2'), 
cclf3 STRING  OPTIONS(description= 'CLASIFICACION ARTICULO -3'), 
cclf4 STRING  OPTIONS(description= 'CLASIFICACION ARTICULO -4'), 
cacfj STRING  OPTIONS(description= 'CODIGO DEL ARTICULO'), 
tacfj STRING  OPTIONS(description= 'DESCRIPCION DEL ARTICULO'), 
tmrfj STRING  OPTIONS(description= 'DESCRIPCION DE MARCA'), 
tmofj STRING  OPTIONS(description= 'DESCRIPCION DE MODELO'), 
nsefj STRING  OPTIONS(description= 'NUMERO DE SERIE'), 
cesfj STRING  OPTIONS(description= 'DESCRIP. ESTADO A=BUENO B=REGULAR C=MALO D=STOCK'), 
cidfj STRING  OPTIONS(description= 'CODIGO DE SITUACION 1=DISPONIBLE 2=REPARACION'), 
cprov STRING  OPTIONS(description= 'FILLER SIN USO'), 
nnifj STRING  OPTIONS(description= 'NUMERO ORDEN DE COMPRA'), 
dcofj STRING  OPTIONS(description= 'DIA DE COMPRA'), 
mcofj STRING  OPTIONS(description= 'MES DE COMPRA'), 
acofj STRING  OPTIONS(description= 'AÑO DE COMPRA'), 
cmone STRING  OPTIONS(description= 'CODIGO DE MONEDA'), 
itcmo STRING  OPTIONS(description= 'IMPORTE TIPO DE CAMBIO'), 
ipcfj STRING  OPTIONS(description= 'IMPORTE PRECIO UNIT. COMPRA'), 
pdefj STRING  OPTIONS(description= 'PORC.ANUAL DE DEPRECIACION'), 
cdefj STRING  OPTIONS(description= 'T: TOTALMENTE,U: ULTIMO AÑO'), 
irefj STRING  OPTIONS(description= 'IMP. REVALUACION DEL AÑO'), 
idefj STRING  OPTIONS(description= 'IMP. DEPRECIACION DEL AÑO'), 
irafj STRING  OPTIONS(description= 'REVALU.EJERCICIOS ANTERIORES'), 
idafj STRING  OPTIONS(description= 'DEPREC.EJERCICIOS ANTERIORES'), 
midfj STRING  OPTIONS(description= 'MES INICIO DE DEPRECIACION'), 
aidfj STRING  OPTIONS(description= 'AÑO INICIO DE DEPRECIACION'), 
dinfj STRING  OPTIONS(description= 'DIA DE INGRESO'), 
minfj STRING  OPTIONS(description= 'MES DE INGRESO'), 
ainfj STRING  OPTIONS(description= 'AÑO DE INGRESO'), 
ducfj STRING  OPTIONS(description= 'DIA ULTIMA ACTUALIZACION'), 
mucfj STRING  OPTIONS(description= 'MES ULTIMA ACTUALIZACION'), 
aucfj STRING  OPTIONS(description= 'AÑO ULTIMA ACTUALIZACION'), 
cisfj STRING  OPTIONS(description= 'INDICA SEGURO S/N'), 
cilfj STRING  OPTIONS(description= 'INDICA LEASING S/N'), 
pcifj STRING  OPTIONS(description= 'PRECIO UNIT.COMPRA EN INTIS'), 
iajfj STRING  OPTIONS(description= 'PRECIO AJUSTADO POR INFLAC.'), 
usefj STRING  OPTIONS(description= 'USUARIO TENEDOR DE ITEM'), 
prdfj STRING  OPTIONS(description= 'PROVEEDOR'), 
guifj STRING  OPTIONS(description= 'GUIA DE REMISION'), 
folfj STRING  OPTIONS(description= 'FOLIO'), 
fuprl STRING  OPTIONS(description= 'FEC ULT PROC LOTE'), 
grrfj STRING  OPTIONS(description= 'GUIA REMISION REMITENTE'), 
fgrrfj STRING  OPTIONS(description= 'FEC GUIA REM.REMI'), 
terfj STRING  OPTIONS(description= 'NUMERO TERMINAL'), 
invefj STRING  OPTIONS(description= 'CODIGO INVENTARIO'), 
ipcfje STRING  OPTIONS(description= 'IMP.M.E.PRECIO UNIT. COMPRA'), 
esntfj STRING  OPTIONS(description= 'ESTADO SUNAT R=BUENO D=DESUSO  O=OBSOLETO'), 
afcelu STRING  OPTIONS(description= 'NUMERO DE CELULAR'), 
afclns STRING  OPTIONS(description= 'NUMERO DE SERIE'), 
nsefjc STRING  OPTIONS(description= 'NUMERO DE SERIE'), 
aflico STRING  OPTIONS(description= 'MARCA LINEA CONTROL'), 
aftico STRING  OPTIONS(description= 'TIPO DE COMUNICACION'), 
afpgac STRING  OPTIONS(description= 'MARCA CAMBIO DE UBICACION'), 
afacub STRING  OPTIONS(description= 'FECHA CAMBIO DE UBICACION'), 
aftiex STRING  OPTIONS(description= 'TIPO EXISTENCIA'), 
afosce STRING  OPTIONS(description= 'CODIGO OSCE'), 
afnume STRING  OPTIONS(description= 'NUM. TRAS.'), 
afnudo STRING  OPTIONS(description= 'NUM. DOC.'), 
affapa STRING  OPTIONS(description= 'FECHA APERTURA DE LIBRO AF'), 
afsecc STRING  OPTIONS(description= 'SECCION CONTABLE DEL TRASPAS'), 
didfj STRING  OPTIONS(description= 'DIA INICIO DE DEPRECIACION'), 
aftipc STRING  OPTIONS(description= 'TIPO DE COMPROBANTE'), 
afserc STRING  OPTIONS(description= 'SERIE DE COMPROBANTE'), 
afnumc STRING  OPTIONS(description= 'NUMERO DE COMPROBANTE'), 
afnorc STRING  OPTIONS(description= 'NUMERO ORDEN DE COMPRA'), 
afsubs STRING  OPTIONS(description= 'SUBSECUENCIA DE TRASPASO'), 
afuser STRING  OPTIONS(description= 'USUARIO CAMBIO UBICACION'), 
afcuot STRING  OPTIONS(description= 'NUMERO DE CUOTAS'), 
afmven STRING  OPTIONS(description= 'CAMPAÑA DE VENTA'), 
afrepo STRING  OPTIONS(description= 'REPOSISIÓN EXPRES'), 
afacls STRING  OPTIONS(description= 'CLASE DEL AF'), 
afgcod STRING  OPTIONS(description= 'CODIGO DE GRUPO'), 
affam STRING  OPTIONS(description= 'FAMILIA AF'), 
afsbf STRING  OPTIONS(description= 'SUBFAMILIA AF'), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='Datos generales items del activo fijo');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_as400.akfmarti( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
cclf1 STRING  OPTIONS(description= 'CODIGO ARTICULO 1'), 
cclf2 STRING  OPTIONS(description= 'CODIGO ARTICULO 2'), 
cclf3 STRING  OPTIONS(description= 'CODIGO ARTICULO 3'), 
cclf4 STRING  OPTIONS(description= 'CODIGO ARTICULO 4'), 
tclfj STRING  OPTIONS(description= 'DESCRIPCION DEL ARTICULO'), 
cctc1 STRING  OPTIONS(description= 'CODIGO SCTA 1'), 
cctc2 STRING  OPTIONS(description= 'CODIGO SCTA 2'), 
cctc3 STRING  OPTIONS(description= 'CODIGO SCTA 3'), 
cctc4 STRING  OPTIONS(description= 'CODIGO SCTA 4'), 
cctc5 STRING  OPTIONS(description= 'CODIGO SCTA 5'), 
cctc6 STRING  OPTIONS(description= 'CODIGO SCTA 6'), 
cctc7 STRING  OPTIONS(description= 'CODIGO SCTA 7'), 
cctc8 STRING  OPTIONS(description= 'CODIGO SCTA 8'), 
cctc9 STRING  OPTIONS(description= 'CODIGO SCTA 9'), 
ccdep STRING  OPTIONS(description= 'CTA.DEP.ACUM.'), 
ccgto STRING  OPTIONS(description= 'CTA.GASTO'), 
anali STRING  OPTIONS(description= 'ANALITICA'), 
artins STRING  OPTIONS(description= 'TIPO INSTALACION'), 
cchip STRING  OPTIONS(description= 'POS GRPS:S,N'), 
tiprol STRING  OPTIONS(description= 'TIPO DE ROLLO'), 
artico STRING  OPTIONS(description= 'TIPO DE COMUNICACION'), 
ctipar STRING  OPTIONS(description= 'TIPO DE ARRENDAMIENTO'), 
record_source STRING  OPTIONS(description= 'CODIGO DE EMPRESA'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='Maestro de códigos de artículos');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_as400.alfm004( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
chseri STRING  OPTIONS(description= 'NUMERO DE SERIE'), 
chtiop STRING  OPTIONS(description= 'TIPO OPERADOR'), 
chcelu STRING  OPTIONS(description= 'NUMERO DE CELULAR'), 
chfcom STRING  OPTIONS(description= 'FECHA DE COMPRA'), 
chgcom STRING  OPTIONS(description= 'GUIA DE COMPRA'), 
chprec STRING  OPTIONS(description= 'PRECIO'), 
chmarg STRING  OPTIONS(description= 'MARGUESI DEL POS'), 
chesta STRING  OPTIONS(description= 'ESTADO'), 
chsitu STRING  OPTIONS(description= 'SITUACION'), 
choper STRING  OPTIONS(description= 'OPERACION'), 
charti STRING  OPTIONS(description= 'CODIGO ARTICULO'), 
chdesc STRING  OPTIONS(description= 'DESCRIPCION'), 
chumod STRING  OPTIONS(description= 'USUARIO MODIFI'), 
chpmod STRING  OPTIONS(description= 'PANTALL MODIFI'), 
chfmod STRING  OPTIONS(description= 'FECHA MODIFICA'), 
chhmod STRING  OPTIONS(description= 'HORA  MODIFICA'), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='Maestro de chips');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_as400.akfv002( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
afanoi STRING  OPTIONS(description= 'ANO ACT.FIJO'), 
afflag STRING  OPTIONS(description= 'FLAG INFLACION'), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='Arch. Inflación anual');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_as400.mcfv050( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
tipcom STRING  OPTIONS(description= 'TIPO DE COMERCIO'), 
dtipco STRING  OPTIONS(description= 'DESC.TIPO COMERCIO'), 
ultcod STRING  OPTIONS(description= 'ULT.CODIGO GENERADO'), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='Tabla de códigos automáticos de comercio');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_as400.alfw004( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
mecome STRING  OPTIONS(description= 'COD. ESTAB'), 
metipo STRING  OPTIONS(description= 'TIPO CODIGO'), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='Archivo almacénes y provincias');

CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_as400.mcfv030e( 
process_date DATE NOT NULL OPTIONS(description= 'Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a la foto del día anterior (D-1)'), 
mdcoco STRING  OPTIONS(description= 'Codigo de comercio'), 
mdtien STRING  OPTIONS(description= 'Numero de tienda'), 
mdterm STRING  OPTIONS(description= 'Numero de terminal'), 
mdserm STRING  OPTIONS(description= 'Serie del MPOS'), 
mdterr STRING  OPTIONS(description= 'Numero de terminal real'), 
mdfere STRING  OPTIONS(description= 'Fecha de registro'), 
mdhore STRING  OPTIONS(description= 'Hora de registro'), 
mdfeul STRING  OPTIONS(description= 'Fecha ultima actualizacion'), 
mdhoul STRING  OPTIONS(description= 'Hora ultima actualizacion'), 
mdsermx STRING  OPTIONS(description= 'Serie del MPOS 2'), 
record_source STRING  OPTIONS(description= 'Dato de Auditoría: Descripción del aplicativo origen de los datos.'), 
load_date TIMESTAMP NOT NULL OPTIONS(description= 'Fecha y hora de inserción del registro en el modelo'), 
creation_user STRING NOT NULL OPTIONS(description= 'Usuario que crea el registro en la BD'), 
)
PARTITION BY process_date
OPTIONS (description ='Extensión del archivo mcfv030');

