CREATE OR REPLACE TABLE prd-izipay-data-storage-pv.raw_dataentry_operaciones.miscelaneos (
cambio STRING  OPTIONS(description='Indica si es intercambio es Local (L) o Internacional (I)'),
ingreso STRING  OPTIONS(description='Fecha de ingreso del contracargo'),
envio STRING  OPTIONS(description='Codigo ICA del emisor'),
recibe STRING  OPTIONS(description='Codigo ICA del adquirente (Izipay = 007963)'),
mti STRING  OPTIONS(description='MTI codigo interno'),
fun STRING  OPTIONS(description='Codigo Fun indica la etapa del contracargo'),
tarjeta STRING  OPTIONS(description='Tarjeta enmascarada'),
bin STRING  OPTIONS(description='Bin de la tarjeta enmascarada'),
tipo STRING  OPTIONS(description='Tipo contracargo'),
mone STRING  OPTIONS(description='Codigo de la moneda del contracargo'),
importe STRING  OPTIONS(description='Importe del contracargo'),
autori STRING  OPTIONS(description='Codigo de autorizacion de la transaccion'),
acqrefdata STRING  OPTIONS(description='ARD de la transaccion'),
cod_estab STRING  OPTIONS(description='Codigo del comercio'),
nombre STRING  OPTIONS(description='Nombre del comercio'),
nro_control STRING  OPTIONS(description='Número de control del contracargo'),
razon STRING  OPTIONS(description='Codigo de razon, indica el motivo del contracargo'),
term STRING  OPTIONS(description='Codigo de terminal'),
adqu STRING  OPTIONS(description='País del adquirente'),
emis STRING  OPTIONS(description='País del emisor'),
mensaje STRING  OPTIONS(description='Mensaje del contracargo'),
fraureporteusuario STRING  OPTIONS(description='Codigo del reporte de usuario'),
sit STRING  OPTIONS(description='Situación del contracargo'),
situa STRING  OPTIONS(description='Fecha de aceptación, caso contrario 0'),
gestor STRING  OPTIONS(description='Codigo MC del usuario gestor'),
obserregularizaciones STRING  OPTIONS(description='Observacion en caso de regularizaciones'),
process_date DATE NOT NULL OPTIONS(description='Fecha de foto/datos configurada en el ETL para la extracción de datos, corresponde a aperturas de comercios hasta el cierre del día anterior'),
record_source STRING NOT NULL OPTIONS(description='Dato de Auditoría: Descripción del aplicativo origen de los datos.'),
load_date DATETIME NOT NULL OPTIONS(description='Fecha y hora de inserción del registro en el modelo'),
creation_user STRING NOT NULL OPTIONS(description='Usuario que crea el registro en la BD'),
PRIMARY KEY (fun) NOT ENFORCED
)
PARTITION BY process_date
OPTIONS (description='Tabla que contiene contracargos miscelaneos cargados externamente');
